[danny.ho] 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #20
Opened 2021-01-05 07:55 UTC by kcoms555

안녕하세요, 첫 코드 리뷰를 받을 생각에 두근두근합니다!

danny, joy, corby와 3명에서 같이 진행을 하였는데요, 진행하는 동안 여러가지로 많은 토론을 하였습니다.

Car라는 객체가 있을 때, new로 할당하는 책임은 Car 인스턴스들을 관리하는 CarManager 가 해야하는가, main 같은 중앙 로직에서 처리 하는게 좋은가
순회하면서 배열을 처리를 할때, for loop 문으로 처리하는게 좋은가, stream() 을 사용하는게 좋은가
CarTest라는 테스트 로직 내부에
private static final int NEVER_MOVE_CONDITION = 3;
private static final int ALWAYS_MOVE_CONDITION = 4;
와 같이 Car 객체 내부의 상수값에 종속되는, 하지만 CarTest라는 테스트 로직 이외에는 사용할 일이 없을 것으로 예상되는 상수를 선언하는 코드가 있습니다.
이 코드를 Car 객체에서 public으로 선언하는게 옳을지, CarTest 테스트 객체에서 private로 선언하는게 옳을지 많은 의견이 있었습니다.
위에 사항들과 기타 다른 점들에 대해, 리뷰어님은 어떻게 생각하는지 가감없는 의견 부탁드리겠습니다.

2021-01-05 10:37 UTC, dongjoon1251 requested changes
안녕하세요. 자동차 경주를 맡게된  제노스입니다.
제가 보게된 첫번째 리뷰요청이라서 저도 두근두근거렸습니다 :)
리뷰를 진행하고 나서 질문주신 부분들에 대해 답변드리려고 했는데 이미 코드 근처에 리뷰를 남겼네요. 
build.gradle 파일에 이슈가 있어서 빌드가 안되는데 같이 확인 부탁드립니다.

2021-01-05 10:37 UTC, dongjoon1251 commented on build.gradle
> +<<<<<<< HEAD
merge할 때 conflict이 발생했을 것 같네요. 이런 부분들이 몇군데 보입니다. 확인 부탁드려요~

2021-01-05 10:37 UTC, dongjoon1251 commented on README.md
> +## 기능 요구사항(원본)
TODO list를 잘 작성해주셨네요 💯 
commit log도 나누어서 남겨주셨는데, TODO list에 나온 기능 단위로 커밋 로그를 남기면 특정 기능을 revert 시키거나 어떤 작업이 진행되었는지 쉽게 확인할 수 있을 것 같습니다.
그리고 commit log가 영어로 되어 있는데 TODO list에 맞춰서 같이 한글로 남겨주셔도 좋을 것 같습니다.
README.md, README.txt 파일이 이렇게 2개 있는데 하나는 지우는게 어떨까요?

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/Car.java
> +            throw new IllegalArgumentException("자동차 이름 길이는 1이상 5이하 입니다");
InvalidCarNameException 과 같은 예외클래스를 만들어서 적용해보면 어떨까요?

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/InputView.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
문자열도 해당 클래스의 상수로 분리해보면 어떨까요?

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/OutputView.java
> +        String s = "";
String 을 합치는 방법으로 StringBuilder를 사용하는 방법도 있는데요. 어떤 방법이 더 효율적일지 확인해보시고 적용해보면 좋을 것 같습니다. 더불어서 특정 문자를 특정 횟수만큼 반복하게 해주는 함수는 없는지 검색해보면 어떨까요?

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/OutputView.java
> +        System.out.println(str);
str 이라는 의미가 모호한 변수로 분리한 후에 출력하는 것 보다는 method로 분리하거나 inline시키는게 어떨까요? 
가독성이 더 좋은 방향으로 가면 좋을 것 같습니다.

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/RacingCarGame.java
> +
메소드 내에서 줄바꿈은 코드상에서 한 단락을 구분하는 의미이기도 합니다. 반드시 줄바꿈을 넣어야하는 단락의 의미가 아니라면 없애는 것이 좋을 것 같습니다. 한 메소드 내의 코드는 10줄을 넘지 않도록 구현하는 요구사항이 있으니 같이 확인 부탁드립니다.

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/StringUtil.java
> +        return Arrays.asList(nameString.split(","));
사용되는 곳이 두군데 이상 되지 않는다면 StringUtil 클래스로 분리하지 않고 InputView 내부의 private method로 사용해보는게 어떨까요?

2021-01-05 10:37 UTC, dongjoon1251 commented on src/test/java/CarTest.java
> +    void length5이하() {
테스트의 의미를 좀더 잘 표현하기 위해서 한글 메소드명을 사용해주셨네요 👍 
@DisplayName과 같은 annotation을 사용하는 방법도 있으니 고려해주세요~

2021-01-05 10:37 UTC, dongjoon1251 commented on src/test/java/CarTest.java
> +    private static final int ALWAYS_MOVE_CONDITION = 4;
해당 상수를 사용하지 않고, Car의 MOVE_THRESHOLD를 사용해보는게 어떨까요?
MOVE_THRESHOLD만 수정해도 테스트들이 실패하는 케이스가 발생할 수 있습니다.

2021-01-05 10:37 UTC, dongjoon1251 commented on src/test/java/CarTest.java
> +        assertThat(car.getPosition()).isEqualTo(1);
test code는 given/when/then 패턴에 맞춰서 줄바꿈으로 분리해주시면 가독성이 좋아질 수 있습니다.
그리고 하나의 테스트 메소드 안에는 최대한 assert구문을 하나만 넣도록 작성해보면 어떨까요? :)

2021-01-05 10:37 UTC, dongjoon1251 commented on src/test/java/NumberUtilTest.java
> +    void 난수생성() {
테스트 코드는 코드를 수정하지 않는 한 항상 같은 결과가 나와야 합니다. 
랜덤에 관련된 테스트 코드는 최대한 지양하는 것이 좋습니다.

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/CarManager.java
> +public class CarManager {
해당 클래스는 Car의 일급 컬렉션 역할을 하는 것으로 보입니다. 잘 분리해주셨네요 👍 
일급컬렉션에 대해서 처음 들어보셨다면 한번 찾아보셔도 좋을 것 같습니다.
클래스명은 Cars로 바꾸고 메소드 명도 같이 바꾸어보면 어떨까요?
pushCar -> push 나 add
moveCars -> move

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/CarManager.java
> +                .collect(Collectors.toList());
stream vs for 
이 문제에는 정답이 없습니다. 다만 그때그때 더 잘 어울리는 코드를 써주시면 됩니다. 이에 관련해서 찾아보시면 다수의 의견들이 나옵니다. 이것과 관련해서 어느정도 장단점이 정리되어 있는 링크를 공유드립니다. 제 블로그는 아니고 저도 찾아보니 아래와 같은 글이 나오네요. 아래 글이 꼭 모든 경우에 정답이라고 할 수는 없지만 참고해보시면 좋을 것 같습니다.

https://jaehun2841.github.io/2019/02/16/effective-java-item45/#%EC%84%9C%EB%A1%A0

이러한 정답이 없는 문제들은 프로그래밍을 하다보면 많이 만나게 됩니다. 
이에 대해서 인지하고 지금처럼 동료들과 같이 토론해보는 경험은 향후에도 도움이 많이 될 것으로 예상됩니다. 👍

2021-01-05 10:37 UTC, dongjoon1251 commented on src/main/java/CarManager.java
> +        }
Car를 움직이는 기준이 지금은 random이지만 나중에 다른 기준을 적용할 때 최대한 코드의 수정을 적게 하려면 어떤 방식으로 수정해보면 좋을까요? 한번 동료들과 같이 고민해보시면 좋을 것 같습니다.

2021-01-05 13:58 UTC, kcoms555 commented on build.gradle
> +<<<<<<< HEAD
레포지토리를 통으로 옮기다가 이런 문제가 발생하였는데, 이런 실수를 해서 죄송합니다. 반영하였습니다.

2021-01-05 14:02 UTC, kcoms555 commented on README.md
> +## 기능 요구사항(원본)
1. 기능 단위 로그와 한글 or 영어 통일 : 기능 단위로 커밋 로그를 남기고, 언어는 하나로 통일하는 습관 들이겠습니다.
2. README.txt : 네 같이 공동 작업을 하는데, 팀원이 .md파일 형식을 볼 수 없는 알 수 없는 현상이 있어서 동일한 파일을 만들었었습니다. 삭제하였습니다.

2021-01-05 14:37 UTC, kcoms555 commented on src/main/java/Car.java
> +            throw new IllegalArgumentException("자동차 이름 길이는 1이상 5이하 입니다");
InvalidCarNameException 을 만들어서 적용을 해보았습니다. 그런데, 자바에서 예외 클래스를 어떤 위치에 두어야할지(새로운 파일에 둘지, Car 클래스 내부에 둘지) 컨벤션을 찾지 못하여서, Car와 직접적으로 관련된 예외 클래스이니 Car 내부에 public class 의 형태로 만들었습니다. 이렇게 하는게 옳은건가요?

2021-01-05 14:45 UTC, kcoms555 commented on src/main/java/InputView.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
상수로 취급해도 문제없는 문자열을 모두 클래스 상수로 대체하였습니다. 그런데, UI 관련 클래스는 문자열이 많이 나타나게 될 텐데, 수십개 이상으로 많아질 때는 어떻게 취급하나요?

2021-01-05 16:11 UTC, kcoms555 commented on src/main/java/OutputView.java
> +        String s = "";
- 직접 테스트를 해보니 position 크면 문자열 합치는 비용(O(n^2))이 매우 증가한다는 것을 알게되어서, 앞으로 반복적으로 StringBuilder 를 적극 사용하도록 하겠습니다. 
- 반복에 대하여 조사를 해보니, 문자열을 반복해주는 함수는 여러가지가 있는데, 대표적으로 String.repeat가 있었지만 아쉽게도 버전이 맞지 않아, Java 8에서 지원하는 스트림을 활용하여, Collections.nCopies 와 Stream.collect 를 사용해보았습니다.

2021-01-05 16:15 UTC, kcoms555 commented on src/test/java/NumberUtilTest.java
> +    void 난수생성() {
난수 생성을 여러번 시도해서 난수 값들이 모두 의도한 값 범위 내에 있는지 확인하려는 의도입니다. 랜덤에 관련된 테스트 코드 명심하겠습니다.

2021-01-05 16:18 UTC, kcoms555 commented on src/main/java/OutputView.java
> +        System.out.println(str);
str를 formattedCarsStatus로 변수명을 변경해보았습니다.

2021-01-05 16:25 UTC, kcoms555 commented on src/main/java/CarManager.java
> +                .collect(Collectors.toList());
좋은 링크 감사합니다!

2021-01-05 16:37 UTC, kcoms555 commented on src/main/java/CarManager.java
> +public class CarManager {
CarManager는 Car 객체만 관리하고, 상태와 행위를 분리하는게 제일 좋겠다 했는데, 이게 일급컬렉션이라는 걸 처음 알았습니다!
Cars로 변환하고, 이에 맞춰서 여러 메소드 명을 변경해보았습니다.

2021-01-05 16:54 UTC, kcoms555 commented on src/test/java/CarTest.java
> +    private static final int ALWAYS_MOVE_CONDITION = 4;
NEVER & ALWAYS_MOVE_CONDITION 은 MOVE_THRESHOLD 에 종속적이게, Car에서 MOVE_THRESHOLD를 참조해서 할당하게 하였습니다. 해당 상수들을 사용하지 않는 방법을 고려해보았지만 외부 사용자가 보기에 의미가 더 명확해서 상수들은 그대로 유지하였습니다.

2021-01-05 16:57 UTC, kcoms555 commented on src/main/java/CarManager.java
> +        }
가장 어려운 고민인 것 같습니다. moveOrNot의 인자를 제거를 하거나, 인자가 들어가는 곳에 차량 이동 조건을 제어하는 클래스, 혹은 메소드로 한번더 감싸는 식으로 추상화하는게 좋아보입니다..

2021-01-05 23:56 UTC, dongjoon1251 commented on src/main/java/Car.java
> +            throw new IllegalArgumentException("자동차 이름 길이는 1이상 5이하 입니다");
질문주신 부분에 대해서 정답은 없습니다. 선택지로는 말씀해주신 방법도 있고 package로 분리하는 방식도 있습니다. car package로 따로 분리하면 해당 패키지안의 코드는 접근이 가능해서 Car 클래스를 테스트할때도 편하게 사용할 수 있습니다.

2021-01-06 00:02 UTC, dongjoon1251 commented on src/main/java/InputView.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
이문제도 정답은 없지만, UI별로 상수를 따로 관리하는 클래스를 만들기도 하고 UI 관련 클래스 자체를 좀더 세분화해서 나누는 방법도 있을 것 같습니다.

2021-01-06 00:19 UTC, dongjoon1251 approved these changes
말씀드린 부분에 대해서 피드백을 잘 반영해주셨네요 :)
몇가지 코멘트를 남겼으니 다음 단계에서 반영해주시기 바랍니다.

2021-01-06 00:19 UTC, dongjoon1251 commented on src/main/java/InputView.java
> +    private static final String STRING_HOW_MANY_TIMES_TRIES = "시도할 회수는 몇회인가요?";
상수는 변수보다 먼저 선언해주세요 :)

2021-01-06 00:19 UTC, dongjoon1251 commented on src/main/java/Cars.java
> +    public void push(Car car) {
해당 메소드를 공개하게되면 외부에서 자유롭게 일급컬렉션의 객체를 변경할 수 있습니다. 
cars 를 생성할 때 필요한 로직으로 판단됩니다. 이부분은 private으로 바꾸고 생성자를 통해서 사용하도록 수정해보면 어떨까요?

2021-01-06 00:19 UTC, dongjoon1251 commented on src/main/java/Cars.java
> +    public void createCarsByNames(List<String> names) {
이부분은 생성자의 역할을 하는 것으로 판단됩니다. List<String> names를 이용해서 Cars(LIst<Car>) 생성자를 호출하는 static 메소드로 변경해보면 어떨까요?

2021-01-06 00:19 UTC, dongjoon1251 commented on src/test/java/CarTest.java
> +    void moveForward(int trial) {
이 경우에는 CsvSource보다는 ValueSource를 사용해보면 어떨까요?

2021-01-06 00:19 UTC, dongjoon1251 commented on src/test/java/NumberUtilTest.java
> +    void 난수생성() {
해당 Util 클래스의 메소드를 통해서 최대, 최소값을 지정하여 random 값을 생성하도록 변경하면 말씀하시는 의도에 더 잘 맞을 것 같습니다. :)

2021-01-06 00:19 UTC, merged