[ellie.klm 김예지] 코드 리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #21
Opened 2021-01-05 07:58 UTC by Ye-Ji-Kim

2021-01-05 13:54 UTC, kriery requested changes
안녕하세요 엘리, 리뷰 쓰는 크리스입니다.
간결하고 군더더기 없는 코드로 작성해 주셨네요.
domain, UI 분리에 신경을 더 써주시고, 테스트를 보강해 주셨으면 좋을것 같아 피드백 드렸어요.
리뷰어가 만능은 아니라서, 적절히 의견을 남겨주셔도 좋습니다 🌟

2021-01-05 13:54 UTC, kriery commented on src/main/java/calculator/StringCalculator.java
> +    }
null 또는 empty를 판별하는 기능이라면, `isNullOrEmpty` 정도가 적당하지 않았을까요?

2021-01-05 13:54 UTC, kriery commented on src/main/java/racingcar/Car.java
> +    }
getter 는 가급적이면 지양하는게 맞지만, UI 로직을 domain으로 가지고 오는 것 만큼 중요하지는 않아요 😱

2021-01-05 13:54 UTC, kriery commented on src/main/java/racingcar/RacingGame.java
> +            throw new IllegalArgumentException("한대 이상의 자동차를 입력해주세요.");
적절한 Exception 처리 👍 칭찬합니다.

2021-01-05 13:54 UTC, kriery commented on src/main/java/racingcar/RacingGame.java
> +        return input.equals("") || input == null;
input이 `null`이라면 어떻게 되나요?
```suggestion
        return input == null || input.equals("");
```
같아 보이지만 같지 않아요 ([short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation))

2021-01-05 13:54 UTC, kriery commented on src/main/java/racingcar/RacingGame.java
> +        return (int) (Math.random() * 10);
이 방법도 훌륭하지만, 참고해 두시면 좋을것 같아요
[Random.nextInt](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#nextInt-int-)

2021-01-05 13:54 UTC, kriery commented on src/main/java/racingcar/RacingGameApp.java
> +
`scan.nextXX`와 `System.out`이 domain 로직과 섞여서 메서드가 다소 길어졌네요.
Input 담당 객체 / Output 담당 객체를 분리해서 정리하면 좋을것 같아요

2021-01-05 13:54 UTC, kriery commented on src/test/java/racingcar/CarTest.java
> +    }
getter의 사용을 지양하는 것은, 의도치 않은 사이드 이펙트를 줄이기 위해서예요.
ex) Map<String,Object> getAllParameter() -> obj.getAllParameter().put("mykey", "My Value");
테스트가 어려울만큼 노출을 은닉하는 것은 바람직하지 않은것 같아요.
getLocation을 부활하여 테스트를 좀 더 보강해 보는것은 어떨까요?

2021-01-06 08:51 UTC, Ye-Ji-Kim commented
1. input 담당 객체와 output 담당 객체를 분리하라 하신 부분을 제가 제대로 이해한 것인지 모르겠습니다. 제가 구현한 방향이 리뷰어님이 말씀해주신 방향과 일치하는 지 궁금합니다.
2. 피드백 외에 추가적으로 유틸성 메소드들은 Util 객체로 분리하였으며, 우승자를 찾는 로직을 위한 메서드들은 모두 RacingGame 객체가 담당할 수 있도록 수정하였습니다.

2021-01-06 10:40 UTC, kriery approved these changes
피드백을 깔끔하게 잘 반영하셨어요. 고생 많으셨을것 같네요.
이번에 제안하는 내용은 한개 밖에 없네요.
이 내용은 다음 스탭에 적용해주셔도 됩니다.
머지할게요. 계속 화이팅입니다!

2021-01-06 10:40 UTC, kriery commented on src/main/java/racingcar/Utils.java
> +        return generator.nextInt(10);
Literal은 가급적이면 상수화 해서 처리하는 것이 좋습니다

2021-01-06 10:40 UTC, merged