[echo.ohce 김환석] 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #23
Opened 2021-01-05 08:37 UTC by 10000sukk

안녕하세요 echo 입니다. 코드 리뷰 해주시면 감사하겠습니다.

그리고 몇가지 질문사항이 있습니다! 답변 주시면 감사하겠습니다!

1. Test 기반으로 코드를 짜는 도중에 구현하다가 test 코드에 빨간줄(오류) 가 뜰 경우는 보통 어떻게 처리 하는 게 정석 인가요?

2. Racing class 에서 checkCarNames 메서드를 도저히 들여쓰기 2가 넘지 않게 리펙토링 하지 못하겠습니다. 이럴 경우 해결책을 알려주시면 감사하겠습니다.

3. 지금 까지의 TDD 는 느낌상으로 top-down 으로 짜는 느낌이였는데 원래 큰것 부터 구현하는 게 정석인것인가요?

4. TDD 를 사용해서 구현 할 경우에 메서드의 인자 값으로 랜덤 값이 필요한 경우에 테스트를 어떻게 하는 것이 좋을까요?

2021-01-05 10:23 UTC, ljh131 requested changes
잘 봤습니다.
몇 가지 수정이 필요할 것 같습니다. 특히 테스트 부분이요.
그리고 다음엔 어떤 단계에 대한 PR인지 명시해주시면 좋겠습니다.

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Car.java
> +        if (value >= 4) {
상수가 좋지 않을까요

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +    private int getMaxPosition(List<Integer> positions) {
스트림을 사용하면 간단하게 될 것 같네요.

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +        return (int) (Math.random() * 10);
Random.nextInt는 어떤가요?
현재 메서드명이 애매한데, 10을 인자로 받는것도 좋을 것 같네요.

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Car.java
> +    private final int MAX_VALUE = 9;
무엇에 대한 min, max인지를 변수명으로 나타내야 좋을 것 같습니다.

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Car.java
> +        if(value > MAX_VALUE || value < MIN_VALUE) throw new RuntimeException();
범위를 벗어나면 어떻게 하라는 요구사항은 딱히 없긴 합니다만.
에러에 대한 정보가 있는 익셉션이 좋을 것 같습니다.

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +        }while(!checkCarNames(names));
반복문이 왜 필요한건가요?

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +    private int createNumber() {
메서드명이 모호합니다.

2021-01-05 10:23 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +        for(int carIndex: getWinnerCarsIndex(maxPosition, getFinalCarPositions())){
인덱스를 따로 구할 필요가 있을까요? 여기서 바로 찾으면 더 간단히 될 것 같네요.

2021-01-05 10:23 UTC, friediceday commented on src/test/java/racingcar/RacingTest.java
> +        rc.startRacing(3, 0);
이 안에서 사용자 입력을 받는데, 어떻게 동작하는 테스트인가요?
그리고 파라매터를 안받는데 인자를 넘기고 있네요.

2021-01-05 10:23 UTC, friediceday commented on src/test/java/racingcar/RacingTest.java
> +public class RacingTest {
전체 레이싱 과정 통채로 테스트 하는 것 역시 필요하겠지만,
하나 하나의 메서드들이 동작하는지에 대한 테스트도 필요할 것 같네요.

2021-01-05 10:23 UTC, friediceday commented on src/test/java/racingcar/CarTest.java
> +
이건 왜 비어있나요?

2021-01-05 10:45 UTC, ljh131 commented
질문 답변드립니다.

Test 기반으로 코드를 짜는 도중에 구현하다가 test 코드에 빨간줄(오류) 가 뜰 경우는 보통 어떻게 처리 하는 게 정석 인가요?
-> 빨간줄이 컴파일 에러를 말하는건가요? 테스트 실패를 말하는건가요? 둘다 수정해야 합니다.

Racing class 에서 checkCarNames 메서드를 도저히 들여쓰기 2가 넘지 않게 리펙토링 하지 못하겠습니다. 이럴 경우 해결책을 알려주시면 감사하겠습니다.
-> 간단하게 스트림으로 하셔도 됩니다.

지금 까지의 TDD 는 느낌상으로 top-down 으로 짜는 느낌이였는데 원래 큰것 부터 구현하는 게 정석인것인가요?
-> 정석이라는게 있는지 모르겠지만, 보통 그렇게 많이 하는 편인 것 같습니다. 그렇지만 편한대로 하시면 될 것 같습니다.

TDD 를 사용해서 구현 할 경우에 메서드의 인자 값으로 랜덤 값이 필요한 경우에 테스트를 어떻게 하는 것이 좋을까요?
-> 랜덤을 필요로 하는곳과 랜덤을 만드는 곳을 서로 분리해서 생각해보면 좋겠습니다.

2021-01-05 14:43 UTC, 10000sukk commented on src/test/java/racingcar/CarTest.java
> +
지금까지 주신 피드백들을 토대로 수정 완료 하였습니다. 피드백 많이 주셔서 정말 감사합니다....
수정하면서 너무 형편없이 짠거 같아서 죄송스러웠습니다... 죄송합니다...
쓸데없는 메서드들이 너무 많아서 삭제도 하고 수정도 하였습니다. 
그리고 테스트 같은 경우는 처음에 테스트 기반으로 짜다가 기능 구현 코드를 수정하면서 에러가 떳는데 테스트 기반으로 짯다는 것을 표현하기 위해서 남겨 뒀었는데 이게 잘못되었던 것이었군요! 테스트 public 으로 되있는것 위주로 랜덤 값 안받는 것들 테스트 하였습니다!

미흡한점 있으면 알려주신다면 정말 감사하겠습니다! 감사합니다!!

2021-01-06 03:01 UTC, ljh131 approved these changes
많이 좋아진 것 같습니다. 머지하겠습니다.
몇 가지 커멘트를 남겼으니 다음 단계에서 참고해주세요.

2021-01-06 03:01 UTC, friediceday commented on src/main/java/racingcar/Car.java
> +        if (randomValue < THRESHOLD_RANDOM_VALUE) return;
이런 형식은 인자가 유효한지 확인할때 자연스러울 것 같아요. (널이거나 공백 등등) 

특정 조건에 만족하는 경우에 포지션을 증가시키는 것이니 이 문장 그대로 조건문을 역으로 작성하지 않고 자연스럽게 작성하면 어떨까요

2021-01-06 03:01 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +        }while(!checkCarNames(names));
이 부분은 확인해주세요.

2021-01-06 03:01 UTC, friediceday commented on src/main/java/racingcar/Racing.java
> +        Random random = new Random();
한번만 생성하는게 좋겠습니다. 게다가 매번 생성하면 분포상 균일하지 않을 가능성이 있습니다.

2021-01-06 03:01 UTC, friediceday commented on src/test/java/plusNumber/PlusNumberCalTest.java
> +
이렇게 공백이 들쑥날쑥 한것도 신경써보면 좋겠습니다.
메서드들도 붙어있는게 있고 너무 떨어져있는 것도 있고요.

2021-01-06 03:01 UTC, merged