[kuri.copper 송동욱] 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #25
Opened 2021-01-05 09:37 UTC by D-kuri

안녕하세요! :) 
코드 리뷰와 함께 몇가지 질문 드리고 싶습니다.

1) 도메인 Layer -> View Layer, View Layer -> 도메인 Layer로 데이터를 전달할 때 사용하는 DTO(data transfer object)의 경우 setter/getter를 허용한다. 이부분이 잘 이해가 가지 않습니다. getter , setter를 어떻게하면 최대한 줄일수 있고 어떠한 경우에 사용해야 하는지 알고 싶습니다.

2) 자바 접근제어자에 대해서 좀 더 알고 싶습니다. 어떠한 경우에 어떤 접근 제어자를 사용해야 하는지 명확하게 알려주시면 감사하겠습니다 !

3) 처음 기능 구현 목록을 작성후 작은 기능에는 TDD를 사용하고 이후 좀 더 복잡한 로직이나 UI와 조금이라도 연동이 되는 부분은 TDD하는데 어려움이 많은것 같습니다. 그러다보니 로직은 계속 길어지고 커밋 타이밍도 놓치게 되는것 같은데 이러한 경우 어떻게 하면 좋을지 알고 싶습니다.

2021-01-05 11:30 UTC, dongjoon1251 requested changes
안녕하세요. racingcar 리뷰를 맡게된 제노스입니다 :)
먼저 질문에 대한 답변을 드리자면 아래와 같습니다.

1. 각각의 클래스 내부에 있는 변수를 최대한 외부에 적게 노출시키기 위해서 setter, getter를 줄여야 합니다. 하지만 해당 클래스가 가진 정보를 외부에서 알기 위해선 getter는 줄이기가 힘듭니다. 대신에 노출시키려는 변수가 Object 인 경우에 외부에서 필요한 필드들만 따로 추려서 DTO 클래스로 변환한 후에 리턴하는 방식으로 최대한 클래스 내부의 변수를 숨길 수 있습니다. setter의 경우도 클래스를 인스턴스로 생성한 후에, 해당 인스턴스의 public 메소드를 통해서 변수를 수정하는 로직은 클래스 내부에 있는 것이 좋습니다. 일례로, 이번 미션에서 Car 객체의 위치를 변경한다고 할 때, Car 객체의 위치를 직접 set하는 것이 아니라 move와 같은 메소드를 통해서 내부의 위치를 Car 클래스가 직접 다룰수 있도록 하는 것이 좋습니다. 

2. 해당 부분은 코드 상에 코멘트로 남겼습니다. 클래스 내부는 최대한 외부에 노출되지 않아야 한다는 것을 염두에 두시면 좀더 적용하기 쉽습니다. 간단하게는 대부분 private으로 선언하시고 노출 시킬 부분만 public으로 사용한다고 보시면 될 것 같습니다. 

3. 미션을 계속 수행하시다보면, 테스트를 수행하기 쉬운 코드로 변경하다보면 자연스럽게 코드의 가독성과 설계가 나아지는 경험을 하실 수 있습니다.   하나의 메소드 안에서 한가지 역할만 하도록 좀더 분리하시다보면 테스트가 더 쉬워질 수 있습니다. 이부분에 대해서는 코드상에 몇가지 코멘트를 남겼으니 확인 부탁드립니다 :)

질문 주신 부분들 외에도 궁금하신 부분이 많을 것으로 예상됩니다. 편하게 질문 주세요 :) 그리고 정답이 나와있는 건 아니지만 '클린 코드', '이펙티브 자바'라는 책을 참고하시면 질문주신 부분들에 있어서 도움이 많이 될 것으로 예상됩니다.

2021-01-05 11:30 UTC, dongjoon1251 commented on README.md
> +- 예외 처리
예외처리 부분은 작성하시다가 놓치신 것 같습니다. 확인 부탁드려요 :)

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Race.java
> +
특정 변수를 클래스로 분리한다는 것은 해당 변수의 수정이나 관리에 대해서 해당 클래스가 전적으로 책임을 진다는 의미로 해석할 수 있습니다. 그래서 클래스 내의 변수와 메소드는 기본적으로 private 으로 선언해준다고 생각하고, 외부에서 사용될 메소드에 대해서만 public으로 선언해주시는 것이 좋습니다.

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Race.java
> +        while(tryNum < 1){
하나의 메소드는 하나의 역할만 할 수 있도록 분리해보면 어떨까요? 
해당 메소드는 값을 입력받는 부분과 출력하는 부분이 하나의 메소드에 모두 포함된 것으로 보입니다.
더불어서 입력받는 부분만 관리하는 클래스, 출력하는 부분만 관리하는 클래스를 추가해보는 건 어떨까요?

ps. 잘못된 입력값이 들어왔을 때 실패하여 다시 반복 요청하는 부분은 일단 나중에 생각하고 
값을 한번만 입력받아서 처리하는 방법부터 다시 고려해보는 것이 좋을 것 같습니다.

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +
해당 클래스는 일급 컬렉션의 역할을 하는 것으로 보여집니다. 
일급컬렉션에 대해서 처음 들어보셨다면 이번에 공부해보면 어떨까요?
Racingcar보다는 car list를 관리하는 Cars가 더 어울릴 것 같은데 어떻게 생각하시나요? 
변수도 carList -> cars가 더 간결해보이는데 한번 고민해주세요 :)

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +        this.carList.forEach(car -> {
변수명, 메소드명은 축약하지 않고 전체 단어를 다 써주시는 것을 권장드립니다. 
짧아서 더 읽기 쉬울 수도 있지만 메소드명만으로는 의미 파악이 힘들어질 수 있습니다.
더불어서 주석을 쓰지 않고도 메소드 명만으로 의미를 전달하는 것이 가장 좋습니다 :)

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +        for (int i = 0; i < this.carList.size(); i++) {
이부분도 우숭자를 찾는 부분과 출력하는 로직이 섞여 있습니다. 분리해보면 어떨까요? :)

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/RandomNumber.java
> +    public void tryNum(Racingcar newRacingcar){
이부분은 해당 클래스의 역할과는 거리가 멀게 느껴집니다. 어느 클래스로 옮기는 것이 좋을까요?

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +        this.carList.forEach(car -> {
car에 위치를 지정하기 보다 위치를 변경하는 로직을 car내부에서 처리해보면 어떨까요? CarStatus를 사용하지 않는 방향으로도 고민해보시면 좋을 것 같습니다.

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +            str += "-";
String 을 합치는 방법으로 StringBuilder를 사용하는 방법도 있는데요. 어떤 방법이 더 효율적일지 확인해보시고 적용해보면 좋을 것 같습니다. 더불어서 특정 문자를 특정 횟수만큼 반복하게 해주는 함수는 없는지 검색해보면 어떨까요?

2021-01-05 11:30 UTC, dongjoon1251 commented on src/test/java/racingcar/RandomNumberTest.java
> +        assertThat(randomNum.setRandomNum()).isBetween(0, 9);
테스트 코드는 코드를 수정하지 않는 한 항상 같은 결과가 나와야 합니다.
랜덤에 관련된 테스트 코드는 최대한 지양하는 것이 좋습니다.

2021-01-05 11:30 UTC, dongjoon1251 commented on src/test/java/racingcar/RacingcarTest.java
> +        Race.carNames = "pobi,crong,honux";
test code는 given/when/then 패턴에 맞춰서 줄바꿈으로 분리해주시면 가독성이 좋아질 수 있습니다.
그리고 하나의 테스트 메소드 안에는 최대한 assert구문을 하나만 넣도록 작성해보면 어떨까요? :)

2021-01-05 11:30 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +    void addCarName(String[] carNames) {
클래스 내부에서만 쓰이는 함수들은 private으로 선언해주세요. 이부분은 다른 클래스의 메소드들도 확인해보시고 전반적으로 적용해보는게 어떨까요?

2021-01-05 12:33 UTC, D-kuri commented on README.md
> +- 예외 처리
앗 감사합니다 ! 제가 추가해놓고 커밋하지 않았네요

2021-01-05 18:05 UTC, D-kuri commented on src/main/java/racingcar/Race.java
> +
클래스 접근 제어에 대해서 제가 제대로 생각하지 않았네요 ㅠ 혹시 추가적으로 protected와 default 접근제어자와 public , private을 비교하여 어떤 경우에 사용해야 하는지 알려주실 수 있으신가요 !

2021-01-05 18:06 UTC, D-kuri commented on src/main/java/racingcar/Race.java
> +        while(tryNum < 1){
하나의 메소드에는 한개의 기능만 구현하도록 노력해보겠습니다 ! :)

2021-01-05 18:07 UTC, D-kuri commented on src/main/java/racingcar/Racingcar.java
> +
변수명 좀 더 이쁘게 짓도록 노력할게요... ㅎㅎ 일급컬렉션은 공부하여 적용해보도록 하겠습니다

2021-01-05 18:09 UTC, D-kuri commented on src/main/java/racingcar/Racingcar.java
> +        this.carList.forEach(car -> {
변수명을 축약하는 경우도 더러 있다고 알고 있습니다. 혹시 어느 경우에는 축약하고 어느 경우에는 전체를 쓰면 좋은지 알려주실수 있으신가요?? 또한 주석의 경우 어느정도로 남겨야 하는지도 궁금합니다 !

2021-01-05 18:11 UTC, D-kuri commented on src/main/java/racingcar/Racingcar.java
> +        for (int i = 0; i < this.carList.size(); i++) {
단일 책임 원칙 지켜가도록 노력하겠습니다 !

2021-01-05 18:21 UTC, D-kuri commented on src/main/java/racingcar/RandomNumber.java
> +    public void tryNum(Racingcar newRacingcar){
이부분은 클래스를 제가 생성하고 나서 이후에 코드를 작성하면서 저도 이상함을 많이 느꼈던 부분인데 어디서부터 수정해야 할지 감을 못잡고 그대로 제출했던것 같습니다. ㅠ 다음부터는 적절한 위치에 코드를 작성하도록 하겠습니다 !

2021-01-06 00:24 UTC, dongjoon1251 commented on src/main/java/racingcar/Race.java
> +
protected는 private 과 같은데 해당 클래스를 상속받는 child class에서는 접근이 가능합니다.
default는 주로  interface에서 기본 구현을 정의할 때 사용합니다.

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/GameManager.java
> +import java.util.OptionalInt;
해당 import는 사용되지 않는 것 같습니다. 
intelliJ를 사용하신다면 save action 사용 방법에 대해서 한번 검색해보시고, 저장할때마다 optimize import, reformat 등이 적용되게 세팅해보면 어떨까요?

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/GameManager.java
> +public class GameManager {
해당 클래스 내부의 로직들은 CarGame에 전부 있어도 무방해보입니다 :)
CarGame과 합치는게 어떨까요?

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/GameManager.java
> +            throw new RuntimeException("횟수를 1회 이상 입력해주세요.");
InvalidRountLengthException과 같이 예외에 대한 클래스를 직접 만들어서 사용해보면 어떨까요?

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/Input.java
> +    private static final Scanner sc = new Scanner(System.in);
Input, Output으로 잘 분리해주셨네요 👍 
향후에 적용할 MVC 패턴에 맞춰서 클래스명을 InputView, OutputView 등으로 바꿔보면 어떨까요?

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/Output.java
> +    }
입력을 받기 전에 출력할 메소드들은 Input으로 옮기고, inputCarNames(), inputRound() 등을 호출할때 내부에서 호출되도록 수정해보면 어떨까요?

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/Cars.java
> +    public void setCars(String carNames){
해당 클래스의 인스턴스를 생성한후에 내부 변수를 set하기 보다는 생성자에서 받아서 처리하도록 수정해보면 어떨까요?

2021-01-06 00:35 UTC, dongjoon1251 commented on src/main/java/racingcar/Racingcar.java
> +        this.carList.forEach(car -> {
같이 작업하는 팀 내에서 '이렇게 축약형을 쓰자'라고 같이 얘기된 것들은 축약해도 무방합니다. 다만 이번 미션 수행중에는 축약은 없다고 생각해주시면 좋을 것 같습니다. 주석은 사실 최대한 남기지 않는 것이 좋습니다. 주석을 써야 다른 사람이 이해할 수 있다면, 코드를 리팩토링해야한다는 신호가 될 수 있습니다.

2021-01-06 00:44 UTC, dongjoon1251 approved these changes
코멘트 드린 부분에 대해서 잘 반영해주셨네요 :)
몇가지 코멘트를 추가했습니다. 다음 단계에서 반영 부탁드립니다.

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Car.java
> +    private int loccation;
변수명 오타같습니다 :) getter 메소드도 같이 오타가 나온 것 같네요

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Car.java
> +        printLocation();
출력하는 로직이 포함되었네요. Output에서 처리되도록 수정해보면 어떨까요?

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Cars.java
> +        Output.printNewLine();
해당 메소드에도 출력하는 로직이 추가되었네요. GameManager에서 호출되도록 수정해보면 어떨까요?

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Cars.java
> +            if (car.getLoccation() == winnerLocation){
indent가 두번 되었네요. 메소드로 분리해보면 어떨까요?

2021-01-06 00:44 UTC, dongjoon1251 commented on src/test/java/racingcar/CarsTest.java
> +
Car에 대한 테스트 코드도 추가해주시기 바랍니다 :)

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Cars.java
> +    public String checkWinner(){
우승자를 확인해서 전달하는 목적에 가까운 것 같습니다. checkWinner보다는 findWinner, getWiner등으로 메소드명을 바꿔보면 어떨까요?

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Cars.java
> +    private int setRandomNumber(){
해당 메소드는 set보단 get에 더 가까워 보입니다.

2021-01-06 00:44 UTC, dongjoon1251 commented on src/main/java/racingcar/Cars.java
> +    private int checkMove(){
car를 움직이는 조건이 지금은 randomNumber이지만 나중에 기준이 달라질 수 있다고 가정하면, 어떤식으로 분리하는게 좋을지 고민해보시면 좋을 것 같습니다.

2021-01-06 00:45 UTC, merged