[snoopy.brown 김상열] 코드 리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #36
Opened 2021-01-05 13:28 UTC by syeol-kim

안녕하세요. 스누피입니다:D
자동차 경주 미션에 대해, 아래의 몇 가지 질문과 함께 코드 리뷰를 요청드립니다. 

1. TDD에 관한 질문입니다.  
구현 기능 목록만 작성하고 테스트를 만들다보면 어느순간 객체지향적이지 않고 무엇인가 이상함을 인지했습니다.
그래서 적당히 설계하고 테스트를 만들면 TDD를 하고 있는 것이 맞는지 의심하게 되었습니다.
이에 대한 조언을 얻고 싶습니다.
2. 자동차의 이동 가능여부를 확인하는 함수(isMovable)에 private를 지정했습니다.
이떄, isMovable에 대한 테스트 코드를 만들기 위해 접근지정자를 바꾸는 것이 좋은가요?
아니면 move에서 isMovable를 포함하고 있으니 move에 대한 테스트로 isMovable에 대한 테스트를 포함하고 있다고 할 수 있을까요?
3. 진행상황을 출력(ResultView.printProgress)할 때 ResultView에 Car 객체를 넘기는 방법보다 출력할 문자열을 넘기는 방법이 좋은가요?
아니면 출력할 문자열을 만들기 위한 정보(이름, 위치)만 따로 담아서 넘기는 방법이 좋을까요?

2021-01-06 01:40 UTC, humbledude requested changes
안녕하세요~ 리뷰를 맡은 조슈아입니다

리뷰 열심히 하고 있는데 중간에 싹 날리셔서 당황~ ㅎㅎ
하지만 맥락이 있으니 다행이었어요 ㅎㅎㅎㅎ
코멘트를 커밋단위로 리뷰하고 드렸으니, 사라진 코드에도 리뷰가 달렸는데요,
그런 부분은 그냥 참고 하시고요 ㅎㅎ
새 코드에 붙은 리뷰 중심으로 한번 검토해보시고 수정해서 다시 요청 주세요~

질문주신거에 답변 드립니다
1
TDD 와 객체지향에 대한 근본적인 질문을 해주셨는데요, 저의 의견 또한 의견이라는것을 알려드리며 ㅎㅎㅎ
TDD 와 객체지향은 상호 모순되는 개념이 아니라고 생각하는데요.
TDD 가 물론 설계에 지대한 영향을 미치는것은 알고 있습니다.
그렇다고 객체지향의 기본 개념을 흐트러뜨리는 쪽으로 영향을 주지는 않는다고 생각합니다.
지금 TDD 때문에 기존에 갖고있던 생각들이 깨지는것은 새로운 개념을 익히는 과정의 일환으로 생각하셔도 좋겠네요~
앞으로 다른 미션들까지 진행하시면더 더 인사이트를 얻으실 꺼에요

2
이견이 있을수 있는데요,
저는 개인적으로 private 는 테스트 하지 않는 것으로 생각하고 있습니다.
public 메소드의 테스트 안에 private 테스트가 포함 된것으로 생각하려고 하구요
그럼에도 불구하고 private 를 꼭 반드시 테스트 하고 싶을때는 reflection 으로 테스트 합니다.
테스트 하고싶어서 private 을 public 으로 바꾸는 일은 하지 않아요 (저는)

3
어려운 질문이네요 ㅎㅎㅎ
Car 를 직접 넘기면 정보를 너무 다 넘기는거 같고, getter 를 피할수 없겠죠
출력할 문자열을 넘기려면 Car 가 output 에 대한 책임을 갖게 되고
출력할 문자열을 만들기위한 재료를 넘기려면 getter 를 피할수 없겠네요 (또는 DTO 를 만들수도 있겠어요)
저라면 Car 를 넘기는걸 하겠네요. 근데 정답이라고 자신있게 말할수 없겠어요 ㅎㅎ

stack overflow 에도 의견이 있네요
https://stackoverflow.com/questions/21136227/passing-whole-object-vs-passing-objects-property
이걸 시작으로 이것저것 찾아보셔서 한번 여러가지로 시도 해 보세요~

2021-01-06 01:40 UTC, humbledude commented on build.gradle
> +    implementation 'junit:junit:4.12'
이거는 왜 정의되었을까요?
테스트용 프레임워크는 테스트시에만 컴파일 되는게 좋습니다

2021-01-06 01:40 UTC, humbledude commented on src/test/java/RacingGameTest.java
> +        assertThat(game.getWinner().equals(Arrays.asList(c2, c3))).isTrue();
assertJ 에서 list 관련 함수를 찾아서 써보세요~
코드가 더 직관적일 수 있어요
`contains` 로 시작하는것들입니다.

https://www.baeldung.com/introduction-to-assertj
https://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html

2021-01-06 01:40 UTC, humbledude commented on src/main/java/RacingGame.java
> +        System.out.println(String.join(", ", winnersName) + "가 최종 우승했습니다.");
위에 stream 을 쓰셔서 stream 을 쓰실줄 아는것으로 생각했을떄,
stream 써서 더 간결한 코드를 만들수 있어요

힌트 : 맨 마지막에 이걸 쓰게 됩니다 : `Collectors.joining(", ")`

2021-01-06 01:40 UTC, humbledude commented on src/main/java/RacingGame.java
> +    private static boolean isValidNames(String[] names) {
자동차 이름의 유효성 검사가 여기로 이사왔군요
물론 한번에 어레이에 있는 값을 다 체크해도 되지만,
유효성 검사의 제일 중요 목적은 이름 한개에 대한 검사라고 생각 됩니다.

여기서는 이름중에 어느 하나가 문제가 발생했을때, 통으로 검사 실패를 얻게 되는데,
그러면 이름 중에 뭐가 문제였는지 알수가 없겠어요

2021-01-06 01:40 UTC, humbledude commented on src/main/java/RacingGame.java
> +        return nameList.stream()
어레이도 바로 stream 으로 만들수 있어요 ㅎㅎ
다음엔 `Arrays.stream` 한번 체크해 보세요~

2021-01-06 01:40 UTC, humbledude commented on src/main/java/RacingGame.java
> +    private final int FINAL_ROUND;
자바측 컨벤션에 의하면,
대문자로 변수명을 지정할때는 static final 일 경우에요~
컨벤션 한번 확인해 보세요~

2021-01-06 01:40 UTC, humbledude commented on src/test/java/domain/CarTest.java
> +        assertThat(car.getPosition(), is(0));
Junit + hamcrest 가 익숙하신가 보군요 👍 
이번 강의에서는 assertJ 를 유도하고 있긴한데요~
이참에 한번 써보시고 익숙한것과 비교해봐도 좋을꺼 같아요

2021-01-06 01:40 UTC, humbledude commented on src/main/java/domain/Car.java
> +//    public final static Comparator<Car> comparotr = new Comparator<Car>() {
커밋에 의미없는 주석문은 포함되지 않게 신경써주세요~

2021-01-06 01:40 UTC, humbledude commented on src/main/java/view/InputView.java
> +                    throw new PostiveIntegerException();
이번 미션에서는 indent 를 1단만 유지하도록 가이드 하고 있어요
이게 생각해보면 루프 안에서 if 하나를 못쓰게 하는 규칙이고요,
try catch 를 매우 작은 범위로 좁히는 등의 제약이 걸립니다.

전체적으로 indent 를 줄이기 위해 메소드를 작게 만들어 보세요~

2021-01-06 01:40 UTC, humbledude commented on src/main/java/view/InputView.java
> +    public LengthOfNameException() { super("이름은 최대 5자 이내로 작성하세요."); }
예외 정의 👍 
파일이 많아져도 괜찮으니, 각기 다른 파일에 정의하셔도 되겠어요~

2021-01-06 01:40 UTC, humbledude commented on src/main/java/view/InputView.java
> +    private InputView() {}
static 전용 클래스라 기본 생성자 막기 👍

2021-01-06 01:40 UTC, humbledude commented on src/main/java/view/InputView.java
> +        return (names != null) && (names.length >= RacingGame.MIN_NUM_NAMES);
이부분 코드 작성시에 잘 동작안했을꺼 같은데요~
리팩토링하느라 다른 파일을 싹 지우셔서~ ㅎㅎ
각 커밋은 동작하는 상태의 코드를 커밋하는게 좋겠습니다

2021-01-06 01:40 UTC, humbledude commented on src/main/java/view/ResultView.java
> +        return String.join("", Collections.nCopies(n, str));
오 저도 오늘 처음보는거네요 `nCopies` 👍 
종종 써먹을데가 있겠어요~

2021-01-06 01:40 UTC, humbledude commented on src/main/java/domain/RacingGame.java
> +                .orElse(0);
max 의 결과가 optional 에서 empty 로 나오는 경우를 체크 해보셨나요?
orElse(0) 으로 설정해도 뭐 딱히 에러는 없겠지만 그 의미가 모호한거 같아요~

2021-01-06 01:40 UTC, humbledude commented on src/main/java/Main.java
> +    public static void main(String[] args) throws Exception {
메인이 RaceGame 밖에 있어서 더 좋은거 같네요~ 👍 
application 의 전반적인 흐름이 나타나네요

2021-01-06 01:40 UTC, humbledude commented on src/main/java/domain/RacingGame.java
> +        return rand.nextInt(MAX_RAND_NUMBER - MIN_RAND_NUMBER + 1) + MIN_RAND_NUMBER;
이거 max - min + 1 +min 계산하면 max + 1 나오네요 ㅎㅎㅎ

2021-01-07 04:03 UTC, syeol-kim commented on build.gradle
> +    implementation 'junit:junit:4.12'
* 테스트 어노테이션 임포트에서 실수가 있었습니다.  
`org.junit.Test`에서 `org.junit.jupiter.api.Test`로 변경했습니다.

  > **org.junit.Test** : @Test tells JUnit that the public void method to which it is attached can be run as a test case.  
  **org.junit.jupiter.api.Test** : @Test is used to signal that the annotated method is a test method.  
* 참고: [JUnit 4 vs Jupiter](https://sormuras.github.io/blog/2018-09-13-junit-4-core-vs-jupiter-api.html)

2021-01-07 04:03 UTC, syeol-kim commented on src/test/java/RacingGameTest.java
> +        assertThat(game.getWinner().equals(Arrays.asList(c2, c3))).isTrue();
* `assertThat(game.getWinners()).contains("crong", "honux")` = winners에 crong과 honux가 포함된다.
`assertThat(game.getWinners()).isEqualTo(Arrays.asList("crong", "honux"))` = winners는 crong과 honux이다.
* 저는 이 상황에 isEqualTo가 더 어울린다고 판단했습니다.  
하지만 다음 미션을 진행하면서 페어가 equals 오버라이딩에 contains를 사용했고, 저는 이상함을 느끼지 못했습니다.  
contains가 두 객체의 일치함을 보장할 수 있을까요?

2021-01-07 04:04 UTC, syeol-kim commented on src/main/java/RacingGame.java
> +    private static boolean isValidNames(String[] names) {
* 여태까지 유효성 검사의 목적을 단순히 '유효성 보장'에 두었는데, 유효하지 않은 값을 특정할 수 있어야 한다는 생각을 못했네요.  
좋은 피드백 감사합니다 😊
* 유효성 검사는 하나하나씩 실시하기! 📝

2021-01-07 04:07 UTC, syeol-kim commented on src/main/java/RacingGame.java
> +    private final int FINAL_ROUND;
* [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)에서 상수일 경우에만 대문자 변수명을 지정하는 것을 다시 한번 확인했습니다.  
컨벤션에 좀 더 주의하겠습니다 📝

2021-01-07 04:08 UTC, syeol-kim commented on src/test/java/domain/CarTest.java
> +        assertThat(car.getPosition(), is(0));
* [1번 피드백](https://github.com/next-step/java-racingcar-kakao/pull/36#discussion_r552271977)을 반영하면서 JUnit + hamcrest를 assertJ로 변경했습니다:D
* `assertThat((number >= RacingGame.MIN_RAND_NUMBER && number <= RacingGame.MAX_RAND_NUMBER), is(true))`
`assertThat(number).isBetween(RacingGame.MIN_RAND_NUMBER, RacingGame.MAX_RAND_NUMBER)`
* isBetween가 가독성이 더 좋은거 같아요 👍

2021-01-07 04:09 UTC, syeol-kim commented on src/main/java/domain/Car.java
> +//    public final static Comparator<Car> comparotr = new Comparator<Car>() {
커밋과 관계없는 주석문은 포함하지 않도록 주의하겠습니다 📝

2021-01-07 04:09 UTC, syeol-kim commented on src/main/java/view/InputView.java
> +                    throw new PostiveIntegerException();
indent depth가 증가하는 부분은 함수화시켰습니다.

2021-01-07 04:10 UTC, syeol-kim commented on src/main/java/view/InputView.java
> +    public LengthOfNameException() { super("이름은 최대 5자 이내로 작성하세요."); }
예외 클래스를 각 파일로 분리했습니다 👍

2021-01-07 04:11 UTC, syeol-kim commented on src/main/java/view/InputView.java
> +        return (names != null) && (names.length >= RacingGame.MIN_NUM_NAMES);
저는 오류 케이스를 찾지 못했습니다. 어떤 경우에 문제가 될까요? 🤔

2021-01-07 04:12 UTC, syeol-kim commented on src/main/java/domain/RacingGame.java
> +                .orElse(0);
* maxPosition 계산
  * orElseThrow  

    ```java
      int maxPosition = cars.stream()
          .map(Car::getPosition)
          .max(Integer::compare)
          .orElseThrow(NoSuchElementException::new);
    ```
  
  * Collections.max
  
    ```java
    List<Integer> positions = cars.stream()
        .map(Car::getPosition)
        .collect(Collectors.toList());

    int maxPosition = Collections.max(positions);
    ```
  
  * 위와 같은 두 가지 대안을 생각했습니다.  
  이전에 사용한 orElse(0) 보다는 orElseThrow가 좀 더 유의미하지않을까 생각합니다.  
  하지만 **모호성을 제거**하는 것이 목표라면 Collections.max가 좀 더 적절하다고 생각합니다.  

* cars is empty?
  * RacingGame이 갖는 cars의 유효성을 보장하고자 생성자를 아래와 같이 수정했습니다.  
  (InputView에서 체크후 값을 넘겨받지만 의존성을 낮춰야하지 않을까 생각했습니다.)

    ```java
      public RacingGame(List<Car> cars, int finalRound) {
        validateCars(cars);
        this.cars = Collections.unmodifiableList(cars);
        ...
    }
    ```

  * 또한 Collections.unmodifiableList를 적용해 **불변 객체**로 만들었습니다.

2021-01-07 04:12 UTC, syeol-kim commented on src/main/java/domain/RacingGame.java
> +        return rand.nextInt(MAX_RAND_NUMBER - MIN_RAND_NUMBER + 1) + MIN_RAND_NUMBER;
* MAX_RAND_NUMBER와 MIN_RAND_NUMBER가 **같은 경우**,  
rand.nextInt(1) + MIN_RAND_NUMBER = **MIN_RAND_NUMBER**를 반환합니다.
* **MIN_RAND_NUMBER=10**, **MAX_RANDOM_NUMBER=99**일 때,  
rand.nextInt(90) + 10 = **10~99**사이의 값을 반환합니다.

2021-01-07 05:23 UTC, humbledude commented on src/test/java/RacingGameTest.java
> +        assertThat(game.getWinner().equals(Arrays.asList(c2, c3))).isTrue();
contains 는 순서에 대한 내용이 제외 되어 있어요~
그리고 contains(어쩌구) 에 넣지 않는 것까지 있을때도 pass 하게 되죠
딱히 list 내부의 순서까지 중요하지 않은 경우에 간단하게 쓸수 있겠어요
반드시 이거여야 해~ 라고 까다롭지 않을때 판단하에 쓰시면 되겠습니다 ㅎㅎ

2021-01-07 05:27 UTC, humbledude commented on src/main/java/view/InputView.java
> +        return (names != null) && (names.length >= RacingGame.MIN_NUM_NAMES);
아 제가 커밋을 위에서부터 하나씩 따라오다보니 그렇게 생각하게 되었어요 ㅎㅎ
중간에 파일을 싹 날리는 커밋이 하나 있었고요, 그다음에 순차적으로 구현이 되고 있었는데요
그 시점에서는 RacingGame 파일이 없었을꺼에요~

커밋을 아마 다 구현한다음에, 파일마다 하나씩 하신거 같아서 말씀 드렸습니다 ㅎㅎ

2021-01-07 05:30 UTC, humbledude commented on src/main/java/domain/RacingGame.java
> +        return rand.nextInt(MAX_RAND_NUMBER - MIN_RAND_NUMBER + 1) + MIN_RAND_NUMBER;
아 네 제가 좀 혼미했네요 ㅎㅎㅎㅎ
의도하신대로 동작하겠네요~

2021-01-07 05:53 UTC, humbledude approved these changes
수고 많으셨습니다~!
코멘트 드린 부분은 별거 아닌내용만 있어서 머지합니다~
다음 미션도 즐겁게~ ㅎㅎㅎ

2021-01-07 05:53 UTC, humbledude commented on src/test/java/view/InputViewTest.java
> +        assertThatThrownBy(() -> InputView.parseNames(text))
assertJ 로 해보셨군요 ㅎㅎ 👍 
이것저것 많이 써보시고 한번 비교해 보세요~

2021-01-07 05:53 UTC, humbledude commented on src/main/java/commons/LengthOfNameException.java
> +}
요거 줄 끝에 newline 이 없다는 에러 표시에요~

저도 별거 아니라고 생각하고 무시하곤 했는데
다 이유가 있더라고요 ㅎㅎ
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

요 블로그 안에 웹스톰 설정이라고 나와있는데 intellij 도 똑같아요~
오늘 셋팅하면 맥북 바꿀때까지 문제없어요 ㅎㅎㅎ

2021-01-07 05:54 UTC, merged

2021-01-08 02:06 UTC, syeol-kim commented on src/main/java/commons/LengthOfNameException.java
> +}
셋팅 완료 했습니다~!! 👌