dino.bin racingcar 2단계 PR입니다.
NewKrew2021/java-racingcar-kakao pull request #39
Opened 2021-01-06 01:32 UTC by kommadot

## 요약
- MVC패턴 방식으로 각 클래스들의 역할을 분리하여 클래스를 분할하였습니다.
- 일급 컬렉션 기법을 이용해서 car들을 관리하는 클래스를 추가하였습니다.
- Circuit은 단순 View의 역할입니다.
- Main에서 컨트롤러를 생성하는 구조입니다.

## 질문
- Main에서 컨트롤러를 생성하는 구조로 가는게 맞나요? 컨트롤러에 메인을 구현해야하나요?
- 일급 컬렉션에 비즈니스 로직이 들어가면 안될거같아서 cars라는 컬렉션에서 list를 반환하는 get method를 구현하였는데 적절한 방식일까요?
- method 명은 동사로 하는편이 좋다고 하는데 명사나 동사가 아닌 경우로 짓는 상황도 있나요?
- 제 MVC패턴 구조가 잘 이루어져 있나요?

2021-01-06 16:29 UTC, htrucci requested changes
안녕하세요!
MVC패턴을 기반으로 구조를 잘 나눠주신 것 같아요! 👏
일급컬렉션, 래핑 클래스를 적재적소에 사용한 부분도 아주 인상적이었습니다. 👍  
질문해주신 내용에 대한 답변을 포함하여 몇가지 리뷰를 남겨드렸으니 
확인 부탁드리고 추가 수정할 부분이 있어 Request changes로 남겨두겠습니다.

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/Main.java
> +        racingGameController.run();
Q. Main에서 컨트롤러를 생성하는 구조로 가는게 맞나요? 컨트롤러에 메인을 구현해야하나요?
A. java 프로그램이 실행될 때 가장 먼저 진입하는 진입점이 Main 이라는 점을 생각하면, Main 함수 내부에 내가 호출할 로직이 오는 것이 적절하다고 생각합니다. 혹시나 나중에 다른 종류의 Controller 가 추가되어도 더 확장성 있기도 하구요!
일례로 서버프로그래밍을 하다보면 자주 보게되는 스프링 프레임워크 중 스프링부트라는 프레임워크의 진입점이 main()함수 인걸 보면 main함수에서 컨트롤러를 생성해주는 구조가 맞다고 생각됩니다.

[스프링부트란??](https://kimyhcj.tistory.com/373)

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/view/Circuit.java
> +    }
출력을 담당하는 클래스네요! 
의도하신 네임이라면 Circuit에서 하는 방송? 이란 의미로 사용할 수는 있곘지만 ㅎㅎ
큰틀에서 View를 담당하고 있으므로 View성격이 명확한 이름으로 변경해보는건 어떨까요?
입력시 출력되는 부분과 결과를 출력하는 부분으로 나눈다면 더 좋을 것 같네요! 😄

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Car.java
> +    public Car(String name) {
리뷰 반영 👍 
지난 리뷰에서 컨벤션만 말씀을 드렸는데 사실 개인 취향이기도 한 부분이어서
Intellij에 reformatCode 기능이 있으니 자신의 스타일을 셋팅해놓고 해당 기능을 사용하면 더 좋을 것 같아요! 
하지만 코드스타일을 개인에 맞춰 커스터마이즈하면 한 코드를 다른 사람이 작업할때마다 불필요한 수정이 일어나니 이점도 유의해야합니다.

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/controller/RacingGameController.java
> +    }
어플리케이션 전반적인 실행이 담긴 함수이네요.
이렇게 해도 괜찮지만, Main함수에서 각기 실행하는 방법도 있을 것 같아요~!
Circuit은 출력을 담당하는 클래스로 보이는데, run함수가 실행될때마다 매번 실행하기 보다 한번만 만들어두면 좋겠죠?
`private final Circuit circuit = new Circuit();`

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/controller/RacingGameController.java
> +    private int rapTime;
rapTime은 RacingGame의 구성 요소가 아닐까요? 👀

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Position.java
> +        this(0);
생성자 재사용성 높인 코드 좋아요 👍 

1단계 요구사항의 실행결과를 보면 5번 시도했으나 6번의 결과가 출력된 걸 볼 수 있어요.
레이스가 시작하지 않았을때 시작점이 1이라는 부분일 것 같아요. 😄

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Position.java
> +        }
요구사항에 자세히 나와있지는 않지만 한바퀴 이상은 설정되어야 레이스가 진행되지 않을까요?

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Cars.java
> +    }
getter사용은 객체의 캡슐화를 위해 지양해야하므로, 😢 
getter를 사용하는 대신에 객체에 메시지를 보내면 어떨까요?
hint. car.equalsPosition(maxPosition)

2021-01-06 16:29 UTC, htrucci commented on src/test/java/racingcar/domain/CarTest.java
> +    }
리뷰반영 👍 👍

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Cars.java
> +    }
와~ add과정이 있어 일부러 LinkedList를 사용하신거죠?? 💯 

레이스가 진행되는동안 car리스트에 변동이 없을 것 같으니 
생성자는 아래와 같이 Stream으로 바로 초기화 할 수도 있을 것 같네요~!
splitName(namesText).stream().map(Car::new).collect(Collectors.toList());

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/controller/RacingGameController.java
> +        circuit.printRaceStatus(racingGame.getRaceStatus());
요구사항에 우승자 출력후 경기 결과를 한번 더 출력하라는 얘기는 없었지만,,
결과 보여주면 좋은거니 요건 넘어가도록 하겠습니다 ㅎ

2021-01-06 16:29 UTC, htrucci commented on src/test/java/racingcar/domain/RacingGameTest.java
> +
rapTime에 대한 검증이 없어 -1로도 실행이 되는 것 같아요.
검증코드를 추가해볼까요?

2021-01-06 16:29 UTC, htrucci commented on src/test/java/racingcar/domain/PositionTest.java
> +    }
래핑클래스에 대해 equals hashcode 재정의하고 테스트코드까지 짜주시는! 좋은 습관입니다 👍 💯

2021-01-06 16:29 UTC, htrucci commented on src/test/java/racingcar/domain/NameTest.java
> +    }
보통 서적 및 교육에서는 TDD(테스트주도개발) 을 할때에는 요구사항에 대한 모든 경우에 대해 테스트코드를 작성하는것을 요청합니다. 그렇게 된다면 테스트코드(모든 테스트 항목 포함)를 기반으로 개발한 소스 리펙토링 시 안정성을 보장할 수 있다고 한 부분입니다(기존기능). 그리고, 신규 기능이 생길경우 기존 만든 테스트 케이스의 모든 항목들의 성공 및 추가요청사항에 따른 테스트코드를 작성하는 것을 권장합니다. 
이전에는 티디디 방법론에 대해 우위적이였으나, 여러 개발 방법론 등이 나오면서 테스트주도개발에 대해 많은 의견들이 논의되고 있습니다. 하지만 테스트 코드가 주는 장점을 생각하면 위 내용을 고려하여 적당히 조절하는 것이 좋겠죠?

이러한 개인적 의견에 덧붙여 아래 글을 한번 봐주시면 좋을 것 같아요.
https://velog.io/@ybg7955/Clean-Code-9%EC%9E%A5-%EB%8B%A8%EC%9C%84-%ED%85%8C%EC%8A%A4%ED%8A%B8

TDD 사이클을 잘 준수했다면 아래와 같이 테스트 코드가 분리되어서 나왔겠죠? 👀 

`assertThatExceptionOfType(IllegalArgumentException.class)
        .isThrownBy(() -> {new Name("dinobin");
        }).withMessageMatching("이름은 5자를 넘기면 안됩니다.");

assertThatExceptionOfType(IllegalArgumentException.class)
        .isThrownBy(() -> {new Name("");
        }).withMessageMatching("이름을 입력해 주세요");`

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Cars.java
> +    }
제 생각이 맞는지 고민이 좀 되는 부분이긴한데 저도 생각을 다시 해봐야하겠지만
car변동이 없다보니 addCar로 cars를 추가하게 되면 List<Cars>가 바뀌어 Cars로 캡슐화한 의미가 퇴색되지 않을까요?

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/domain/Name.java
> +            throw new IllegalArgumentException("이름은 5자를 넘기면 안됩니다.");
메시지도 상수화를 하면 좋을 것 같아요!

2021-01-06 16:29 UTC, htrucci commented on src/main/java/racingcar/view/Circuit.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
메시지도 상수화를 하면 좋을 것 같아요!

2021-01-06 16:29 UTC, htrucci commented on src/test/java/racingcar/domain/RacingGameTest.java
> +
Q. Main에서 컨트롤러를 생성하는 구조로 가는게 맞나요? 컨트롤러에 메인을 구현해야하나요?
 - java 프로그램이 실행될 때 가장 먼저 진입하는 진입점이 Main 이라는 점을 생각하면, Main 함수 내부에 내가 호출할 로직이 오는 것이 적절하다고 생각합니다. 혹시나 나중에 다른 종류의 Controller 가 추가되어도 더 확장성 있기도 하구요!
일례로 서버프로그래밍을 하다보면 자주 보게되는 스프링 프레임워크 중 스프링부트라는 프레임워크의 진입점이 main()함수 인걸 보면 main함수에서 컨트롤러를 생성해주는 구조가 맞다고 생각됩니다.

Q. 일급 컬렉션에 비즈니스 로직이 들어가면 안될거같아서 cars라는 컬렉션에서 list를 반환하는 get method를 구현하였는데 적절한 방식일까요?
 - 일급 컬렉션은 컬렉션 객체를 보호하려는 목적도 있기 때문에, 컬렉션 자체를 외부에 반환해주면 일급 컬렉션을 쓰는 의미가 퇴색되지 않을까요? 컬렉션과 관련된 비지니스 로직이라면 일급컬렉션 내에 있는게 맞고, 소스에서와 같이 단순히 출력을 위해 컬렉션이 필요한거라면 일급 컬렉션 내부에서 컬렉션 내용을 출력해주는 메소드를 생성하면 되지 않을까 합니다. 

Q. method 명은 동사로 하는편이 좋다고 하는데 명사나 동사가 아닌 경우로 짓는 상황도 있나요?
- 캡슐화된 객체에서 상태는 변수, 행위는 메소드가 표현해줍니다. 메소드명을 동사로 표현해야 '행위' 라는 메소드의 본질을 가장 직관적으로 나타낼 수 있기 때문에 동사로 표현하는게 일반적입니다. 
Collection 인터페이스를 사용하는 경우 외부에서 getter메서드로 얻은 값을 통해 상태값을 변경할 수 있기 때문에 

public List<Car> getCars() {
		return cars;
	} (x)

public List<Car> getCars() {
		return Collections.unmodifiableList(cars);
	} (o)

외부에서 변경하지 못하게 생각해보면 좋을 것 같아요.


Q. 제 MVC패턴 구조가 잘 이루어져 있나요?
 - 넵! 그런데 Controller 에서 view 를 run 메소드 내에서 circuit = new Circuit(); 이렇게 초기화하는데, 이부분은 따로 초기화 메소드(예를들면 void initCircuit())를 만들어 분리해주거나 컨트롤러 생성자에 넣는게 더 가독성이 좋아질것같아요~ 
 - controller는 전달의 역할만 하면 되기때문에 Controller에 있는 rapTime 변수도 옮기는 게 더 좋을 것 같습니다!

Q. 출력 View에선 Name등을 알아야하는데, 만약 컨트롤러의 반환값이 일급 컬렉션이나 원시타입 래퍼클래스라면 정보 접근을 어떤식으로 해야 하나요?
 - 일급 컬렉션이라면 일급 컬렉션 내부에 Name 을 리턴해주는 메소드를 만들면 되고,  래퍼클래스라면 원시타입/참조타입 모두 name 정해주고 사용할수 있어 보입니다. 원시타입은 null을 담을수 없는 것을 유의해주세요.

2021-01-07 02:26 UTC, kommadot commented on src/main/java/racingcar/controller/RacingGameController.java
> +    private int rapTime;
그럼 레이싱 결과를 반복적으로 출력해야하는데, RacingGame에서 UI적인 코드가 들어가도 되나요?

2021-01-07 02:27 UTC, kommadot commented on src/main/java/racingcar/domain/Position.java
> +        this(0);
요구사항에 있는 실행결과 보니까 5회라고 입력했지만 6회 출력이 되어있길래 최종 출력이 있나 해서 그렇게 했습니다! 혹시 제가 잘못 이해한걸까요?

2021-01-08 01:29 UTC, htrucci approved these changes
안녕하세요, 데빈입니다.
피드백 모두 잘 반영해주셨네요 💯  
자동차경주 미션은 이정도에서 머지하도록 하겠습니다.
첫 미션 진행하시느라 고생 많으셨어요~ 
로또 미션도 화이팅입니다~!

2021-01-08 01:29 UTC, htrucci commented on src/main/java/racingcar/Main.java
> +        racingGameController.end();
💯

2021-01-08 01:29 UTC, htrucci commented on src/main/java/racingcar/controller/RacingGameController.java
>          }
더 명확한 표현인 것 같아서 보기 좋네요 👍

2021-01-08 01:29 UTC, htrucci commented on src/main/java/racingcar/domain/Cars.java
> +                .filter(car -> car.equalsPosition(maxPosition))
리뷰반영 👍

2021-01-08 01:29 UTC, htrucci commented on src/main/java/racingcar/domain/Cars.java
> +        return Collections.unmodifiableList(cars);
리뷰반영 👍

2021-01-08 01:30 UTC, merged