[eli.nabro 오영민] 자동차 경주 게임 구현 코드리뷰 요청 PR 입니다.
NewKrew2021/java-racingcar-kakao pull request #4
Opened 2021-01-05 03:42 UTC by maireneu

자동차 경주게임 구현 코드리뷰 요청 PR입니다.

2021-01-05 05:56 UTC, javajigi commented on src/main/java/racing/RacingGameLogic.java
> +    public void setCars(String s) {
set 메소드보다 생성자를 통해 초기화하는 것은 어떨까?

2021-01-05 05:56 UTC, javajigi commented on src/main/java/racing/RacingGameLogic.java
> +    public void setCars(String s) {
변수명 s 뭐임??

2021-01-05 09:09 UTC, maireneu commented on src/main/java/racing/RacingGameLogic.java
> +    public void setCars(String s) {
해당 부분은 실은 생성자로 구현했다가, 테스트의 용이성을 위해서 변경했던 부분인데요.. 생성자로 다시 바꾸고, 테스트코드에서도 작동하도록 변경하였습니다! 훨씬 더 깔끔해졌네요.

2021-01-05 09:10 UTC, maireneu commented on src/main/java/racing/RacingGameLogic.java
> +    public void setCars(String s) {
앗 리팩토링중 누락이 있었네요 ㅠㅠ 해당 부분을 포함하여 타 변수명, 메소드명을 직관적으로 수정 하였습니다.

2021-01-05 12:14 UTC, findstar requested changes
안녕하세요, 자동차 경주 리뷰를 하게 된 제임스입니다.
기능 구현 잘해주셨습니다만, 랜덤 값에 따른 자동차의 이동과 진행 횟수에 대한 버그가 있습니다.
코멘트를 남겼으니 확인 부탁드립니다. 
추가적으로 테스트는 클래스 단위로 구분해주시면 좋겠습니다. 
궁금한 점은 언제든지 편하게 질문 주세요 :)

2021-01-05 12:14 UTC, findstar commented on src/main/java/racing/RacingGameUI.java
> +public class RacingGameUI {
UI 안에 Game 이 들어 있네요, 
Input / Output 을 구분하고, UI 와 Game 을 분리해보면 어떨까요?

2021-01-05 12:14 UTC, findstar commented on src/test/java/racing/RacingGameTest.java
> +public class RacingGameTest {
테스트는 각각의 클래스에 맞게 분리해서 진행해주세요.

2021-01-05 12:14 UTC, findstar commented on src/main/java/racing/Car.java
> +    public void move(boolean isMoved) {
move 에 true / false 를 전달할 필요가 있을까요?

2021-01-05 12:14 UTC, findstar commented on src/main/java/racing/RacingGameUI.java
> +        while (this.racingGame.checkPosition(numbers)) {
random 값은 모두 3 이하가 나올 수도 있습니다. 
이 경우 시도횟수가 더 많아 집니다. 
(매 시도 횟수마다 무조건 1 대 이상의 자동차가 전진하지 않을 수도 있습니다.)

2021-01-05 12:14 UTC, findstar commented on src/main/java/racing/RacingGameLogic.java
> +        List<Integer> result = new ArrayList<>();
stream 을 사용하면
```java
return cars.stream()
                .map(Car::getPosition)
                .collect(Collectors.toList());
``` 
와 같이 표현할 수도 있습니다.

2021-01-06 01:58 UTC, maireneu commented on src/main/java/racing/RacingGameUI.java
> +public class RacingGameUI {
말씀하신대로 RacingGameUI를 RacingGame, RacingInputUI, RacingOutputUI로 각각 분리하였습니다. 훨씬 깔끔해졌네요!

2021-01-06 01:58 UTC, maireneu commented on src/test/java/racing/RacingGameTest.java
> +public class RacingGameTest {
테스트 Class를 각각 class별로 나누고, 각 class의 public method에 대한 테스트를 추가하였습니다.

2021-01-06 02:00 UTC, maireneu commented on src/main/java/racing/Car.java
> +    public void move(boolean isMoved) {
해당부분은 randomValue가 stop_value(3) 을 넘었는지 확인하기위해 넣은 부분이었는데요, 아래 언급하신 버그를 수정하면서 move에서 해당 부분을 판별하지 않도록 수정하였습니다.

말씀하신 것처럼 move에서 해당 부분을 빼버리는게 단일 책임원칙에 더 부합하는거 같네요!

2021-01-06 02:02 UTC, maireneu commented on src/main/java/racing/RacingGameUI.java
> +        while (this.racingGame.checkPosition(numbers)) {
Random 값을 class로 분리하고, 매 시행마다  최소한 하나의 값이 stop_value 이상이도록 수정하였습니다.

2021-01-06 02:03 UTC, maireneu commented on src/main/java/racing/RacingGameLogic.java
> +        List<Integer> result = new ArrayList<>();
해당부분을 stream을 사용하도록 고쳤습니다. java 가 처음인데, stream을 더 공부해서 빠르게 익숙해지도록 해보겠습니다. 감사합니다!

2021-01-06 02:54 UTC, findstar approved these changes
코멘트 드린 부분에 대해서 잘 반영해주셨네요. :) 
이 PR 은 merge 하겠습니다. 
과제 수행이 쉽지는 않은데 계속 해보시면 
더 나은 코드를 작성하는 방법이 익숙해질 거라고 생각합니다. 
몇가지 코멘트를 추가했습니다만 꼭 반영해야 하는 건 아니구요. 
한번 더 생각해보시면 좋겠습니다. 화이팅입니다! 💯

2021-01-06 02:54 UTC, findstar commented on src/test/java/racing/RacingGameLogicTest.java
> +    void racingConstructorTest() {
Parameterized Test 를 활용하면 개선할 수 있습니다. 나중에 활용해보세요 😄 
https://gmlwjd9405.github.io/2019/11/27/junit5-guide-parameterized-test.html

2021-01-06 02:54 UTC, findstar commented on src/main/java/racing/RacingGame.java
> +    public void run() {
피드백 드린대로 분리해주셨는데요. 코드 가독성을 좀 더 개선되면 좋겠습니다.
Game 에서 Logic 과 UI 를 분리 잘 해주셨는데요, 
사실 이 과제의 규모를 생각하면 Main 에서 역할을 수행해도 충분합니다 😄 

그리고 OutpuUI 에서 자동차 이름을 위한 입력해달라는 메세지를 출력하고 있는데요.
이부분은 사실 InputUI 에서 처리하는게 더 나아보이네요. 

입력만 담당하는게 아니라, 입력 화면 자체를 표현한다고 보시면 될것 같아요.

2021-01-06 02:54 UTC, findstar commented on src/main/java/racing/RacingGameLogic.java
> +    private static final int RANDOM_DIGIT = 10000;
RANDOM_DIGIT 는 사용되는 곳이 없습니다.

2021-01-06 02:54 UTC, findstar commented on src/main/java/racing/RandomValue.java
> +            randomValues.add((int) (Math.random() * RANDOM_DIGIT % 10));
```java
Random random = new Random();
random.nextInt(10); 
```
과 같은 방법이 더 읽기 편한 방법입니다 😄

2021-01-06 02:54 UTC, merged

2021-01-06 15:50 UTC, maireneu commented on src/main/java/racing/RacingGame.java
> +    public void run() {
피드백 감사합니다! main과 RacingGame을 합치고, OutputUI의 일부를 InputUI로 이동하였습니다. 객체의 행위 자체보다 역할에 치중해서 코딩하도록 할게요.

2021-01-06 15:51 UTC, maireneu commented on src/main/java/racing/RandomValue.java
> +            randomValues.add((int) (Math.random() * RANDOM_DIGIT % 10));
해당 부분을 Random 객체 사용으로 수정하였습니다. 피드백 감사합니다!

2021-01-06 15:52 UTC, maireneu commented on src/main/java/racing/RacingGameLogic.java
> +    private static final int RANDOM_DIGIT = 10000;
클래스 정리 중 빠뜨린 부분이 있었네요ㅠ 피드백 감사합니다!

2021-01-06 16:21 UTC, maireneu commented on src/test/java/racing/RacingGameLogicTest.java
> +    void racingConstructorTest() {
감사합니다. 해당 구문을 활용하여 Testing 클래스를 수정하였습니다.