[Danial 유기백] 코드리뷰 요청 드립니다
NewKrew2021/java-racingcar-kakao pull request #41
Opened 2021-01-06 07:33 UTC by Yookibaek

2021-01-06 08:51 UTC, humbledude requested changes
안녕하세요~ 리뷰를 맡은 조슈아 입니다.

전반적으로 컨벤션 지적을 하게 되었는데요, 이게 참 별거 아닌거 같은데 눈에 잘띄는게 저도 희안하네요~
컨벤션은 전체적으로 한번 훑어보시고 습관을 들여보시는게 좋겠습니다.
현업에서 컨벤션 맞추는데 시간 쏟기는 좀 그렇거든요~

이외에도 개선할 만한 부분 코멘트 드렸습니다.
참고하셔서 동의하시는 부분은 개선해서 다시 요청해 주세요~

2021-01-06 08:51 UTC, humbledude commented on src/main/java/Car.java
> +            throw new IllegalArgumentException();
코드 컨벤션 한번 확인 해 보세요~
중괄호 생략은 문법적으로 가능하지만 권장되지 않습니다.

https://myeonguni.tistory.com/1596

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/MoveStrategy.java
> +public interface MoveStrategy {
strategy 를 따로 뺀것이 훌륭하네요 👍 
함수 하나짜리 클래스라면 @FunctionalInterface 로 지정해도 좋을꺼 같아요

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/Cars.java
> +    List<Car> cars;
일급콜렉션 👍 
어디서 좀 배우셨군요~!

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/Cars.java
> +                .filter((car)->car.getPosition() == maxPosition)
람다에서 보통 arrow 양쪽은 띄어쓰기가 들어갑니다.
마땅한 코딩 컨벤션 정의가 잘 없긴한데, google style 에 정의 되어있긴 하네요~
(지금 우리가 쓰는 컨벤션 정의가 따로 있는건 아니죠?)
요거 참고 하셔요
https://google.github.io/styleguide/javaguide.html

2021-01-06 08:51 UTC, humbledude commented on src/main/java/domain/Car.java
> +    public int compareTo(Car o) {
comparable 구현을 통해서 제일 앞선 차를 구하는 군요 👍

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/InputManager.java
> +    public String getFromUser(String comment, UserInputValidator validator){
유저 입력을 받기위한 일반적인 로직 구현 👍

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/InputManager.java
> +            return getFromUser(comment, validator);
validation 을 통과하지 못하면 다시 시도하게 하는군요
통과 할때까지 stack 이 계속 깊어지는 구조인데요,
물론 세상에 stack overflow 가 날때까지 입력에 실패하는 경우는 없겠지만 개선 해봐도 좋을꺼 같습니다.
그리고 exception 이 발생했으니 사유 정도는 알려줘도 될꺼 같구요~

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +                    new Car(namesArray[i]);
객체 생성없이 validation 이 동작하는게 좋지 않을까요?

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +    public void play(){
메쏘드 간 공백라인 추가 하는 컨벤션이 있습니다~
한번 컨벤션 확인해 보세요

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +                "경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).",
문자열은 상수로 따로 관리해도 좋을꺼 같습니다

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +            cars.moveAll(new RandomBasedMoveStrategy());
메소드 이름이 print 인데 사실 move 가 여기서 이루어지고 있네요
메소드가 한가지 일을 담당할수 있는게 좋겠어요
그리고 RandomBasedMoveStragegy 가 매번 생성될 필요는 없을꺼 같군요~

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +        for (int i=0; i < heads.size()-1; i++) {
각연산자 사이에 공백 문자를 넣는것이 컨벤션 입니다.
자잘한 컨벤션 지적을 하게 되고 있는데, 한번 정리해 보시는게 좋겠어요~

2021-01-06 08:51 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +        countInputValidator = new UserInputValidator() {
이부분은 따로 파일을 빼서 작성하면 RacingGame 클래스가 단순화 되겠습니다

2021-01-07 08:45 UTC, Yookibaek commented on src/main/java/Car.java
> +            throw new IllegalArgumentException();
네!

2021-01-07 09:00 UTC, Yookibaek commented on src/main/java/racinggame/MoveStrategy.java
> +public interface MoveStrategy {
덕분에 @FunctionalInterface 의미가 어떤 것인지 알게 되었습니다..
람다형으로 사용할 목적으로 정의한 인터페이스이니, @FunctionalInterface 선언해주는 것이 맞겠네요. 감사합니다!

2021-01-07 09:03 UTC, Yookibaek commented on src/main/java/racinggame/Cars.java
> +                .filter((car)->car.getPosition() == maxPosition)
감사합니다!

2021-01-07 09:04 UTC, Yookibaek commented on src/main/java/racinggame/Cars.java
> +    List<Car> cars;
포비에게 배웠습니다. 항상 감사합니다..!

2021-01-07 09:10 UTC, Yookibaek commented on src/main/java/racinggame/RacingGame.java
> +                "경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).",
질문이 있습니다.

상수로 따로 빼는 경우의 기준이 궁금합니다.
여기저기서 사용하는 문자열이 아니라, 한번만 사용하는 문자열인데도 상수로 따로 빼야 하나요???

2021-01-07 09:10 UTC, Yookibaek commented on src/main/java/racinggame/RacingGame.java
> +    public void play(){
넵!

2021-01-07 09:11 UTC, Yookibaek commented on src/main/java/racinggame/RacingGame.java
> +        for (int i=0; i < heads.size()-1; i++) {
넵 알겠습니다!

2021-01-07 09:58 UTC, Yookibaek commented on src/main/java/racinggame/RacingGame.java
> +            cars.moveAll(new RandomBasedMoveStrategy());
printRacingGame함수의 이름을 moveCars로 변경 하였습니다.
그리고 내부 로직에서 자동차를 이동시키는 로직 이외는 모두 분리하였습니다(전략객체로 받아서 함수를 실행하도록 했습니다)
혹시 이렇게 변경하는게 적절해 보이시는 지 궁금합니다.

2021-01-07 10:12 UTC, Yookibaek commented on src/main/java/racinggame/RacingGame.java
> +        countInputValidator = new UserInputValidator() {
네

2021-01-08 01:22 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +                "경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).",
일단 가이드는 그렇습니다 ㅎㅎ
한번만 써도 일단 상수로 빼보는게 좋습니다.
한번 해보시고 장단점을 비교해보는것이 좋겠어요~

2021-01-08 01:23 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +            cars.moveAll(new RandomBasedMoveStrategy());
네 저기 밑에 수정내용으로 한번 볼께요~

2021-01-08 01:35 UTC, humbledude approved these changes
고생 많으셨습니다~
기존 코드가 잘 작성되어있어서 큰 변경 없이도 깔끔하게 잘 봤습니다
다음 미션도 즐겁게 잘 하시길 바래요~

2021-01-08 01:35 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +            cars.moveAll(RandomBasedMoveStrategy.getInstance());
싱글톤 좋네요 👍

2021-01-08 01:35 UTC, humbledude commented on src/main/java/racinggame/RacingGame.java
> +    public void moveCars(Cars cars, int tryCount, Consumer<Cars> afterMove) {
오 콜백 함수 👍 
혹시 안드로이드 해보셨나요 ㅎㅎㅎ 안드로이드에서는 콜백 많이 쓰던데 ㅎㅎ
콜백이 혹시 null 일수 있으니, null 체크 정도 하시면 될꺼 같구요.

2021-01-08 01:35 UTC, merged