[yell.ow] 자동차 경주게임 2단계 코드 리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #42
Opened 2021-01-06 07:39 UTC by idealgu

idealgu(yell, 이상규) Step2 MVC 패턴을 적용한 자동차 경주 리팩토링입니다.

UI 처리를 담당하는 RacingGameView, 입력된 정보를 바탕으로 RacingGame을 조작하는 RacingGameController, 도메인으로 RacingGame, Car, CarInfo 등으로 구성하여 리팩토링하였습니다.

앞선 Step1의 피드백을 반영하며 리팩토링하면서 RacingGame의 역할을 많이 줄이려고 했습니다.

## 질문사항
* 지금과 같은 구조로 역할을 나누었을 때 MVC 패턴을 적절하게 적용했다고 할 수 있을까요?
* RacingGameView에서 Car 객체를 사용하지 못하게 하고, 출력에 필요한 정보만 사용하게끔 하기 위해 별도로 CarInfo 클래스를 분리하였습니다. getInfo에서 매번 new를 통해 getInfo를 전달해 주는 방식보다 더 효율적인 방식이 있을지 궁금합니다.

2021-01-06 11:54 UTC, sehan requested changes
안녕하세요. 니오입니다. : )

리팩토링 후 클래스의 역할분리와 패키지 분리까지 아주 좋아졌습니다. 💯 
너무 좋지만 몇가지 개선하면 좋을거 같아서 Request changes 드립니다. 

[개선요청] 으로 남긴 코멘트는 반드시 개선해 주세요.
[도전] 으로 남긴 코멘트는 필수는 아닙니다. 고민해 주시고 여력이 있다면 도전 해보세요 👍

화이팅 👍👍👍

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/controller/RacingGameController.java
> +        }
[도전] RacingGame 의 시작과 종료가 RacingGame 도메인에서 처리되면 어떨까? 하는 생각을 해봅니다.

RacingGame 도메인을 사용하여 RacingGameApplication 을 작성하려고 Controller.startRacingGame() 매소드를 구현하려고 할때 RacingGame 을 어떻게 사용해야 할지 확인해야 합니다.
RacingGame 은 경기에 참여할 자동차들과 경기횟수를 필요로 하고 경기횟수 만큼 racing() 이 진행되면 경기는 종료 ( isEnd() ) 된다라고 도메인의 역할과 책임을 명세해주면 

controller code 작성시 아래와 같이 도메인객체에게 메세지를 주고 받으며 코드를 전개해 나갈 수 있습니다.
```
game = RacingGame( 참여할 자동자들, 경기횟수 )
loop ( !game.isEnd ){
    game.racing()
}
```

이러한 이유로 게임의 종료여부도 RacingGame 에게 물어보고 그에 따라 제어코드를 작성해 보는건 어떨까요? 
현재는 startRacingGame() 매소드에 RacingGame 에 대한 종료로직이 구현되어 있습니다.

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Car.java
> +    private Position position;
원시타입도 포장하셨군요 👍

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Car.java
> +        return new CarInfo(name.getName(), position.getPosition());
name, position 을 외부에 전달하기 위한 DTO 생성 좋습니다. 👍 

> 질문. RacingGameView에서 Car 객체를 사용하지 못하게 하고, 출력에 필요한 정보만 사용하게끔 하기 위해 별도로 CarInfo 클래스를 분리하였습니다. getInfo에서 매번 new를 통해 getInfo를 전달해 주는 방식보다 더 효율적인 방식이 있을지 궁금합니다.

위 질문에 대한 답을 하자면,  CarInfo 와 같이 Data 전송을 위한 객체를 생성하는 비용은 아주 작습니다. 그리고 position 의 값은 늘 변경의 여지가 있는 값이어서 cache 를 적용할 수 없지만 CarInfo 가 불변의 값들 만 가지고 있다면 객체를 cache 해서 늘 동일한 객체를 return 하는 방법을 사용할 수 있겠습니다. 그러기 위해서는 CarInfo 를 생성하는 역할을 분리해서 CarInfoFactory 로 만들고 CarInfo 의 생성책임을 Factory 에게 넘겨줄 수 있습니다.

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/CarInfo.java
> +    private final Name name;
[개선요청] 원시값을 포장한 Name, Position 을 name.getName() , position.getPosition() 용도로만 사용하고 있어서 DTO 에서는 원시값을 그대로 사용하는것이 좋겠습니다. 

private final int position;
private final String name;

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Cars.java
> +            carNameInvalidException.printErrorMessage(name);
[개선요청] 도메인객체에서 exception 이 발생하게 되면 catch 해서 처리하지 않고 throws 하는것이 좋습니다.
exception 의 제어권을 도메인을 사용하는 호출자 에게 주기 위함입니다.
도메인 내부에서 exception 을 처리하게 되면 호출자는 오류를 확인할 방법이 없고 제어도 할 수 없기 때문입니다.

그래서 exception 의 최종처리는 제어로직을 작성하는 쪽에서 처리하는 것이 좋습니다.

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Cars.java
> +    public List<CarInfo> getStatus() {
[개선요청] CarInfo 를 return 하고 있으니 getCarInfos 라고 네이밍을 하는 것이 어떨까요? 
getStatus() 라고 하면 Status 객체 하나가 return 될거 같습니다.

또는 List<CarInfo> 를 포장해서 Status 객체를 만들어 사용해도 괜찮을거 같네요 😊

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Winners.java
> +
[도전] 우승자찾기 로직을 분리하셨네요 👍 

조금더 좋은 코드가 되려면 winners 라는 이름보다는 WinnerFinder.find( List<Car> ) 행태로 매소드를 변경 해보는건 어떨까요?
우승자를 찾아서 우승자 이름목록을 return 하는 역할만 하기 때문에 cars 상태를 클래스에 유지 할 필요가 없습니다.
method scope 에서만 cars 를 사용할 수 있도록 find(List<Car>) 형태로 받는것이 좋겠습니다.

확장성을 높이기위해 더 개선해 본다면 우승자 찾기조건이 새로 추가되어 RacingGame 마다 우승자조건이 달라지더라도 Cars 코드변경 없이 변경된 우승자 찾기조건을 교체할 수 있는 구조를 만들수 있다면 더 좋을거 같습니다. ☺️

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Name.java
> +        if(StringUtils.isNameOverMaxLength(name, NAME_MAX_LENGTH)) {
[개선요청] StringUtils 에 isNameOverMaxLength() 매소드는 로직이 포함되어 StringUtils 에 추가되기에는 접합하지 않습니다.
StringUtils 에는 String 에 기인한 매소드들만 추가되는것이 좋습니다. 
도메인 로직을 포함하는 매소드들을 하나둘 추가하다 보면 StringUtils 에 각 도메인로직이 포함된 수많은 유틸성 매소드들이 추가될 위험이 있습니다.

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Position.java
> +    public void nextStep(int currentSpeed) {
[도전] nextStep() 매소드를 호출하면 position 이 nextStep 으로 갈거라고 예상이 됩니다.
nextStep 이 position 을 증가시키는 역할과 증가시킬지 아닐지 여부를 판단하는 역할 두가지를 하고 있기 때문에 매소드명과 파라미터(currentSpeed) 만으로는 매소드의 역할을 알아내기가 어렵습니다.

isCarGo() 매소드는 외부로 제공하는 매소드가 아니기 때문에 private 으로 변경해주세요
테스트 작성을 위해 public 으로 선언했다면 해당 로직을 클래스로 분리하는 방향을 고민해야 합니다.

자동차 이동조건이 변경된다면 Position 코드를 변경해야 해서 확장성이 떨어 집니다. Position 에서 자동차 이동조건을 분리해 낸다면 Position 은 자동차 이동조건에 의존하지 않게 될 수 있습니다.

strategy pattern , 객체지향원칙 OCP 를 키워드로 관련내용을 참고하시기 바랍니다. 😊

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/exceptions/InvalidCarNameException.java
> +    }
[개선요청] exception 을 catch 하여 system.out 으로 출력하고자 한다면 Logger 를 사용하는 것이 좋습니다.
system.out 으로 출력하는 매소드는 제거 해주세요.
exception 을 catch 한 코드에서 Logger 를 이용해서 출력하기 바랍니다.

사용예입니다. https://examples.javacodegeeks.com/enterprise-java/slf4j/slf4j-tutorial-beginners/

2021-01-06 11:54 UTC, sehan commented on src/test/java/racingcar/domain/CarTest.java
> +    @ParameterizedTest
@DisplayName 을 사용해서 단위테스트 목적을 적어주시면 좋습니다. 

nextStepTest() 의 경우@DisplayName("4이상이면 자동차는 이동해야 한다")  와 같이 작성할 수 있습니다.
테스트 작성시 기능명세를 작성하듯이 적으면 도메인객체의 역할도 명확히 할 수 있고 테스트코드를 읽으면 도메인객체를 사용하는 방법과 역할을 쉽게 이해할 수 있게 도와줍니다 ☺️

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
[개선요청] Cars 테스트 코드가 없습니다. 
Cars 생성에 대한 테스트 코드만 추가 하면 되겠네요 ☺️

2021-01-06 11:54 UTC, sehan commented on src/main/java/racingcar/exceptions/InvalidCarNameException.java
> +package racingcar.exceptions;
[개선요청] 도메인에서 사용되는 custom exception 들은 도메인 패키지로 이동시키는 것이 좋습니다.

현재는 racingcar.domain -> racingcar.exceptions 패키지 의존을 가지고 있습니다. racingcar.exceptions 패키지는 항상 domain 패키지랑 함께 사용되기 때문에 domain 패키지 쪽으로 exception 들을 이동하는게 좋습니다.

2021-01-06 11:54 UTC, sehan commented on src/test/java/racingcar/domain/NameTest.java
> +    void blankTextTest() {
[도전] @ParameterizedTest , @NullAndEmptySource 를 사용해서 코드를 간결하게 개선 해보기 바랍니다. 😊

2021-01-06 11:57 UTC, sehan commented
> ## 질문사항
> * 지금과 같은 구조로 역할을 나누었을 때 MVC 패턴을 적절하게 적용했다고 할 수 있을까요?

네, layer 별로 역할에 맞게 잘 구분해 주셨습니다. 💯 💯 💯 


> * RacingGameView에서 Car 객체를 사용하지 못하게 하고, 출력에 필요한 정보만 사용하게끔 하기 위해 별도로 CarInfo 클래스를 분리하였습니다. getInfo에서 매번 new를 통해 getInfo를 전달해 주는 방식보다 더 효율적인 방식이 있을지 궁금합니다.

코드에 질문에 대한 답을 남겨드렸습니다. ☺️

2021-01-07 02:53 UTC, sehan requested changes
요청드린 부분을 아주 잘 반영해주셨습니다. 💯 💯 💯 

잘못 사용되고 있는 코드들이 몇가지 보여서 추가 수정요청드립니다. 
추가로 남긴 코멘트 확인 후 수정해주세요 😊

끝이 보입니다. 👍

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/controller/RacingGameController.java
> +            logger.error(runtimeException.toString());
exception 의 message 를 로깅하고 싶을때는 getMessage() 를 사용하면 됩니다. 
```suggestion
            logger.error(runtimeException.getMessage());
```

stacktrace 까지 로깅하고 싶다면 아래와 같이 사용하면 됩니다 
```
    logger.error(e.getMessage(), e )
```

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/domain/Car.java
> +    public void move(MovingStrategy movingStrategy) {
👍 👍 👍

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/domain/InvalidCarNameException.java
> +        this.message = message;
[개선요청] RuntimeException 에 이미 message 를 인자로 가지는 생성자를 가지고 있어서  이런경우 아래와 같이 작성하면 됩니다.
```suggestion
      super(message);
```

private final String message; 와 toString() 은 제거 해주세요

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/domain/InvalidGameCountException.java
> +public class InvalidGameCountException extends RuntimeException {
[개선요청] InvalidCarNameException 과 동일한 의견입니다. 같이 수정해주세요

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/domain/InvalidPositionException.java
> +public class InvalidPositionException extends RuntimeException {
[개선요청] InvalidCarNameException 과 동일한 의견입니다. 같이 수정해주세요

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/domain/MovingStrategy.java
> +public interface MovingStrategy {
👍 👍 👍 👍 👍

2021-01-07 02:53 UTC, sehan commented on src/main/java/racingcar/domain/RandomMovingStrategy.java
> +public class RandomMovingStrategy implements MovingStrategy{
👍 👍 👍 👍

2021-01-07 04:46 UTC, idealgu commented
좋은 리뷰 정말 감사드립니다!!
많이 고민하면서 코드 작성해보는 시간이 되어서 도움이 정말 많이되었습니다! 👍👍👍👍

2021-01-07 06:25 UTC, sehan approved these changes
개선사항 잘 반영해 주셨습니다. 👍 👍 👍 
2단계 PR merge 하겠습니다.
이후 로또 미션도 화이팅 입니다. : )

2021-01-07 06:25 UTC, merged