[yuni.code] 자동차 경주 게임 2단계 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #43
Opened 2021-01-06 08:13 UTC by dsyun96

## 리팩토링 결과

- 의도가 불명확한 go와 run 중 go를 지웠습니다.
    - run의 경우 runWithContion으로 이름을 바꿨습니다.
- Car 클래스의 position, name getter는 그대로 남겨두었습니다.
- Car 클래스의 현재 상태를 출력하는 print 메서드 대신 toString을 오버라이딩하였습니다.
- MyRandom 클래스는
    - nextInt 메서드를 static으로 변경하였습니다.
    - Random() 인스턴스도 static으로 가지고 있도록 하였습니다.
    - CustomRandom으로 이름을 변경했습니다.
- RacingGame 클래스의 winner 관련은 Cars 일급컬렉션으로 분리를 하였습니다.
- 자동차 이름 검증 메서드는 Car 클래스에 넣었습니다.
- winner를 효과적으로 테스트하기 위해 Car 클래스에 위치 정보도 인자로 받는 생성자를 추가하였습니다.

2021-01-06 12:57 UTC, sehan requested changes
안녕하세요. 니오입니다 :)

step1 에서 요청드렸던 내용은 아주 잘 반영해주셨습니다. 💯 💯 

하지만, step2 요구사항에 대한 반영은 다소 아쉽습니다.
step2 에서는 MVC 패턴 기반 리팩토링이 핵심입니다. 

* 핵심 비지니스 로직을 가지는 객체를 domain 패키지, UI 관련한 객체를 view 패키지에 구현한다.
* MVC 패턴 기반으로 리팩토링해 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다.

위 두가지 요구사항에 집중해서 좀 더 리팩토링을 진행했으면 합니다.
[개선요청] 으로 남긴 코멘트는 반드시 개선을 해야하는 내용입니다.

그럼 더 분발해 주세요 👍

2021-01-06 12:57 UTC, sehan commented on src/main/java/Car.java
> +        if (isBlank(name) || name.length() > 5)
[개선요청] Car 생성검증 부분 테스트 코드가 작성되지 않았습니다.  테스트 추가 해주세요 😊

2021-01-06 12:57 UTC, sehan commented on src/main/java/Car.java
> +    public String toString() {
[개선사항] MVC 구조를 위해 View 와 관련된 로직은 도메인에서 분리해야 합니다.

toString() 의 return 문자열이 "name : ------ " 형태로 만들어 지는부분이 View 로직에 의존적인 부분입니다.
View 로직을 변경하려고 할때 domain 객체를 수정해야 하는 의존이 발생하기 때문에 Car 객체에서 View 의존적인 로직을 제거 해야 합니다.

2021-01-06 12:57 UTC, sehan commented on src/main/java/Cars.java
> +    private final List<Car> cars;
일급컬렉션으로 RacingGame 의 역할을 잘 분리해주셨네요 👍

2021-01-06 12:57 UTC, sehan commented on src/main/java/Cars.java
> +    public Cars getWinners() {
[개선요청] getWinners() 의 return 결과는 winners 가 되는 것을 기대합니다. Cars 가 car 목록의 상태를 가지는 객체라고 해서 상황에 따라 경기에 참여한 자동차들을 담기도 하고 상황에 따라 우승한 자동차들을 담는 객체가 되어서는 안됩니다.  Winner 객체를 새로 만들거나 우승자 이름 List 를 돌려주는 것이 좋습니다.

Cars 의 매소들은 경기에 참여한 자동차들을 play() 시키거나 그중에서 우승자를 찾는(getWinners()) 역할을 수행합니다. 하지만 , Cars 가 우승한 자동차들의 상태를 가질수도 있다면 getWinners() 라는 매소드는 상황에 따라 그 역할을 제대로 수행하지 못하게 됩니다.

2021-01-06 12:57 UTC, sehan commented on src/main/java/Cars.java
> +    public String toString() {
[개선요청] 우승자를 출력하기 위해 Cars.toString() 을 작성한것으로 보입니다.  MVC 구조를 위해 View 와 관련된 로직은 도메인에서 분리해야 합니다.

2021-01-06 12:57 UTC, sehan commented on src/main/java/RacingGame.java
>      private static final int MAX_LENGTH = 5;
[개선요청] Car 이름검증하는 객체로 옮겨주세요

2021-01-06 12:57 UTC, sehan commented on src/main/java/RacingGame.java
>      private final int FINAL_ROUND;
[개선요청] 상수(static final) 일때 만 대문자를 사용합니다. camelCase 로 표기해주세요

2021-01-06 12:57 UTC, sehan commented on src/main/java/RacingGame.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).");
[개선요청] 사용자 입력을 받고 화면에 출력하는 부분은 View 의 역할입니다. 
MVC 구조를 위해 View 로직을 분리해주세요

2021-01-06 12:57 UTC, sehan commented on src/main/java/RacingGame.java
>              cars.add(new Car(carName));
[개선요청] 입력받은 carNames 로 Cars 를 생성하는 로직을 RacingGame 으로 이동시키면 main() 매소드의 길이를 줄일 수 있습니다. RacingGame(int roundNo, String carNames) 생성자를 추가하면 해당 로직의 단위테스트도 작성할 수 있습니다.

2021-01-08 00:52 UTC, dsyun96 commented
1차 PR에서 코멘트 해주신 부분을 고치는 데 신경 쓰느라 MVC 패턴을 적용하는 것을 깜빡 잊고 있었습니다... ㅜㅜ
이번에 MVC 패턴을 적용하고 개선요청 하신 부분을 리팩토링하면서 생긴 궁금한 점을 아래와 같이 정리했습니다.

## 궁금한 점
- main에서 InputView를 통해 자동차를 입력받는데, InputView에서 바로 Cars로 반환하는 것과 일단 String으로 반환하고 RacingGame에서 Cars로 반환하는 것 중 어느 방법이 적절할까요?
- 도메인 객체에서의 toString을 지우고 View에서 처리하려면 getter를 만들어 처리하는 방법밖에 없나요?

2021-01-08 02:57 UTC, sehan commented
> 1차 PR에서 코멘트 해주신 부분을 고치는 데 신경 쓰느라 MVC 패턴을 적용하는 것을 깜빡 잊고 있었습니다... ㅜㅜ
> 이번에 MVC 패턴을 적용하고 개선요청 하신 부분을 리팩토링하면서 생긴 궁금한 점을 아래와 같이 정리했습니다.
> 
> ## 궁금한 점
> * main에서 InputView를 통해 자동차를 입력받는데, InputView에서 바로 Cars로 반환하는 것과 일단 String으로 반환하고 RacingGame에서 Cars로 반환하는 것 중 어느 방법이 적절할까요?

먼저 domain 측면에서만 바라보면 RacingGame(String carNames) 와 RacingGame(Cars cars) 두가지 생성자를 가지고 있다고 한다면 inputView 에서 string -> Cars 로 변환하는 로직없이 RacingGame 을 생성할 수 있어서 RacingGame 생성시 사용성이 좋아 집니다.
 domain 로직은 A개발자가 개발하고, domain 을 사용하여 application 개발은 B개발자가 진행하기로 했다면 B개발자 입장에서는 Cars 라는 도메일을 모르더라도 RacingGame 을 생성할 수 있게 되어 사용성이 더 좋다고 할 수 있습니다.
 물론, 이것이 RacingGame(Cars cars) 생성자가 필요없다는 의미는 아닙니다. 둘 중 어느것이 우선되어야 한다면 RacingGame(String carNames) 가 더 우선적으로 제공되는것이 더 좋다는 의미 입니다.

> * 도메인 객체에서의 toString을 지우고 View에서 처리하려면 getter를 만들어 처리하는 방법밖에 없나요?
domain 과 view 의 의존성을 제거하기 위해 domain -> view 로 전달할 객체( DTO ) 를 사이에 두어 DTO 에 getter 를 통해 view 에 필요로 하는 속성들을 제공하는 방법이 있습니다. 이렇게 하게 되면 domain 과 view 의 의존이 제거 되고 domain 에서는 외부로 제공할 목적에 맞는 DTO 를 제공 하는것으로 책임을 다 했다고 볼 수 있습니다.

2021-01-08 03:13 UTC, sehan requested changes
MVC 구조로 리팩토링 한 후 코드가 한결 좋아졌습니다. 👍 👍 👍 👍 👍 

리팩토링 하면 더 좋을거 같은 내용을 추가로 코멘트 남겼습니다. 😊
조금만 더 가봅시다~ 힘내세요. 아주 잘 하고 있습니다.

2021-01-08 03:13 UTC, sehan commented on src/main/java/RacingGame.java
> +    private Cars mapCars(String carNames) {
carNames 로 Cars 를 생성하는 factory method 역할을 하고 있습니다. 이 부분은 Cars 의 생성자로 새로 추가하거나 정적팩토리 매소드로 추가하면 Cars 로 이동시킬 수 있습니다. 😊

2021-01-08 03:13 UTC, sehan commented on src/main/java/RacingGame.java
> +    public static void main(String[] args) {
RacingGame 은 도메인 객체 입니다. 그리고 main() 에 구현된 코드는 MVC 구조에서 C ( controller ) 에 해당한다고 볼 수 있습니다. 
main() 매소드만 남기고 RacingGame 을 domain 패키지 쪽으로 이동하고 하는것이 좋겠습니다.

2021-01-08 03:13 UTC, sehan commented on src/test/java/RacingGameTest.java
> +    void createCars() {
CarsTest 로 이동하는것이 좋겠습니다.  앞서 코멘트 했던것 처럼 Cars 에 carNames 를 인자로 받는 생성자를 추가하면 Cars 를 생성하는 테스트를 작성하기 용이해집니다.

2021-01-08 03:13 UTC, sehan commented on src/test/java/domain/CarTest.java
> +    @Test
Junit5 에 @ParameterizedTest 를 살펴보고 코드를 개선해보세요 😊

2021-01-08 05:20 UTC, dsyun96 commented on src/main/java/RacingGame.java
> +    private Cars mapCars(String carNames) {
Cars의 생성자로 추가하겠습니다!

2021-01-08 05:46 UTC, dsyun96 commented on src/test/java/domain/CarTest.java
> +    @Test
이걸 잊고 있었네요...
근데 @ParameterizedTest를 적용하니 null을 한번에 테스트할 수는 없더라구요.
일단 nullName()으로 따로 테스트를 작성하긴 했는데, 이게 최선일까요?

2021-01-08 05:51 UTC, sehan commented on src/test/java/domain/CarTest.java
> +    @Test
@NullAndEmptySource 를 사용해서 null 과 empty 상황을 테스트로 작성할 수 있습니다.
null 을 한번에 테스트 하지는 못합니다.

단위테스트를 작성할때는 assert 구문을 단위테스트 안에 많이 넣는것 보다는 단위테스트를 분리해서 작성하는 것이 좋습니다.
위 상황 같은 경우 자동차 명이 5자를 넘어서는 경우,  Null 또는 Blank 가 입력되는 경우로 2개의 단위테스트를 작성하면 적절합니다.

2021-01-08 05:56 UTC, sehan requested changes
피드백 드린 부분 잘 반영해 주셨습니다. 💯 💯 💯 

단계를 진행하면서 그리고 리뷰를 주고 받으면서 개선되는 모습이 확연히 보입니다. 👍 👍 👍 
자동차 경주게임 미션 마무리 하도록 하겠습니다. 고생하셨습니다.

로또 미션도 더욱 힘내서 화이팅 하세요~~~ 😊

2021-01-08 05:59 UTC, sehan commented on src/test/java/domain/CarsTest.java
> +                ));
이 부분은 getCars 를 꺼내서 테스트 하기 보다는 Cars 에 equals(), hashcode() 를 구현 후 
assertThat(cars).isEquals(new Car("pobi,crong,honux") )  로 테스트를 하는것이 좋습니다.

객체의 동일한 상태로 생성이 되었을때 두 객체가 같은지를 비교해서 같다면 동일한 상태에서 각 매소드의 응답은 동일하기 때문입니다.

2021-01-08 05:59 UTC, merged

2021-01-08 06:03 UTC, dsyun96 commented on src/test/java/domain/CarsTest.java
> +                ));
넵 알겠습니다!