[jack.won] step 2 코드리뷰 요청 드립니다.
NewKrew2021/java-racingcar-kakao pull request #44
Opened 2021-01-06 09:39 UTC by cyrojyro

코드리뷰 주신 사항 반영하였습니다.
step2의 MVC로의 변경은 클래스들이 각각 MVC에 잘 들어맞는것으로 판단되어 패키지 구조 변경만 있었습니다. 

~~~
car.tryForward(-1)이나 car.tryForward(199) 같은 경우에 대한 내용도 포함되면 더 완벽할것 같아요!
~~~
위 사항은 랜덤 값이 잘못된 경우 tryForward에 잘못된 값이 들어가는 경우로 이해하고, 랜덤값 생성 테스트를 강화하였습니다.

2021-01-06 12:09 UTC, kriery requested changes
잭, 2번째 스탭도 잘 작성해 주셨습니다.
다음으로 넘어가기에 앞서 완성도를 높이는 취지에서 조금 더 코드를 다듬어 보면 좋을것 같아요.
아래 피드백 참고하시고 반영해보세요!

2021-01-06 12:09 UTC, kriery commented on src/test/java/calculator/utils/SplitterTest.java
>      }
네거티브 케이스 👍

2021-01-06 12:09 UTC, kriery commented on src/main/java/racingcar/controller/GameController.java
> +public class GameController {
다른 객체들에 비해서 `GameController`가 조금 뚱뚱한 느낌이죠?
다이어트가 필요할것 같아요.

2021-01-06 12:09 UTC, kriery commented on src/main/java/racingcar/controller/GameController.java
> +public class GameController {
전략을 세워 보죠, 공통점을 모아서 새로운 책임 그룹을 만들어 봅니다.
1. xxxGame으로 끝나는 메소드들
   - `Game` 진행을 담당하는 내용인것 같네요,
   - Output은 이들 메소드에서만 이용되고 있군요
2. xxxCars로 끝나는 메소드들
   - `자동차`를 만들고(Create), 가져오고(Read), 조작하는(Update) 기능을 담당하고 있네요
   - 인스턴스 필드: `cars`를 주도 다루고 있네요 
3. 인자로 `List<Car>`를 받는 메소드들
   - `cars`와 강하게 결합되어 있음을 알 수 있어요

2021-01-06 12:09 UTC, kriery commented on src/main/java/racingcar/controller/GameController.java
> +public class GameController {
크게 볼때 GameController는
`Game` 진행 vs `List<Car> cars`에 대한 조작 이라고 볼 수 있겠네요.
- 그렇다면 (설계상)`GameController`가 책임져야 할 대상은 `Game`에 가깝나요? `List<Car> cars`에 가깝나요?
- 만약 `List<Cars>`에 추가적인 메서드를 부여하기 위해서는 어떤 방법을 이용해야 할까요?

2021-01-07 01:23 UTC, cyrojyro commented on src/main/java/racingcar/controller/GameController.java
> +public class GameController {
List<Car> cars를 일급 콜렉션으로 분리해보도록 하겠습니다.

2021-01-07 11:44 UTC, kriery approved these changes
피드백 반영 잘 해 주셨어요. 머지하겠습니다.
미션은 마무리 하였지만 피드백은 꼭 읽어보시면 좋겠습니다.
그럼 언젠가 다음 과제에서 다시 만나요!

2021-01-07 11:44 UTC, kriery commented on src/main/java/racingcar/domain/Cars.java
> +    }
대게의 경우 일급 컬랙션은 외부에서의 불필요한 추가/삭제를 허용하지 않는 편이예요.
빈 객체의 생성, 내부변수를 노출하는 getter (꼭 필요하다면 불변객체를 생성해서 리턴해주는 방법도 있습니다) 등은 피하면 좋을것 같습니다.
여기서 `add`를 갑자기 없애면 `createCars`와 Controller의 `setGameCars`까지 흔들릴텐데요,
Controller에서도 굳이 `cars`를 `playGame`의 로컬 변수로 취급하거나,
굳이 멤버 필드로 가져갈 필요가 있으면, Controller의 생성자를 활용하는 방법도 있을거여요

2021-01-07 11:44 UTC, merged

2021-01-07 12:16 UTC, cyrojyro commented on src/main/java/racingcar/domain/Cars.java
> +    }
일급 콜렉션은 생성자로 immutable하게 생성한 후 외부로부터 메시지를 받아 프로퍼티를 수정하지 않는다는 말씀이시죠?
일급 콜렉션의 내부 프로퍼티가 외부에서 필요한 경우에는 레퍼런스가 아닌 카피된 불변객체를 반환하면 되나요?

2021-01-13 03:02 UTC, kriery commented on src/main/java/racingcar/domain/Cars.java
> +    }
질문을 놓치고 있었네요; 늦게 답변드려 죄송합니다 🙇 
결론부터 말씀드리면 yes 예요.
이건 일급 컬렉션이나 원시값 포장 객체 양쪽에 해당하는 내용인데요
내부 프로퍼티를 조작하는 것은 _꼭 필요한 경우가 아니면_ 피해야 할 부분이구요
의외로 내부 프로퍼티를 읽어가는 경우는 자주 생기는데, 이 때는 언급하신것 처럼 1)카피 객체를 반환하면 됩니다.
받아 쓰는 쪽에서 변경을 시도했을땐 어차피 카피 객체라 변경이 적용되지 않지만, 불변 객체를 제공하여 변경을 불허한다고 명시적으로 알려 주는 것이 좋습니다