[turner.lee] 자동차 경주 step2 리뷰 부탁드립니다.
NewKrew2021/java-racingcar-kakao pull request #46
Opened 2021-01-06 11:12 UTC by sumniy

# 요약
피드백 주신 내용 반영하고 리팩토링 했습니다.
View와 Cars 객체간의 분리를 위해서 중간에 데이터를 전달하기 위한 객체를 만들거나,
좀 더 각 객체에 맞는 책임을 가지도록 하려 했으나 하다보니 오히려 좀 복잡해진 것 같습니다...😥
# 질문
* View에 정보를 전달해주기위한 객체로 CarInfo, CarsInfo를 만들어서 사용했습니다. 그런데 이렇게 하다보니 경기 결과가 나올 때 마다 반복해서 변환을 해줘야합니다. 이처럼 반복되는 상황이라도 계속 변환을 해줘야 할까요?

2021-01-06 12:59 UTC, kriery reviewed
2단계도 무난히 진행 하셨네요.
큰 문제는 없지만 자잘하게 고쳐야 할 내용들을 남겨두었어요.
주로 일급 컬랙션에 이용에 대한 내용들이 될것 같습니다.
그럼 피드백 반영하고 다시 만나요 ⛵

2021-01-06 12:59 UTC, kriery commented on src/test/java/com/nextstep/racingcar/CarTest.java
> +    assertThatExceptionOfType(RuntimeException.class).
이왕 만들어둔 `InvalidNameFormatException`을 썼으면 더 좋았을텐데요
```suggestion
    assertThatExceptionOfType(InvalidNameFormatException.class).
```

2021-01-06 12:59 UTC, kriery commented on src/test/java/com/nextstep/racingcar/CarTest.java
> +            });
(두개뿐이지만) `ParameterizedTest`를 이용하면 간결하게 작성할 수 있습니다.

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
**race** 도중 "새로운 차량의 난입"을 막기 위해서 `Cars`는 생성 후에는,
더 이상 `Car` 추가나 `Car` 삭제가 되지 않도록 하면 어떨까요?

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/RacingApplication.java
> +    }
그러기 위해서는 먼저 빈 `Cars`를 만들어놓고 채우는 형태보다
`Cars`를 구성할 내용을 다준비해서 `new Cars`로 넘겨 주는 것이 좋겠습니다

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +    return farthestLocation == car.getLocation();
한줄 만으로 해결되는 조건이면 lambda식에 바로 넣어도 무방할것 같아요 😄

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/domain/CarsInfo.java
> +public class CarsInfo {
일급컬랙션 🥇

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/view/RacingResultView.java
> +    String winners = String.join(", ", getCarNames(carsInfo));
일급 컬랙션은 
- 데이터를 은닉하고 가공한 결과를 보여주기 위해
- 컬랙션에 추가적인 책임(기능)을 부여하기 위해

이용됩니다. 지금의 `CarsInfo`는 단지 컬랙션 `List<Car> cars` 를 담는 캐리어의 역할만 하고 있어요.
이왕 일급 컬랙션이 나왔으니, `getCarNames`는 `CarsInfo`로 위임해줘도 좋을것 같습니다.

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/RacingApplication.java
> +      carsInfo = convertToInfo(cars.getCars());
race -> getCars -> convert 의 변환을 거치기 보단
race가 `CarsInfo`를 반환하는 것이 더 자연스러워 보여요

2021-01-06 12:59 UTC, kriery commented on src/main/java/com/nextstep/racingcar/RacingApplication.java
> +    RacingResultView.printWinners(convertToInfo(cars.getWinners()));
여기서도, getWinner -> convert -> getCarNames 을 지나면서 결과데이터가 변형되고 있는데요.
한번뿐이 winner 출력인데 `List<Car>` -> `CarsInfo` -> `List<String>`
최종적으로 `List<String>`을 획득하기 위해 너무 큰 희생을 하고 있는것 같아요.
cars.getWinners() 가 `List<String>`을 바로 반환하는건 어떨까요?
(또는 별도 데이터 조작을 하고자 한다면 일급 컬랙션(`Winners`)도 괜찮아요)

2021-01-06 12:59 UTC, kriery commented on src/test/java/com/nextstep/racingcar/CarsTest.java
> +    assertThat(cars.getWinners()).isEqualTo(Arrays.asList("t"));
이대로라면 test 실패가 납니다 🧯

2021-01-06 13:01 UTC, kriery requested changes
^^

2021-01-06 16:33 UTC, sumniy commented
제가 꼼꼼하게 보지 못했던 부분들까지 리뷰해 주셔서 너무 감사합니다. 😭 
피드백 반영해서 다시 커밋했습니다. 다시 한번 리뷰 부탁드립니다!

2021-01-07 00:27 UTC, kriery approved these changes
늦은 시간까지 고민 많이 하셨네요. 제안을 하나 드렸습니다.
PR을 다시 하라는건 아니니까 천천히 고민해서 해답을 찾아보시면 좋을것 같아요.
이번 미션은 여기서 마무리 하도록 하겠습니다. 머지 할게요!

2021-01-07 00:27 UTC, kriery commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
- cars = new Cars("a,b,c,d")
- cars = new Cars(List.of(car1, car2, car3))

두가지로 사용하기 위함인거죠? 더욱 좋은 형태로는, 
- cars = Cars.valueOf("a,b,c,d")
- cars = Cars.of(List.of(car1, car2, car3))

가 있습니다 (네이밍은 적절히...).
이렇게 static factory methods를 이용하시면, 
1. 생성자에 의미있는 이름을 부여하기 좋고
1. 생성에 필요한 로직을 캡슐레이션 할 수 있고
1. 생성자에서 부르지 못하는 인스턴스 메소드를 호출할 수가 있습니다

see also:
[static factory methods](https://www.baeldung.com/java-constructors-vs-static-factory-methods)를 한번 읽어보시면 도움이 될것 같습니다

2021-01-07 00:27 UTC, kriery commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
여기서도 convert가 이용되고 있는데요 (convert가 항상 나쁜것은 아닙니다만)
개념적으로 볼때,
- `void car.move`: 차를 달리게 하고
- `map(car -> new CarInfo(car.getName(), car.getLocation()))`: 달린 차에서 이름/위치를 뽑아서 결과 데이터를 생성한다

라는 흐름보다는,

- `CarInfo car.move`: 차를 달리게 한 다음 결과를 받아온다
- collect: 결과를 모아서 CarsInfo를 만든다

라는 흐름이 조금 더 직관적일것 같아요.
이렇게 함으로 인해, car.getLocation() 의 getter를 이용하지 않는 방법이 있습니다.
(CarInfo는 단순 데이터 전달을 위한 DTO로 볼 수 있으니까요)

2021-01-07 00:27 UTC, kriery commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
그렇게 하면(`getLocation`을 없앤다면), winner를 받아오는 데 고민이 생길텐데요
winner 역시도 결과 데이터니까, cars 에서 가져오기보단 CarsInfo에서 가져오면 더 명확합니다.
나아가서는, CarsInfo에 winner를 받아오는 책임을 넘길 수도 있을거구요

2021-01-07 00:27 UTC, merged

2021-01-07 02:50 UTC, sumniy commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
예시로 보여주신 것처럼 어떤 값에 의해 생성되는 지 의미를 바로 알 수 있네요. 더 공부해보겠습니다. 감사합니다! 😀

2021-01-07 02:59 UTC, sumniy commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
와 덕분에 코드가 훨씬 깔끔해졌네요 감사합니다 !!

2021-01-07 03:05 UTC, sumniy commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  }
아하 Cars에서 Cars에 대한 행위들에 대한 메서드를 남겨두고, 
데이터를 얻는 메서드들을 CarsInfo로 분리해서 클래스의 역할과 책임을 명확하게 하는 느낌이네요.
감사합니다

2021-01-07 03:06 UTC, sumniy commented
리뷰받으면서 너무 많이 배우게 되었습니다. 정말 감사합니다!! 👍👍👍