[mark.lim 임상진] 자동차 경주 step2 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #49
Opened 2021-01-06 12:14 UTC by limdef

안녕하세요 마크입니다.
step1에서 피드백 주신 부분을 최대한 고려하여 보았습니다.

- MVC패턴의 main 메소드의 예시를 참고하며 리팩토링 하였습니다.
- 최대한 각 로직들이 그 로직을 담당하는 도메인에게 책임을 가지도록 하였습니다.
- 기존 코드에 Cars에 일급콜렉션을 적용해보았는데, 많은 부분을 리팩토링하게 되었습니다.

2021-01-07 02:08 UTC, sehan requested changes
안녕하세요. 니오 입니다 😊

MVC 구조로 각 클래스들을 잘 분리해 주셨습니다. 💯 💯 💯 
아쉬운 부분이 몇가지 있어서 좀 더 리팩토링을 진행했으면 합니다.

[개선요청] 으로 남긴 코멘트는 꼭 개선해 주세요 ☺️
[도전] 으로 남긴 코멘트는 잘 고민해 보시기 바랍니다. 필수는 아닙니다.

화이팅~~~ 👍👍👍

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/domain/Car.java
> +        this(name);
[개선요청] name, location 파라미터를 모두 가지는 Car(name, location) 생성자가 있다면 구현코드를 작성 후 간소화된 생성자 Car(name) 에서 location 의 기본값을 지정해 주는 방식으로 생성자를 작성하는 것이 좋습니다.

```
Car( name ){
   this(name, 0)
}

Car( name, location ){
  validate(name)
  this.name = name
  this.location = location
}
```

더 나아가 static factory 매소드를 활용해서 Car 를 생성해보는 건 어떨까요?

참고. [정적 팩토리 메서드는 왜 사용할까?](https://velog.io/@ljinsk3/정적-팩토리-메서드는-왜-사용할까)

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/domain/Cars.java
> +public class Cars {
일급컬랙션으로 RacingGame 의 역할이 잘 분리 되었네요 👍

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> getCars() {
[도전] getCars() 를 통해 꺼낸 List<Car> 에 새로운 car 를 추가하게되면 의도와는 다르게 RacingGame 에 참여하지 않은 차량이 느닷없이 추가될 수 있습니다. 이런 상황을 막으려면 어떻게 해야 할까요?

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> findWinners() {
[도전] 우승자를 찾아서 List<Car> 를 return 했습니다. Winner 객체를 만들어서 전달해보는건 어떨까요?

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/domain/RacingGame.java
> +    public Cars getCars(){
[도전] 자동차의 상태를 출력하기 위해 Cars 를 꺼내어 다시 Cars.getCars() 를 사용하고 있습니다. 
경기에 참여한 자동차들을 꺼내어 View 가 용도에 맞게 쓰고 있습니다.  객체의 역할을 명확하게 매소드의 역할을 명확하게 할 필요가 있습니다. 
RacingGame 에게 자동차 경주 상태를 출력하기위해 현재 경주상태를 알려달라고 메세지를 보내고 경주상태를 view 에 출력 해보는건 어떨까요?

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/util/StringUtil.java
> +        throw new AssertionError();
👍

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/view/InputView.java
> +        return new Cars(names);
[개선요청] Cars 는 RacingGame 도메인 내에서 사용되는 일급컬렉션으로 외부로 노출시키지 않도록 해봅시다.
외부로 노출이 필요한 경우면 모르겠지만 노출하지 않아도 된다면 사용자가 RacingGame 을 사용하기위해 알아야 하는 도메인객체를 줄여주는 것이 좋습니다. 

이런 관점에서 input 에서 받은 String 을 바로 사용하거나 split 해서 List <String> 을 사용하는 방식으로 개선해 보시기 바랍니다 ☺️

2021-01-07 02:08 UTC, sehan commented on src/main/java/racingcar/view/InputView.java
> +        if (tryNo <= 0) {
[개선요청] tryNo 원시값을 포장해보는건 어떨까요? 
검증로직을 도메인으로 이동시킬 수 있습니다.

2021-01-07 02:08 UTC, sehan commented on src/test/java/racingcar/CarTest.java
>  public class CarTest {
[개선요청] @DisplayName 을 사용하여 단위테스트의 목적을 명세 해보시기 바랍니다. 😊

저는 "~~ 해야한다" 또는 "~하면 ~한다" 와 같은 문체로 명세를 작성하는것을 추천드립니다.

예시입니다 
* 자동차 이름이 5자를 초과하면 IllegalArgumentException 을 던진다
* 자동차는 4이상의 매직넘버를 받아야 움직인다

2021-01-07 02:08 UTC, sehan commented on src/test/java/racingcar/CarTest.java
[개선요청] 테스트 클래스들의 패키지는 대상 클래스의 패키지와 동일한 위치에 있어야 합니다.  

CarTest 와 Car 의 패키지 위치가 상이 합니다. 다른 테스트 들도 패키지 위치를 변경해 주세요

2021-01-07 15:14 UTC, limdef commented
피드백 감사드립니다.

피드백을 참고하여 최대한 개선 해보았습니다.
RacingGame의 내부 정보들을 외부로 노출시키지 않도록 하였습니다
외부로 전달해야할 경우 CarInfo 를 활용하거나 Winner객체에서 String으로 전달하였습니다.

static factory 매소드를 활용해보라는 피드백을 받고
이번 레이싱 경주의 경우에는 생성자 이름을 여러개 가질 수 있는 장점을 활용해 보자는 것으로 이해하였는데
제대로 이해한 것이 맞을까요?

2021-01-08 02:40 UTC, sehan reviewed
> 피드백 감사드립니다.
> 
> 피드백을 참고하여 최대한 개선 해보았습니다.
> RacingGame의 내부 정보들을 외부로 노출시키지 않도록 하였습니다
> 외부로 전달해야할 경우 CarInfo 를 활용하거나 Winner객체에서 String으로 전달하였습니다.
> 
> static factory 매소드를 활용해보라는 피드백을 받고
> 이번 레이싱 경주의 경우에는 생성자 이름을 여러개 가질 수 있는 장점을 활용해 보자는 것으로 이해하였는데
> 제대로 이해한 것이 맞을까요?

네, 잘 이해 하신거 같네요 👍 .  생성자를 다양하게 제공하는것은 객체의 사용성이 좋아집니다. static factory 매소드를 사용하면 생성자의 의도를 매소드명으로 좀 더 명확하게 해 줘서 가독성 측면에서도 이점을 제공해줍니다.

2021-01-08 02:40 UTC, sehan commented on src/main/java/racingcar/domain/TryNo.java
> +    public TryNo(int tryNo) {
원시값을 잘 보장해 주셨네요 👍

2021-01-08 02:40 UTC, sehan commented on src/test/java/racingcar/domain/TryNoTest.java
> +        assertNotNull(new TryNo(1));
[참고] 상태값이 동일할 경우 동일한 객체다 라는 전제로 동일한 상태로 생성된 객체를 비교하는 것으로 테스트를 작성하는 것을 추천드립니다.
TryNo 에 equals(), hashCode() 매소드를 구현하고 아래와 같이 테스트 하면 됩니다. 😊
```
TryNo no = new TryNo(1);
assertThat(no).isEquals(new TryNo(1));
```

2021-01-08 02:42 UTC, sehan requested changes
피드백 잘 반영해 주셨습니다. 👍 

자동차 경주미션 step2 PR merge 하도록 하겠습니다. 고생하셨습니다. 😊

2021-01-08 02:42 UTC, merged