[echo.ohce 김환석] racing car 미션 step2 코드 리뷰 요청 드립니다.
NewKrew2021/java-racingcar-kakao pull request #53
Opened 2021-01-06 15:08 UTC by 10000sukk

코드 리뷰 힘드실 텐데 해주셔서 감사드립니다 ㅜㅜ

2021-01-07 10:48 UTC, ljh131 requested changes
클래스를 많이 분리하셨는데 특히 랜덤넘버 클래스는 의미가 일반적이지 않은 것 같습니다. 
모든 클래스에 equals, hashCode를 오버라이드 한것도 불필요해보이고요.
수정 후 다시 요청해주세요.

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/Racing.java
> +    private TryNumber tryNumber;
시도 횟수를 굳이 분리한 이유가 궁금합니다.

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/TryNumber.java
> +    public void useTryNumber() {
이왕 객체로 분리한거면 여기서 음수가 되는 경우 에러를 내주는게 좋을 것 같아요.

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> getCarsList(){
불필요해보입니다

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/RandomNumber.java
> +public class RandomNumber {
일반적으로 랜덤 넘버 생성기를 기대할텐데, 그냥 랜덤 넘버 자체를 나타내고 있네요. 이렇게 해야될 이유가 있나요?

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/Racing.java
> +    @Override
이 클래스는 왜 이퀄스와 해시코드를 오버라이드 했나요?

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/Cars.java
> +    @Override
여기도 이퀄스와 해시코드를 오버라이드한 이유가 궁금해요

2021-01-07 10:48 UTC, ljh131 commented on src/main/java/racingcar/domain/RandomNumber.java
> +        Random rand = new Random();
매 랜덤 넘버마다 매번 생성하게 되네요.

2021-01-08 04:36 UTC, 10000sukk commented
step2 1차 피드백 주셔서 감사합니다. 
테스트를 위해서 equals 를 만들었었는데 꼭 그렇게 할 필요가 없을 뿐더러 불필요한 기능 이더라구요... 수정 하였습니다.
한가지 질문을 하고 싶습니다!
Q. 클래스 안에 필드로 있는 상수 같은 경우는 매번 객체가 생성 될때마다 생성되기엔 오버헤드가 있으니 static 으로 지정 해주는 것이 적절 할까요??

2021-01-08 04:37 UTC, 10000sukk commented on src/main/java/racingcar/domain/RandomNumber.java
> +        Random rand = new Random();
이 부분은 static 으로 필드로 옮겨서 수정 하였습니다! 감사합니다

2021-01-08 04:38 UTC, 10000sukk commented on src/main/java/racingcar/domain/Racing.java
> +    @Override
삭제해서 없앴습니다. 불필요한 부분 인거 같습니다..

2021-01-08 04:39 UTC, 10000sukk commented on src/main/java/racingcar/domain/TryNumber.java
> +    public void useTryNumber() {
감사합니다!

2021-01-08 04:40 UTC, 10000sukk commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> getCarsList(){
이 부분은 output view 를 위해서 car 객체들을 포함하는 리스트가 필요해서 구현했었습니다! 없애는 방법쪽으로 생각을 해봤지만 도저히 생각이 나지 않아서요.. 혹시 조그만한 힌트라도 주실수 있다면 감사하겠습니다 ㅠㅠ

2021-01-08 04:42 UTC, 10000sukk commented on src/main/java/racingcar/domain/Racing.java
> +    private TryNumber tryNumber;
원시 값으로 되어있는 시도횟수를 포장하는 포비를 보고 따라해봤습니다!

2021-01-08 05:33 UTC, ljh131 requested changes
저번보다 나아진 것 같습니다. 몇 가지 커멘트 드렸는데요, 랜덤과 엮인 부분은 테스트가 없습니다. 랜덤을 분리해서 테스트할 수 있는 구조를 생각해보시고 수정해주세요.

2021-01-08 05:33 UTC, friediceday commented on src/main/java/racingcar/view/OutputView.java
> +public class OutputView {
패키지를 컨트롤러, 뷰 이렇게 분리하셨는데요, 이 클래스를 보면 뷰가 컨트롤러를 참조하고 있습니다. 컨트롤러가 뷰한테 최소한의 모델만 넘겨서 출력해주도록 하는건 어떤가요?

2021-01-08 05:33 UTC, friediceday commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> getWinner() {
여기서만 사용한다면 프라이빗인게 좋겠습니다.

2021-01-08 05:33 UTC, ljh131 commented on src/test/java/racingcar/domain/CarsTest.java
> +        assertThat(winnerCars).isEqualTo(
Car가 equals를 오버라이딩 하지 않았습니다. 지금은 동일한 객체를 리턴할테니 괜찮겠죠. 그런데 이런 방식이 좋은지 의문입니다.

마침 실제로 사용하는 getWinnerName이 있으니 굳이 테스트용 메서드를 열어두지 않아도 충분히 테스트할 수 있고, 위 문제도 피할 수 있는데 어떤가요?

2021-01-08 05:33 UTC, ljh131 commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> getCarsList(){
차가 몇대고 몇번 위치에 있는 차를 가져오는 방식도 생각해볼 수 있을 것 같습니다.

2021-01-08 05:33 UTC, ljh131 commented on src/main/java/racingcar/controller/Racing.java
> +    public List<String> splitNames(String str) {
이런 기능은 일반적이기 때문에 유틸로 분리하는 것도 좋을것 같아요.

2021-01-08 05:33 UTC, ljh131 commented on src/test/java/racingcar/domain/CarsTest.java
> +public class CarsTest {
moveAll 도 중요할 것 같은데 이 부분에 대한 테스트는 없습니다. 지금은 랜덤 때문에 바로 테스트할 수 없겠죠. 어떻게 해야할까요?

2021-01-08 05:37 UTC, ljh131 commented
질문 답변 드립니다.

```
Q. 클래스 안에 필드로 있는 상수 같은 경우는 매번 객체가 생성 될때마다 생성되기엔 오버헤드가 있으니 static 으로 지정 해주는 것이 적절 할까요??
```
-> 네. 이미 그렇게 하신 것 같네요.

2021-01-08 07:13 UTC, 10000sukk commented
피드백 주신 사항들 정말 감사합니다. 많은 도움이 되었습니다.
더 미흡한점 있으면 알려주시면 감사하겠습니다. 감사합니다

2021-01-08 12:36 UTC, ljh131 reviewed
수고하셨습니다. 첫 미션이니 여기서 머지하겠습니다.
커멘트는 꼭 참고해주시고요, 더 좋은 방법을 고민해보시면 좋겠습니다.

2021-01-08 12:36 UTC, friediceday commented on src/main/java/racingcar/controller/Racing.java
> +        cars.moveAll(RandomNumberForRacing.getRandomNumberListForRacing(cars.getNumberOfCars()));
랜덤값을 외부에서 매번 넣어줘야하고, 넣어주기 위해 차 개수도 알아야 하네요.

조금 더 우아하게 한다면, strategy pattern 을 사용해볼 수도 있습니다. 
예를 들어 테스트시 고정된 값을 내주는 클래스를 사용하고, 실제 동작시 랜덤을 내주는 클래스를 사용할 수 있습니다.

2021-01-08 12:36 UTC, friediceday commented on src/main/java/racingcar/domain/Cars.java
> +        if (carsList.size() != randomNumberList.size()) {
덕분에 이런 처리도 들어가야하고요.

2021-01-08 12:36 UTC, merged