[ian.lock 양정일] 자동차 경주 게임 2단계 PR입니다
NewKrew2021/java-racingcar-kakao pull request #54
Opened 2021-01-06 15:14 UTC by Jjungs7

- `List<Car>` -> `Cars` 로 변경하면서 OutputView에서는 `Cars.getCarStatus()` 및 `Cars.getNamesAppended()`에서 만들어진 String을 출력하도록 하였는데 이러한 구조가 괜찮은지 궁금합니다.
---
주요 변경사항은 다음과 같습니다:
- RacingcarGame(구: Simulator) 에서 입출력을 더욱 명확히 분리
- Cars 일급 컬렉션 추가
- 기존에는 OutputView에서 building 하던 문자열을 이제는 Cars 클래스에서 build

2021-01-06 15:15 UTC, Jjungs7 commented on src/main/java/com/nextstep/racingcar/controller/RacingcarGame.java
> +    Cars winners = racingcar.getCars().getWinners();
연쇄적인 get 메소드 호출이 괜찮은지 궁금합니다. 괜찮은게 아니라면 클래스 설계가 잘못된 것 일까요?

2021-01-06 15:43 UTC, findstar requested changes
안녕하세요, 피드백 진행하는 제임스입니다.
지난번 피드백을 기반으로 수정 잘 해주셨네요. 
몇가지 코멘트 남겼습니다. 확인부탁드립니다.

덧) 전체적으로 code format 을 조금 더 잘 다듬어 주시면 좋겠습니다. 
슬랙방에 공유했던 code reformat 기능을 활용해보세요 
그럼 화이팅입니다 !

2021-01-06 15:43 UTC, findstar commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  private final String CAR_UNIT_STEP_SYMBOL = "-";
Cars 에서 SYMBOL 을 가지고 있어야 할까요? 이건 출력을 위한 상수값으로 보이네요.

2021-01-06 15:43 UTC, findstar commented on src/main/java/com/nextstep/racingcar/controller/RacingcarGame.java
> +    Cars winners = racingcar.getCars().getWinners();
@Jjungs7 
racingcar 에서 winners car list 를 가져오는 방법은 없을까요? 
winner 를 구하는 방법을 좀 더 구분해보면, 
1. 가장 멀리 간 위치를 획득하고
2. 이 위치에 해당하는 Car List 를 획득하는
두 가지로 구분할 수 있을것 같은데요. 
Cars 에서 이런 메서드를 추가하면 어떨까요?

2021-01-06 15:43 UTC, findstar commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +    List<Integer> randoms = getNRandomDigitsForCars(getNumberOfCars());
random 때문에 테스트가 어려워집니다. 
자동차의 이동을 판단하는 로직 자체를 외부에서 주입받는 형태로 개선해보면 좀 더 테스트가 수월해집니다.

2021-01-06 15:43 UTC, findstar commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +  public String getCarsStatus() {
이건 출력을 위한 기능이므로 보입니다.

2021-01-06 15:43 UTC, findstar commented on src/main/java/com/nextstep/racingcar/domain/Cars.java
> +public class Cars {
Cars 가 전체적으로 너무 많은 역할을 수행하려고 하고 있습니다. 

조금더 가볍게 만들 수 있는 방법을 고민해보세요 😄

2021-01-06 15:43 UTC, findstar commented on src/test/java/com/nextstep/racingcar/domain/CarsTest.java
> +public class CarsTest {
각각 대응되는 클래스의 기능을 골고루 테스트 해야합니다. 
인텔리J에서 코드 커버리지를 확인할 수 있습니다.

2021-01-08 03:21 UTC, Jjungs7 commented on src/test/java/com/nextstep/racingcar/domain/CarsTest.java
> +        );
인수에 여러 메소드들이 nested 되는 상황에 대한 컨벤션을 못 본 것 같은데 이런 경우에는 괄호나 인수를 어떻게 작성하시는지 궁금합니다. 예를 들어

```java
Cars cars = new Cars(Arrays.asList(
        new Car("ian", 0),
        new Car("good", 0),
        new Car("valid", 0));
```
와 같은 경우도 있을텐데 리뷰어님만의 규칙이 있을까요??

2021-01-08 11:50 UTC, findstar approved these changes
안녕하세요 제임스 입니다. 
피드백 남긴 부분 수정 잘 해주셨어요~ 👍 
마지막에 random 때문에 테스트 하기 힘든 부분도 잘 처리해주셨습니다. 
자동차 경주 프로젝트 진행하시면서 고생 많으셨습니다. 질문이 있으시면 언제든 DM 주세요!
PR은 머지하겠습니다.
그럼 다음 프로젝트도 화이팅입니다!

2021-01-08 11:50 UTC, merged