[jamal.park] 2단계 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #55
Opened 2021-01-06 15:19 UTC by jypark5826

꼼꼼하게 피드백 해주셔서 감사드립니다:)
이전에 피드백 해주신 내용과 수업에서 참고한 내용들 반영해서 코드 수정해보았습니다.

2021-01-06 16:02 UTC, findstar requested changes
안녕하세요, 피드백 진행하는 제임스입니다.
지난번 답변드린 부분을 잘 적용해주셨네요. 
몇가지 코멘트 남겼습니다. 확인부탁드립니다.

그럼 화이팅입니다 !

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/domain/MovingStrategy.java
> +public interface MovingStrategy {
잘 구현해주셨네요 💯 
요런 경우에는 Functional Interface 어노테이션을 추가해주는게 좋습니다 
https://beomseok95.tistory.com/277

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/view/OutputView.java
> +            String distance = new String(new char[car.getDistance()]).replace("\0", "-");
```java
System.out.print(car.getName() + " : " + "-");
            IntStream.range(0, car. getDistance())
                    .forEach(t -> System.out.print("-"));
System.out.println();
```
와 같이 표현할 수도 있습니다 
stream 에 대해서 찾아보시면 좀 더 가독성 높은 코드를 작성하는데 도움이 됩니다 😄

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/view/OutputView.java
> +            String distance = new String(new char[car.getDistance()]).replace("\0", "-");
위치 출력을 위한 "-" 는 상수로 정의하면 좋겠습니다.

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/Main.java
> +        OutputView.printGetTime();
OutputView 는 결과 출력을 위한 View 라고 정의하면
getTImes 를 입력받기 위한 메세지 출력은 InputView 에서 처리할 수 있습니다. 

입력/출력에 대한 기준보다는 
입력 화면 / 결과 출력 화면 을 위한 클래스로 구분지으면 

역할이 좀 더 명확해집니다.

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/Main.java
> +        while (!racingGame.isEnd()) {
코드가 읽기 훨씬 더  편해졌습니다. 💯

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/domain/Cars.java
> +    public void moveAll(MovingStrategy movingStrategy) {
java.util.function.Consumer 를 사용할 수도 있습니다. 
이건 필수는 아니고 고민한번 해봐주세요. 😄

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/domain/Car.java
> +    public void move(MovingStrategy movingStrategy) {
여기서 MovingStrategy 를 입력받을 필요가 있을까요?
Car 는 단순히 이동이라는 기능만 있으면 되지 않을까요?

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/domain/Cars.java
> +            cars.add(new Car(name, INITIAL_DISTANCE));
Car 클래스의 생성자를 2개를 만들면 굳이 INITIAL_DISTANCE 가 필요하지 않습니다.

2021-01-06 16:02 UTC, findstar commented on src/main/java/racingcar/domain/Name.java
> +public class Name {
이름에 대한 역할을 위한 Name 클래스 까지 만드셨군요 💯

2021-01-06 16:02 UTC, findstar commented on src/test/java/racingcar/CarsTest.java
> +        cars.moveAll(() -> true);
람다 전달하는 방식을 익히셨군요 💯

2021-01-06 16:02 UTC, findstar commented on src/test/java/racingcar/NameTest.java
> +public class NameTest {
이건 팁입니다만, 
테스트 메서드 이름은 한글로 작성해도 됩니다. 
그게 팀원들과 같이 코드를 읽는데 도움이 될 수 있습니다. 
또는 @DisplayName 을 지정할 수도 있습니다.

2021-01-07 04:55 UTC, jypark5826 commented
input output을 어떻게 나눠야하는지 긴가민가해서 너무 과도하게 분리를 해놓았네요.. 고쳐놓았습니다.
피드백 해주신 사항들 고려해서 다시 작성해보았습니다!

2021-01-07 05:38 UTC, findstar requested changes
안녕하세요. 제임스입니다. 
지난번 피드백 수정 잘 해주셨네요. 👍 
마지막일것 같습니다만
코멘트 추가로 남겼습니다. 확인하시고 궁금하신 점은 편하게 질문주세요 😄 
그럼 화이팅입니다!

2021-01-07 05:38 UTC, findstar commented on src/main/java/racingcar/domain/Car.java
> +    public void move(int moveNumber) {
MovingStrategy 에서 진행가능한지 여부를 확인하고
Car 는 move 에만 집중하면 어떨까요?

2021-01-07 05:38 UTC, findstar commented on src/main/java/racingcar/domain/RacingGame.java
> +    public List<Car> getCars() {
RacingGame 에서는 cars 를 사용하지만
결국 내부에 getCars 라는 getter 를 두고 있네요.

2021-01-07 15:06 UTC, jypark5826 commented
이번에도 어떻게 수정해야 하는지 긴가민가 했지만 고민해서 피드백 받은 부분들을 수정해보았습니다!
틀렸으면 시원하게 피드백해주세요:)

2021-01-07 15:28 UTC, findstar approved these changes
안녕하세요 제임스 입니다. 
피드백 남긴 부분 수정 잘 해주셨어요~ 👍 
코드가 읽기도 편하고 의도도 잘 드러나 도록 개선되었다고 느껴집니다. 
몇가지 코멘트 남겼습니다만 이건 추가적으로 생각해보시면 됩니다. 
PR은 머지하겠습니다.
자동차 경주 프로젝트 진행하시면서 고생 많으셨습니다. 질문이 있으시면 언제든 DM 주세요!
그럼 다음 프로젝트도 화이팅입니다!

2021-01-07 15:28 UTC, findstar commented on src/main/java/racingcar/view/OutputView.java
> +        for (Car car : cars.getCars()) {
Cars 에 람다를 전달할 수 있는 apply 메서드가 존재한다면 다음과 같이 처리할 수 있습니다 
```java
        cars.apply(car -> {
            System.out.print(car.getName() + " : ");
            IntStream.range(0, car.getDistance())
                    .forEach(t -> System.out.print(DISTANCE_SYMBOL));
            System.out.println();
        });
```
이때 인자의 타입은 java.util.function.Consumer 타입형태가 됩니다. 
스트림과 람다에 대해서 배우셨으니 다음의 내용도 금방 이해하실 수 있을꺼라고 생각되어서 피드백 남겼습니다 😄 
```java
// Cars.java

public void apply(Consumer<Car> consumer) {
        cars.forEach(consumer);
    }
```

2021-01-07 15:28 UTC, findstar commented on src/main/java/racingcar/domain/RacingGame.java
> +        cars.moveAll(new RandomMovingStrategy());
race 메서드 안에서 RandomMovingStrategy 에 의존하면
인터페이스로 분리한 구조의 의미가 퇴색됩니다. 인터페이스를 주입받도록 개선해보세요.
또는 생성자 시점에 MovingStrategy 를 주입받아서 처리할 수 도 있습니다.
그렇게 되면 race 메서드를 테스트 하기가 더 쉬워집니다. 

의존관계를 연결하는 방식에서 의존성 주입의 방식에 대해서 나중에 찾아보시면 도움될것 같습니다.

2021-01-07 15:28 UTC, findstar commented on src/test/java/racingcar/CarTest.java
> +public class CarTest {
CarTest 에서는 Car 의 기능을 가능한 충분히 테스트 하는것이 좋습니다. 
인텔리J 의 커버리지 기능을 잘 활용해 보세요 😄 
![image](https://user-images.githubusercontent.com/1266944/103910458-32666a80-5148-11eb-9a2d-af058bcea829.png)

2021-01-07 15:28 UTC, findstar commented on src/test/java/racingcar/NameTest.java
> +public class NameTest {
DisplayName 어노테이션을 사용하면
인텔리J 에서 테스트 결과를 확인하기 더 좋아집니다 😄 
![image](https://user-images.githubusercontent.com/1266944/103910623-6477cc80-5148-11eb-9290-d6f86ff5401b.png)

2021-01-07 15:28 UTC, merged

2021-01-08 10:39 UTC, jypark5826 commented
친절하고 꼼꼼한 피드백 감사드립니다:)