[kuri.copper 송동욱] 자동차경주 Step2 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #57
Opened 2021-01-06 16:04 UTC by D-kuri

피드백 해주신 내용들 감사합니다 :)

한가지 질문 드리고 싶습니다. 

- move관련 기능들이 cars -> car -> Location 방향으로 모두 생성되어 있는데 이 경우 어느 클래스에서 단위 테스트를 해줘야 하는 것인지 궁금합니다. 모든 클래스에서 테스트를 진행해야 하는 건가요?? 아니면 제가 논리적으로 코드를 작성하지 못한건지 알고 싶습니다 !

2021-01-07 00:15 UTC, dongjoon1251 requested changes
mvc 패턴을 적용하기 위해서 패키지를 잘 나누어 주셨네요 👍 
다만 이전에 드렸던 피드백들에 대해서 다시 한번 검토해보시고 반영해주시기 바랍니다. 빠진 부분들이 꽤 있어보입니다.

질문에 답변을 드리자면 다음과 같습니다. 
move 관련 기능들은 하위 도메인으로 전파가 가능합니다. 크게 문제될 것은 없습니다. :)
이번 미션에서는 TDD에 익숙해지는 것에 초점을 두시고, 단위테스트를 클래스 코드보다 먼저 작성해주시기 바랍니다. 
테스트 코드는 모든 클래스의 public 메소드에 대해서는 전부 존재하는 것이 좋습니다.

추가 요청 사항
- empty.txt 파일은 제거해주세요. 
- 이전에 car를 move 시키는 조건을 분리하는 방법에 대해서 한번 고민 부탁드렸는데 어떤 방법이 있을까요? 아무리 고민해도 감이 안잡히신다면 전략패턴에 대해서 공부해보시면 좋을 것 같습니다. 이 패턴을 적용하는 것이 정답은 아니지만 하나의 선택지가 될 수 있습니다.
- 메소드 간에 줄바꿈이 없는 경우, 줄바꿈이 2줄 이상 된 경우들이 종종 보입니다. 가이드되었던 reformat 기능을 적용해보시기 바랍니다. 매번 reformat을 수행하는 것을 잊게된다면 intelliJ의 saveAction 플러그인을 적용해보시기 바랍니다.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/Main.java
> +public class Main {
클래스명이 Main으로 바뀌었지만 여전히 해당 클래스가 있어야 하는지는 의문이 있네요 :)

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +            throw new InvalidRoundLengthException("횟수를 1회 이상 입력해주세요.");
round도 Name, Location처럼 클래스로 분리하면 check하는 로직을 분리할 수 있지 않을까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +        OutputView.printRoundStart();
round는 startRound말고는 쓰이는 곳이 없는데 해당 메소드에 파라미터로 넘겨주는게 어떨까요?
setter 메소드는 지양해주세요 :)

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +        OutputView.printInputCars();
단순히 출력이라는 관점에서 보면 OutputView에 있어도 무방하지만, 입력을 받기 위해 사용자에게 질의하는 목적이라면 InputView에 있어도 되지 않을까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +            throw new InvalidRoundLengthException("횟수를 1회 이상 입력해주세요.");
추가로 파라미터로 넘긴 문자열은 해당 Exception에 대한 것인데 클래스 내부에 있어도 되지 않을까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +        return name.toString() + " : " + "-".repeat(location.getLocation());
String 을 합치는 다른 방법에 대해서 혹시 알아보셨나요? 어떤 방식이 더 효율적인지 확인부탁드립니다.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +        return name.toString() + " : " + "-".repeat(location.getLocation());
해당 메소드는 locations를 가져온다기 보다는 출력을 위한 목적으로 보입니다. dto로 만들어서 전달하거나 이미 만들어진 getter를 사용하게 하면 어떨까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +        if(location.getLocation() == winnerLocation){
location의 location이 winnerLocation과 같은지 확인하는 부분은 location 내부 로직으로 처리할 수 있지 않을까요?
winnerLocation도 Location 으로 받는게 어떨까요?
Location의 equals 메소드를 활용해봐도 좋을 것 같습니다.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
>          addCarName(parsingCarNames);
setter 메소드는 지양해주세요 :)
해당 로직은 생성자에서 처리되게 하는게 어떨까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +        return name.toString() + " : " + "-".repeat(location.getLocation());
repeat는 java11에서 지원되는데 gradle은 java8으로 되어있습니다. java8에서 지원되는 방법을 알아보면 어떨까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +    private Location location = new Location();
Location의 default 값이 바뀔 경우에 어떤 영향이 있을까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +        OutputView.printWinner(cars.getWinner());
게임의 결과를 출력하는 관점에서 보면 OutputView가 아니라 ResultView로 바꿔볼 수 있지 않을까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
>          return (int)(Math.random()*10);
해당 메소드의 역할이 random number를 set하는 걸로 보이지 않습니다.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
> +            roundReulst += car.getCarLocations() + "\n";
결과 출력을 위한 로직으로 보입니다. 
이미 해당 메소드에 getCars 메소드가 있는데, 외부에서 이 메소드로 정보를 받고 결과출력을 위한 가공은 다른 클래스에서 처리하는게 어떨까요?

그리고 rountReulst 오타로 보입니다.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
>      }
아래와 같이 최대한 한 라인에 point 하나가 출력되게 수정해주세요.
cars.stream().
     mapToInt().
     ...

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Location.java
> +    @Override
equals & hashCode 메소드가 다른 도메인 클래스에는 없는 이유가 있을까요?

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Name.java
> +    private final int MAX_NAME_LENGTH = 5;
static이 있는 부분이 있고 없는 부분이 있는데 어떤 역할인지 공부해보시면 좋을 것 같습니다.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Name.java
> +    @Override
equals & hashCode 메소드는 클래스의 맨 하단에 정의해주세요 :)

2021-01-07 00:15 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +        if(location.getLocation() == winnerLocation){
Car 클래스는 name 하나만 갖고 있는데 findWinner라는 메소드가 있는게 어색해보입니다. name을 리턴하고 있기도 하구요

2021-01-07 00:15 UTC, dongjoon1251 commented on src/test/java/racingcar/domain/CarTest.java
> +
getter를 제외한 모든 메소드는 테스트코드에 추가해주세요 :)
클래스에 메소드를 만들기전에 test 코드를 먼저 작성해보는 연습을 계속 해주시면 좋을 것 같습니다.
이번 미션의 목적을 기능구현보다는 TDD를 연습하는 것에 초점을 맞춰주세요.

2021-01-07 00:15 UTC, dongjoon1251 commented on src/test/java/racingcar/domain/CarsTest.java
Cars에 나오는 모든 public 메소드들도 테스트코드에 추가해주세요 :)

2021-01-07 09:34 UTC, D-kuri commented on src/main/java/racingcar/domain/Car.java
> +        return name.toString() + " : " + "-".repeat(location.getLocation());
concat이나 +와 같은 방법으로 기존 문자에 합치거나 스트링 빌더, 스트링 버퍼와 같은 방법으로 문자에 합치는 방법이 있다는걸 알게 되었습니다. 전자와 같은 방법은 string이 immutable하기 때문에 매번 새로운 string 객체를 생성하는 반면 후자의 방법은 동일 객체내에 추가/삭제를 하기 때문에 더 효율적인 방법이라고 공부하였습니다 :)
다만 이번 경우에는 조금 메모리를 낭비하더라도 간단하게 코드를 작성하기위해 replace를 사용해서 repeat처럼 기능을 수정해보았습니다.

2021-01-07 09:37 UTC, D-kuri commented on src/main/java/racingcar/domain/Car.java
> +        return name.toString() + " : " + "-".repeat(location.getLocation());
추가적으로 Name과 Location을 분리한 상태에서 Car에 관한 DTO를 만들어 해당 문자만을 전달하게 하는 것에 대해서 조금 효율적이지 않을것이라 생각하여 DTO를 만들지않고 기존 getter를 이용하여 출력할 내용을 전달하였습니다 !

2021-01-07 12:11 UTC, D-kuri commented on src/main/java/racingcar/domain/Car.java
> +    private Location location = new Location();
음... default 자체가 기본적으로 설정하는 값이라고 알고 있습니다. default값 자체가 바뀌게 되면 기본 설정 값이 바뀌므로 프로그램 전체에 영향을 주어 프로그램의 조건이나 논리가 달라지는 상황이 올 것 같습니다. 여기서는 위치값이 바뀌므로 자동차의 출발 지점이 바뀌는 상황이 올 것 같습니다.

2021-01-07 12:44 UTC, D-kuri commented on src/main/java/racingcar/domain/Location.java
> +    @Override
기본적으로 객체는 각각이 고유하다고 알고 있습니다. Name과 Location의 경우 테스트에서 똑같은 조건의 객체를 2개 만들고 비교를할때 isEqualTo를 사용했기 때문에 두 객체가 같음을 비교하기위해 override하여 equals를 사용하였습니다. hashcode의 경우 잘 알지 못하고 자동으로 같이 생성되었기에 사용하였습니다. 무엇인지 이번 기회에 알아보았고 객체의 주소를 변환하여 보여주는 고유한 값이라는 것을 알게 되었습니다. 결론적으로 객체의 논리적 동일성을 보장하기 위해 두개의 메소드를 같이 오버라이드 해주는 것 같습니다.

2021-01-07 12:50 UTC, D-kuri commented on src/main/java/racingcar/domain/Name.java
> +    private final int MAX_NAME_LENGTH = 5;
자바 프로그램이 실행되기 전 가장 먼저 메모리 영역에 올라가는 부분이 static인것으로 알고 있습니다 ! 메모리상에 별도로 존재하며 공유되는 자원이다 라는 정도로 이론을 알고 있었지만 실제로 적용하려고 하니 이것저것 신경쓰지 못한것 같습니다. 앞으로 해당 역할에 따라 잘 분리해보도록 노력하겠습니다 ㅠ

2021-01-07 14:09 UTC, D-kuri commented
move 전략 분리에 대해서 생각을 해봐도 어떻게 분리할지 감이 잡히지 않네요 ㅠㅠ 그래서 포비가 말해주신 3가지 방법중 하나인 인터페이스를 사용해서 무브전략을 만들어봤습니다. 그 외 코드 컨벤션이나 논리적이지 못한 부분들 수정해보았습니다.

2021-01-08 00:32 UTC, dongjoon1251 requested changes
전략패턴을 잘 적용해주셨습니다 :)
제가 드렸던 코멘트에 대한 피드백도 잘 반영해주셨네요.
몇가지 추가로 코멘트 남겼습니다. 조금만 더 힘내주세요!

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/Round.java
> +
Round 는 도메인으로 볼 수 있을 것 같습니다. 지금은 controller package에 있네요 :)

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/Round.java
> +        ResultView.printRoundStart();
Round는 rount 파라미터에 대한 검증만 수행하고, 출력하거나 cars를 이동시키는 부분은 GameManager에서 수행하게 하는게 어떨까요?

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +        result();
이부분은 메소드로 분리하지 않아도 무방해 보입니다 :)

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +    private static Round round;
멤버 변수로 선언하지 않고 main 함수 안에서 로컬 변수로만 사용하는게 어떨까요?

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/Round.java
> +
Round에 대한 테스트도 추가해주세요

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +    private Location location = new Location();
말씀해주신대로 전체에 영향이 있습니다. 테스트 코드에도 영향이 있습니다. CarTest에서 location을 가져와서 검증하는 부분들도 모두 실패하게 됩니다. 이런 영향들을 줄이기 위해서 Location은 항상 파라미터를 받아서 초기화 시키고, Location의 최소값을 검증하는 로직도 추가해보면 어떨까요? Car를 초기화시킬 때도 Location을 항상 받도록 수정하는 부분에 대해서도 고민해주시기 바랍니다.

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Car.java
> +        location.move(moveStrategy);
전략 패턴을 잘 적용해 주셨네요 👍

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
> +            car.move(new RandomNumberMoveStrategy());
전략을 controller부터 주입하게하면 어떨까요?

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
> +        String roundResult = "";
출력에 대한 코드를 수정할 때, 도메인 코드도 같이 수정해야 할 것으로 보입니다. 아래의 역할도 출력을 관리하는 클래스로 옮겨보면 어떨까요?

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Location.java
> +    public void move(MoveStrategy moveStratege) {
파라미터명 오타인것 같습니다.

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/exception/InvalidRoundLengthException.java
> +        super("횟수를 1회 이상 입력해주세요.");
문자열은 모두 상수로 분리하면 어떨까요?

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/view/InputView.java
> +        System.out.println("경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분)");
여기서도 문자열은 상수로 분리하면 어떨까요? Exceptoin, OutputView 등 문자열을 상수로 분리할 수 있으면 분리해보면 좋을 것 같습니다.

2021-01-08 00:32 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Cars.java
> +        return cars.stream()
winner의 name list를 리턴하고 space로 join하는 부분은 출력하는 클래스에서 담당하도록 수정해보면 어떨까요?

2021-01-08 04:51 UTC, dongjoon1251 approved these changes
피드백 반영하시느라 고생하셨습니다.
일단 이번 미션은 여기서 마무리 짓도록 하겠습니다.
다음 미션에 도움이 될수있을만한 코멘트를 추가로 남겼습니다. 확인해주시고, 다음 미션 수행시에는 잘 고려해서 적용해주세요 :)
그리고 주로 성공하는 테스트 코드만 작성하기보다는 실패할 수 있는 케이스들을 찾아서 테스트 코드에 넣어보시면 좋을 것 같습니다.

2021-01-08 04:51 UTC, dongjoon1251 commented on src/main/java/racingcar/controller/GameManager.java
> +
제가 의도했던 건 출력에 대한 로직은 ResultVeiw 쪽으로 옮기는 것이였는데 잘 전달되지 않은 것 같습니다 ㅜㅜ

2021-01-08 04:51 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Location.java
> +        if (location < 0) {
외부에서 location이 음수일 경우, 잘못되었다는 것을 인지시키기 위해서 Exception을 발생시키는 것이 더 낫다고 보여집니다.

2021-01-08 04:51 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Round.java
> +        if (round < 1) {
round의 최소값도 상수로 분리하면 좋을 것 같습니다.

2021-01-08 04:51 UTC, dongjoon1251 commented on src/main/java/racingcar/domain/Location.java
> +        if (location < 0) {
location의 최소값도 상수로 분리하는게 좋을 것 같습니다.

2021-01-08 04:51 UTC, merged