[eli.nabro 일라이, 오영민] 자동차 경주 Step2 코드리뷰 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #58
Opened 2021-01-06 16:37 UTC by maireneu

안녕하세요. 일라이 입니다.

Step1 에서 피드백주신 내용 정말 감사드립니다!
Step2에서 MVC 패턴을 적용하였습니다. 1단계에서 많은 것을 배우고, 주신 피드백을 이행하면서 MVC 패턴을 그래도 수월하게 구현해 볼 수 있었습니다. 

또한 Parameterized test를 포함한 그외 언급해주신 피드백 사항을 고쳤습니다!

감사합니다.

2021-01-07 02:25 UTC, findstar requested changes
안녕하세요. 제임스 입니다. 
지난번 피드백 잘 반영해주셨네요. 수고하셨습니다 👍 

몇가지 추가 코멘트 남겼습니다. 확인 부탁드립니다. 
잘 이해가 되지 않거나, 궁금한 사항은 직접 메세지 주셔도 좋습니다 😄 
그럼 오늘도 화이팅입니다!

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/RacingGameMain.java
> +/*
주석을 작성할 때는 코드를 이해하는데 도움을 주는 경우에 작성하는 것을 추천드립니다
이런 컨벤션에 따른 주석은 굳이 달지 않아도 됩니다.

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/RandomValue.java
> + * Version  : 1.1
주석에 버전을 기록하면 매번 신경쓰기가 어렵습니다.

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/view/RacingInputUI.java
> +    private static final String PRINT_CAR_NAME_QUESTION = "경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).";
output 에서 input 쪽으로 이동했네요. 👍

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/view/RacingInputUI.java
> +    /* set input string to defined string for testing */
테스트만을 위한 메서드를 추가하지 말고 테스트가 가능한 형태로 리팩토링하는 부분을 더 신경쓰면 좋습니다.

2021-01-07 02:25 UTC, findstar commented on src/test/java/racing/RacingGameMainTest.java
> +public class RacingGameMainTest {
Main 메서드가 있는 클래스까지 테스트 하지 않아도 됩니다.

2021-01-07 02:25 UTC, findstar commented on src/test/java/racing/domain/CarTest.java
> +        car.move();
Car 클래스에
Name 과 Position 을 입력받는
생성자를 추가하면 이런 테스트가 더 쉽게 처리될 수 있습니다.

클래스의 생성자를 여러개 만들 수 있다는 점을 기억해주세요 😄

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/RacingGameMain.java
> +        RacingOutputUI.printWinner(racingGameLogic.whoAreWinner(noTrials));
noTrials 를 winner 에 전달하는 이유가 있을까요?

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/RacingGameMain.java
> +        int noTrials = RacingInputUI.inputNumberOfTrials();
noTrials 라는 이름은 잘못 읽으면 Trials 가 아니다라는 의미로 읽힐 수 있습니다.
numberOfTrials 로 변경해도 좋습니다. 

네이밍은 계속 어떤게 더 좋을까 고민해보시면 도움이 됩니다.
1개월 뒤에 내가, 또는 다른 팀 동료가 읽기에 편한 이름은 무엇일까 고민해 보세요

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/RandomValue.java
> +            randomValues.add(random.nextInt(10));
NextInt 활용 좋습니다. 💯

2021-01-07 02:25 UTC, findstar commented on src/main/java/racing/RandomValue.java
> +        Random random = new Random();
static 메서드 호출에서는 Random 객체를 매번 생성할 필요가 있을까요?

2021-01-07 13:58 UTC, maireneu commented on src/main/java/racing/RacingGameMain.java
> +/*
네 주석을 달때 유의하도록 하겠습니다.

2021-01-07 13:58 UTC, maireneu commented on src/main/java/racing/RandomValue.java
> + * Version  : 1.1
해당부분을 삭제하도록 하겠습니다!

2021-01-07 13:59 UTC, maireneu commented on src/main/java/racing/view/RacingInputUI.java
> +    /* set input string to defined string for testing */
테스트가 가능한 형태로 리팩토링 하도록 하겠습니다!

2021-01-07 13:59 UTC, maireneu commented on src/test/java/racing/RacingGameMainTest.java
> +public class RacingGameMainTest {
해당 Main 메서드의 테스트를 삭제하였습니다.

2021-01-07 14:00 UTC, maireneu commented on src/test/java/racing/domain/CarTest.java
> +        car.move();
Car 클래스에 position을 입력받을 수 있는 생성자를 추가하였습니다.

2021-01-07 14:00 UTC, maireneu commented on src/main/java/racing/RacingGameMain.java
> +        RacingOutputUI.printWinner(racingGameLogic.whoAreWinner(noTrials));
해당 변수를 생성자에서 인자로 받아서 세팅할 수 있도록 변경하였습니다.

2021-01-07 14:00 UTC, maireneu commented on src/main/java/racing/RacingGameMain.java
> +        int noTrials = RacingInputUI.inputNumberOfTrials();
해당 변수이름을 수정하였습니다. 명명법을 좀더 직관적으로 작성하도록 유의하겠습니다.

2021-01-07 14:01 UTC, maireneu commented on src/main/java/racing/RandomValue.java
> +        Random random = new Random();
해당 Random 객체를 static 맴버변수로 변경하였습니다.

2021-01-07 14:01 UTC, maireneu commented on src/main/java/racing/RandomValue.java
> +            randomValues.add(random.nextInt(10));
감사합니다!

2021-01-07 14:05 UTC, maireneu commented on src/main/java/racing/view/RacingInputUI.java
> +    private static final String PRINT_CAR_NAME_QUESTION = "경주할 자동차 이름을 입력하세요(이름은 쉼표(,)를 기준으로 구분).";
감사합니다!

2021-01-07 14:24 UTC, findstar requested changes
안녕하세요 제임스 입니다. 
피드백 반영 잘 해주셨네요 💯 
코드가 정말 많이 좋아졌습니다. 읽기도 편하고 의도도 잘 드러나 있네요 😄 
random 때문에 테스트하기 어려운 부분에 대해서만 다시 코멘트 남겼습니다.
확인부탁드립니다. 화이팅입니다!

2021-01-07 14:24 UTC, findstar commented on src/main/java/racing/domain/RacingGameLogic.java
> +    public boolean checkPosition() {
이제 checkPosition 을 다시 생각해보면 
numberOfTrials 에 도달했는지 않했는지만 확인하면 됩니다. 
개별 자동차의 포지션을 확인하지 않아도 됩니다

2021-01-07 14:24 UTC, findstar commented on src/main/java/racing/domain/RacingGameLogic.java
>      public void race() {
random 때문에 race 를 진행하는 동작을 테스트하기가 어렵습니다. 
테스트 하기 어려운 부분은 별도의 클래스로 분리해내면 테스트가 수월해 집니다.

2021-01-07 17:05 UTC, maireneu commented on src/main/java/racing/domain/RacingGameLogic.java
>      public void race() {
RacingGameLogic에서 RandomValue Class를 의존하지 않도록 변경하였습니다!

2021-01-07 17:05 UTC, maireneu commented on src/main/java/racing/domain/RacingGameLogic.java
> +    public boolean checkPosition() {
이전에 피드백주신부분 다음번에도 유념하도록 하겠습니다. 감사합니다!

2021-01-11 11:49 UTC, findstar approved these changes
안녕하세요 일라이! 
질문 주신 내용에 대해서 설명드렸습니다만
아직 랜덤을 처리하시는데 고민이 많으신것 같습니다.
별도의 인터페이스로 분리해보기를 권장드립니다. 
DM 과 구글 Meet 을 통해서 설명 드린 부분이 있으니 
이 PR 은 머지하고 다음 미션에 집중해주세요. 
수고 많으셨습니다. :) 

수고 많으셨습니다.

2021-01-11 11:49 UTC, merged