[pharrell.mp3 민필규] 자동차 경주 step2에 대해 PR 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #60
Opened 2021-01-06 16:47 UTC by pilgyumin

안녕하세요!
pharrell(퍼렐, 민필규)입니다.

1차 코드 리뷰에 대한 피드백을 정성스럽게 작성해주셔서 정말 감사드립니다.

1차 피드백에 대한 부분 중에 해결한 부분은 resolve conversation 버튼을 눌렀고,
질문이 생긴 부분에 대해서는 코멘트로 질문을 달아놓았습니다.

이번 2차 PR은 1차 피드백에 대한 추가 구현과 포비가 작성해주신 2단계 구현에 대해
신경써서 코드를 작성하였습니다.

그럼 2차 피드백도 잘 부탁드리겠습니다.

감사합니다.

2021-01-06 21:08 UTC, Hue9010 requested changes
안녕하세요 퍼렐 ~!! 리뷰어 휴입니다.
저번 피드백 잘 적용해주셨네요. 👍
1차 피드백에 남겨주신 질문에도 답변드렸는데 혹시 놓친 부분 있으면 말씀주세요. 😉
이번에도 몇가지 코멘트 남겼는데 확인하시고 궁금한건 문의주세요~

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/utils/CarRacingProgramPhrases.java
>      public static final String WINNER_PHRASE = "가 최종 우승했습니다.";
지금처럼 상수를 모아둔 클래스를 만드는건 과거 자바 1.5 이전 enum이 존재하지 않을 때 주로 사용하던 방식입니다. 당시엔 정수를 모아뒀었다는 점에서 꽤 다르지만 정말 필요하지 않다면 상수만 모아둔 지금같은 클래스는 불필요합니다. 실제 사용도 View에서만 이뤄지고 있는데 View로 옮기면 됩니다. 😉 

[이펙티브 자바 Item 34. Int 상수 대신 열거 타입을 사용하라](https://jaehun2841.github.io/2019/02/03/effective-java-item34/#%ED%83%80%EC%9E%85-safe%ED%95%98%EC%A7%80-%EC%95%8A%EB%8B%A4)

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +        return cars;
향상된 for문을 잘 사용해주셨네요. 스트림을 사용하시는 분들이 많던데 그럼 이번엔 스트림에 익숙해지는 차원에서 스트림을 사용해보세요. (스트림이 더 좋기때문에 제안드리는건 아닙니다)

이미 아실 수도 있는데 향상된 for문을 만들 때 intellij에서의 꿀팁이 names.for까지만 타이핑 한 상태에서 엔터를 치면 for문을 완성해줍니다. 😮

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    private final String NAMES_DELIMETER = ",";
[[코딩규칙] 자바 코딩 규칙(Java Code Conventions)](https://myeonguni.tistory.com/1596)

> 3.1.3 Class와 Interface 선언
> 클래스(static) 변수 : 첫번째로는 public 클래스 변수들이 나오고, 그 다음에 protected 클래스 변수들, 그 다음에 package(접근 제한자가 없는 경우) 클래스 변수들, 그 다음에 private 클래스 변수들이 나온다.


세부적인 컨벤션은 개인, 팀마다 다를 수 있으니 참고만 하셔도 됩니다. 😉

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/Car.java
> +        return MINIMUM_NAME_LENGTH <= name.length() && name.length() <= MAXIMUM_NAME_LENGTH;
NPE에 대한 체크도 하면 좋을 것 같습니다. 😉

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/Car.java
> +    }
요구사항에 꼴등을 찾는다가 추가되면 어떻게 될까요? 지금 메서드 명은 우승자만 찾을 수 있는걸로 보이지만 실제로는 입력받은 position에 자동차가 위치하는지 확인하는 메서드입니다. 메서드명과 더불어 매개변수 명을 적절하게 수정해주세요.

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
`findRaceWinners`, `compareMaxMoveDistanceToCarMoveCount`을 하나의 스트림으로 만들어 보세요.

위의 `mapCarNamesToCars`과 여기만 스트림을 사용하세요. 혹시 스트림이 이미 익숙하시다면 하지 않으셔도 됩니다. 😉

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +public class CarRacingProgram {
CarRacingProgram가 MVC에서 Controller와 Model중 어디에 해당할까요? 패키지 상으로는 모델에 해당하지만 컨트롤러의 역할까지 담당하고 있는걸로 보여요. 그러다보니 CarRacingProgram이 생각보다 복잡하다고 느껴집니다. MVC에 맞춰서 Controller도 만들어보세요.

분리시 약간 힘들 수 있는 부분이 보이는데 한 라운드가 끝날 때마 Car의 위치를 출력하는건  [2단계 - 자동차 경주 리팩토링](https://edu.nextstep.camp/s/bb4PXLji/ls/W1LFM86E)의 MVC 패턴으로 리팩토링 후의 main 메소드 예시를 참고하면 좋을 것 같아요.

```java
        while(!racingGame.isEnd()) {
            racingGame.race();
            ResultView.printCars(racingGame.getCars());
        }
```

제가 생각한 개선 방안이 꼭 답은 아니니까 다른 형태로 구현해도 됩니다. 특히 온라인으로 비동기적으로 소통하다보니 제가 의도한 부분을 캐치하지 못하면 거꾸로 헤맬수 있으니 여러 방법 중 한가지 힌트 정도로 생각하고 진행하시면 돼요. 😋 

사실 코드는 전체적으로 깔끔히 잘 짜주셔서 이부분만 개선하면 될 것 같습니다. 선택사항으로 List<Car>를 일급컬렉션으로 만들어 보는 것도 좋을 것 같아요. 선택사항이기 때문에 다른 곳부터 다 개선한다음 고민하시는게 좋습니다. 😉

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/Car.java
> +    private String name;
자동차의 이름은 바뀌지 않는 값이라고 생각한다면 final로 선언하는 것도 고려해 볼 수 있습니다.

2021-01-06 21:08 UTC, Hue9010 commented on src/main/java/carracing/domain/Car.java
> +        positionBuilder.append(" : ");
👍👍👍
말씀드린 이유로 큰 문제가 발생하진 않지만 이게 생각보다 많이하는 실수에요. 😏

2021-01-06 21:08 UTC, Hue9010 commented on src/test/java/carracing/CarTest.java
>      }
테스트명인 goTest와 실제 테스트가 일치하지 않네요. 참고로 프로젝트 내 작성한 모든것은 관리해야할 대상입니다. 비즈니스 코드, 주석, 테스트 코드 뿐 아니라 각종 설정파일까지 포함됩니다. 😋 

테스트 메서드에 한해서는 한글로 작성하거나 junit5라면 @DisplayName을 활용하는게 좋습니다. 영어 그대로 작성한다 해도 띄어쓰기 시 `_`를 사용할 필요가 없다는 장점이 있습니다.

2021-01-06 21:08 UTC, Hue9010 commented on src/test/java/carracing/CarTest.java
> +    }
👍👍👍
한가지 살짝 보완하자면 경계값을 테스트하는게 좋습니다. 조건을 이하로 만들어야 하는데 미만으로 구현 할 수 있어 경계값으로 테스트하는게 좋습니다.

```java
        LocalDateTime now = LocalDateTime.now();
        now.isBefore(now);
```
동일한 시간을 비교하면 true/false 중 무엇일 까요? 🤔 자신이 직접 조건식을 작성하지 않고 라이브러리를 사용할 때 어림짐작으로 사용하여 버그가 발생하기도 합니다. 😉

2021-01-07 08:44 UTC, pilgyumin commented on src/main/java/carracing/utils/CarRacingProgramPhrases.java
>      public static final String WINNER_PHRASE = "가 최종 우승했습니다.";
넵 반영하겠습니다!

2021-01-08 05:16 UTC, pilgyumin commented on src/main/java/carracing/domain/CarRacingProgram.java
> +        return cars;
네 스트림 반영해보겠습니다!

2021-01-08 05:28 UTC, pilgyumin commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    private final String NAMES_DELIMETER = ",";
넵 감사합니다!

2021-01-08 05:49 UTC, pilgyumin commented on src/main/java/carracing/domain/Car.java
> +        return MINIMUM_NAME_LENGTH <= name.length() && name.length() <= MAXIMUM_NAME_LENGTH;
넵 반영하겠습니다!

2021-01-08 05:59 UTC, pilgyumin commented on src/main/java/carracing/domain/Car.java
> +    }
넵 해당 부분 고려해서 수정하겠습니다!

2021-01-08 06:22 UTC, pilgyumin commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
넵 반영하겠습니다!

2021-01-08 06:25 UTC, pilgyumin commented on src/main/java/carracing/domain/Car.java
> +    private String name;
넵 반영하겠습니다!

2021-01-08 06:26 UTC, pilgyumin commented on src/main/java/carracing/domain/Car.java
> +        positionBuilder.append(" : ");
넵 앞으로는 해당 부분 고려하여 코드 작성하겠습니다!

2021-01-08 07:05 UTC, pilgyumin commented on src/test/java/carracing/CarTest.java
>      }
넵 해당 부분 반영하겠습니다!

2021-01-08 07:22 UTC, pilgyumin commented on src/test/java/carracing/CarTest.java
> +    }
넵 테스트 케이스 작성 시에 해당 부분 고려하겠습니다!

2021-01-08 11:06 UTC, pilgyumin commented on src/main/java/carracing/domain/CarRacingProgram.java
> +public class CarRacingProgram {
네 해당 부분 반영하겠습니다.

2021-01-08 16:54 UTC, Hue9010 approved these changes
잘 반영해주셨네요 👍 
이번 단계는 여기서 머지할게요. 자동차 경주 진행하시느라 고생 많으셨습니다!!
몇가지 피드백 남겼는데 궁금하신 점 있으면 언제든 질문주세요. 😉 
다음 단계도 화이팅입니다!!

2021-01-08 16:54 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
아래와 같이 사용하실 수도 있습니다.

```java
    public List<Car> mapCarNamesToCars(String[] names) {
        return Arrays.stream(names)
                .map(Car::new)
                .collect(Collectors.toList());
    }
```

스트림을 잘못 쓰는것도 문제지만 우선 스트림에 익숙해지는게 좋을 것 같네요. 간단한 반복문은 스트림으로 작성해보는 것도 좋을 것 같아요. 스트림의 개념을 이해하고 사용하는게 가장 좋지만 제대로 학습하려고하면 생각보다는 쉽지 않을 수 있어 우선은 map, filter, collect 정도만 익숙하게 사용해도 유용하게 쓰실 수 있을 겁니다. 😉 

보면 좋을 것 같은 내용들입니다. (아래 두개는 스트림 사용시 조심하면 좋은 사항)
[Become a Master of Java Streams - Part 1: Creating Streams](http://minborgsjavapot.blogspot.com/2019/10/become-master-of-java-streams-part-1.html)
[for-loop 를 Stream.forEach() 로 바꾸지 말아야 할 3가지 이유](https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/)
[Java8 Stream은 loop가 아니다.](https://www.popit.kr/java8-stream%EC%9D%80-loop%EA%B0%80-%EC%95%84%EB%8B%88%EB%8B%A4/)

2021-01-08 16:54 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
이제 보니 throws RuntimeException 은 왜 있을까요? 🤔

2021-01-08 16:54 UTC, Hue9010 commented on src/main/java/carracing/domain/Car.java
> +        return name != null && MINIMUM_NAME_LENGTH <= name.length() && name.length() <= MAXIMUM_NAME_LENGTH;
null check 먼저 👍

2021-01-08 16:54 UTC, Hue9010 commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
mapCarNamesToCars에서 예시로 드린 코드에 filter를 추가하는 걸로 개선 가능 할 것 같네요. 😉

2021-01-08 16:54 UTC, Hue9010 commented on src/test/java/carracing/domain/CarTest.java
> +    void isCarPositionEqualToIndex1() {
저는 DisplayName을 사용하면 테스트 메서드 네임은 약간 너프하게 작성하는 편인데 이건 사람에 따라 다를 수 있다는 점 꼭 참고해 주세요.

2021-01-08 17:02 UTC, merged

2021-01-12 02:57 UTC, pilgyumin commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
앗 runtimeException을 throws을 한것은 잘못 작성 된 것 같네요 해당 부분은 수정하겠습니다!

2021-01-12 02:59 UTC, pilgyumin commented on src/main/java/carracing/domain/Car.java
> +        return name != null && MINIMUM_NAME_LENGTH <= name.length() && name.length() <= MAXIMUM_NAME_LENGTH;
👍👍

2021-01-12 03:10 UTC, pilgyumin commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
넵 해당 부분 반영하겠습니다.

2021-01-12 03:10 UTC, pilgyumin commented on src/test/java/carracing/domain/CarTest.java
> +    void isCarPositionEqualToIndex1() {
넵 참고하겠습니다!