[ky.kiske] 코드 리뷰 요청합니다.
NewKrew2021/java-racingcar-kakao pull request #61
Opened 2021-01-06 18:08 UTC by SimJung

말씀해주신 부분들에 대해서 나름 궁리해보았습니다만, 여전히 갈 길이 먼 것 같습니다 ㅜㅜ
감사합니다!!

2021-01-07 02:33 UTC, parkjoos requested changes
고생 많으셨습니다. 
지난번에 제가 제안 드린 부분들에 대해 많이 신경 써서 작업 해주신것 같아요 
입출력 부분만 따로 분리 되어도 훨씬 보기 좋습니다. 

그리고 항상 테스트 코드가 모든 코드를 커버한다는 생각으로 작업 해 주셨으면 좋겠습니다.
인텔리제이에서 테스트를 실행 할때 Test with Coverage 로 실행 하시면 
내 코드중에 어느 코드가 테스트에 커버되지 않았는지를 홗인 할 수 있어요 
불가피한 코드를 빼고는 모든 코드가 커버 될수있도록 연습해 보면 좋을 것 같아요
![image](https://user-images.githubusercontent.com/61861989/103843606-7cfdcd80-50db-11eb-88de-61d49675b112.png)

커멘트 중에 도메인으로 기능을 위임했으면 하는 부분들이 있어요 이부분 한번 확인해 주시고
제가 남긴 커멘트들은 모두 적용하려고 노력 하실 필요는 없습니다.
혹시 너무 어렵거나 질문이 있으면 언제든지 DM 이나 댓글 남겨 주세요

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/RandomNumber.java
> +package carracing.domain;
이런 클래스는 domain 으로 보지 않죠 utility 성 클래스 라고 해요. 새로운 다른 이름의 패키지를만들어서 이동시켜 보면 좋을것 같아요

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/view/CarRacingInfoPrint.java
> +}
출력 기능을 분리한 부분 좋습니다. 👍

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/CarRacingProgram.java
> +package carracing.domain;
지금 이 클래스도 도메인이라는 카테고리로 보긴 어려울것 같아요, MVC 에서 C 에 해당하는 부분이라고 보이고, 자바 웹 어플리케이션 에서는 보통 service ,manager 등의 이름으로 분류 한답니다.

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    private List<Car> carList;
아래 생성자에서 할당 할 필요 없이 이렇게 멤버 변수 선언할때 할당하는 부분이 더 좋을것 같아요.
그리고 생성자에서 할당한 부분은 빼버리고요
```suggestion
    private final List<Car> carList = new ArrayList<>();
```

물론 생성자에 따라 할당을 안해야 할때도 있다면 지금 처럼 하는게 맞아요
그걸 의도 한게 아니라면 다른 생성자를 만들때에 실수할 여지가 생길 수 있을 것 같아요

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/RacingInfoScanner.java
> +package carracing.domain;
이 입력을 담당하는 클래스도 도메인 으로 볼수는 없을것 같아요 이 클래스도 일종의 view 라고 볼 수 있지 않을까요? 사용자에게 입력을 요청하고 입력을 받아주는 화면 이라고 생각한다면요

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/CarRacingProgram.java
> +        }
아래쪽에 playOneCycle 메소드 에서는 stream 을 활용하셨는데 이부분도 stream 을 활용해 보면 어떨까요? 
힌트를 드리면 stream().map 을 사용하면 아주 간결하고 읽기 좋은 코드가 만들어 질것 같습니다.

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/CarRacingProgram.java
> +        totalMoveCount = RacingInfoScanner.insertRaceTryCount();
이 변수는 이 메소드 내에서만 사용되는 것 같네요, 멤버 변수에서는 지우고 로컬변수로 변경하는게 좋아 보입니다.

2021-01-07 02:33 UTC, parkjoos commented on src/test/java/carracing/CarTest.java
>  package carracing;
main 코드의 패키지는 정리가 되어 있는데 test 코드는 패키지 정리가 안되어 있어요
main 클래스에 대응되는 test 클래스는 같은 패키지에 포함되도록 정리해 보면 좋을 것 같습니다.

2021-01-07 02:33 UTC, parkjoos commented on src/test/java/carracing/CarTest.java
>  }
Car 의 go method 에 대한 테스트가 빠져있어요

2021-01-07 02:33 UTC, parkjoos commented on src/test/java/carracing/CarRacingProgramTest.java
>  }
자동차 이름이 비어 있는 경우에 대한 테스트 는 빠져 있어요 ("car1,,cae3" 이렇게 입력했을때 실패하는지 검증 하는 부분이요)

split 한 결과가 정상인지에 대한 테스트도 빠져 있어요 

둘다 로직으로는 구현이 되어 있는데 테스트가 없어서 말씀 드립니다.
항상 테스트를 먼저 작성하고 해당되는 로직을 구현하시기를 추천드립니다.

2021-01-07 02:33 UTC, parkjoos commented on src/main/java/carracing/domain/CarRacingProgram.java
> +    }
자동차의 이름에 대한 validation 코드 들인데요 이부분은 Car 도메인의 역할로 보면 어떨까요? 
CarRacingProgram 에서 체크 하는 것 보다 Car 도메인으로 한번 위임해 보면 좋을 것 같아요

2021-01-08 08:09 UTC, SimJung commented
피드백 주신 내용 반영하여 커밋하고 푸쉬 해보았습니다만, 이전까지 하던 방식으로 PR을 보내려니 아직 여기가 열려있는 것 같아서 이렇게 남겨봅니다. 여러 부분들에 대한 조언 주셔서 감사합니다! 
테스트 코드를 작성하는 부분에 대해 질문이 있습니다만, 
1. private한 메소드들은 테스트를 어떤 식으로 진행해야 할지 궁금합니다! 
2. 메소드의 특성상 반환값이 없는 void 형 메소드일 경우 어떤 식으로 테스트를 진행해야 할지 궁금합니다!
3. 입출력이나 Main 프로그램의 경우에도 테스트를 진행해야 할지 궁금합니다!
4. 테스트 커버리지 기능을 매우 유용하게 썼습니다만, 어느 순간 제대로 다른 테스트는 진행되지만 창에 뜨는 테스트 범위가 도메인 패키지로 고정되어 버리는 경우가 생기는 데, 이럴 경우엔 어떻게 설정해야 테스트 커버리지 범위가 정상적으로 나오는지 알고 싶습니다!
감사합니다!!

2021-01-08 10:11 UTC, parkjoos requested changes
안녕하세요! 
많은 부분 개선된게 보이네요 👍
입출력이나 main 클래스 처럼 검증하기 어렵거나 검증이 필요 없는 부분은 꼭 커버하려고 하지 않아도 된다고 생각해요
TDD 가 익숙해지면 검증이 불필요하거나 불가능한 부분 빼고는 자연스럽게 커버가 잘 될것이라고 생각이 됩니다.
제가 위에 추천드린 커버리지 체크는 TDD 를 하면서 혹시나 내가 놓치고 가는 부분이 있나 참고 하는 용도로 생각해 주시면 좋을것 같습니다.
void 메소드에 대한 테스트는 제가 코멘트로 남겨 보았구요
이부분만 수정해주시면 바로 머지해도 될것 같아요
private 메소드에 대한 의견은 별도 댓글로 남기겠습니다. 
정말 고생 많으셨어요

2021-01-08 10:11 UTC, parkjoos commented on src/main/java/carracing/service/CarRacingProgram.java
> +    private List<Car> carList;
아마 로또 미션을 진행하거나 강의를 통해 보셨겠지만 carList 를 일급 컬렉션으로 만들면 아래 많은 메소드 들이 해당 도메인으로 위임 될 수 있어요
이 부분은 로또을 통해서 일급 컬렉션을 만들어 보면서 꼭 연습해 보세요

2021-01-08 10:11 UTC, parkjoos commented on src/main/java/carracing/service/CarRacingProgram.java
> +    }
아하 테스트에서 어떻게 검증해야 할지 몰라 true 를 억지로 리턴이 된거군요
커버리지를 채우기 위해서  이렇게 테스트를 하는것은 아무 의미가 없어요
리턴된 결과를 검증하려 하지 말고 이 메소드를 통해서 변화되는 어떤 값이 있으면 그 값을 검증하는 방식이면 될것 같습니다. 
이 메소드의 경우 완료가 된 이후에는 반드시 우승자가 나오게 되어 있네요 
테스트에서 race() 이후 findRaceWinner()의 결과가 있는지 체크해 보면 어떨까요?

2021-01-08 10:21 UTC, parkjoos commented
private 메소드에 대해 테스트를 해야 하는지 말아야 하는지 한다면 어떤 방법으로 하는지는
정말 논쟁이 많은 주제에요. 그래서 제가 답을 드릴수는 없습니다. ㅋㅋ 
한번 어떤 이유로 논쟁이 일어나는지 검색해 보면 좋을것 같습니다. 
그런데 제 의견을 말씀 드리면 private 인데 꼭 테스트가 필요하다고 생각되면 테스트를 해도 된다고 생각해요
테스트를 하는방법은 private 접근 제한자를 protected 로 변경해서 같은 패키지 내의 테스트 클래스에서만 접근이 가능하도록 하는 방식입니다. 
이부분은 정말 제 개인적인 취향과 생각이니 참고만 해주시고
이 미션에서는 TDD 를 연습하는 부분이 중요하니 다른 메소드에 의해 커버가 되지 않고 꼭 테스트가 필요하다면 public 이나 protected로 열고 테스트가 되도록 연습해보는편이 더 좋을것 같습니다.

2021-01-11 09:04 UTC, SimJung commented
남겨주신 코멘트가 정말 많은 도움이 되었습니다! 항상 감사합니다 ㅜㅜ
테스트의 경우, 최대한 많은 메소드를 테스트 하는 것을 목표로 하되, 피치 못할 경우(예를 들어 함수 내부에서 private , 혹은 반환형이 void인 함수를 호출하는 경우, 아니면 그 자체가 private 하거나 void한 경우) 상위 레벨의 메소드를 호출하고 해당 메소드의 결과로 바뀌는 상태값을 확인하는 방식으로 테스트하면 되는 것이라 이해하면 될까요??

2021-01-11 09:13 UTC, parkjoos commented
네네 반환이 없다고 해서 테스트가 불가능 하지 않다는 뜻이었어요 
메소드를 통해서 어떤 상태가 바뀔수도 있기 때문에 
그런 녀석들은 그 바뀐 상태가 원하는 결과인지 확인하면 될 것 같습니다.

2021-01-11 09:19 UTC, parkjoos approved these changes
ky 안녕하세요 
일급 컬렉션 까지 적용해 보셨네요 
매번 리뷰마다 엄청나게 발전되고 있는 모습이 보여서 제가 아주 뿌듯합니다. 👍👍
이번 미션은 이만 마무리 되어도 좋을 것 같네요
다른 미션에서도 화이팅 해주세요!
혹시 부족한 부분 있으면 다시 PR 주시면 확인후에 머지 하도록 할께요
그럼 수고 많으셨습니다. 👏

2021-01-11 09:19 UTC, parkjoos commented on src/main/java/carracing/service/CarRacingProgram.java
> +    }
이부분 아직 반영이 안되어 있는데요. 다른 미션에서 이런 부분에 신경 써서 작업해 보세요

2021-01-11 09:19 UTC, merged

2021-01-11 09:23 UTC, SimJung commented
감사합니다!!!! 실수가 있어 바로 수정하였습니다. 덕분에 즐겁고 유익한 미션 진행할 수 있었습니다! 정말 감사합니다^^