[sierra.s] 코드리뷰 2단계 요청드립니다.
NewKrew2021/java-racingcar-kakao pull request #64
Opened 2021-01-07 11:23 UTC by 32sylee

안녕하세요😃 1단계 코드리뷰 때 좋은 피드백들 감사했습니다!!
참고 자료들도 링크해주셔서 많이 공부할 수 있었던 것 같아요.
피드백 반영하여 레이싱 게임 코드리뷰 2단계 요청드립니다.

그리고 [1단계 코드리뷰](https://github.com/next-step/java-racingcar-kakao/pull/34#discussion_r551989779) 내용을 반영해서 Car에서 움직이는 행동을 넘겨받을 수 있도록 변경을 했는데요!
그렇게 하고보니 Cars를 테스트할 때 차의 움직임을 임의로 설정해 주는 것이 어려워지더라구요.
그래서 지난번에 [답변 주셨던 내용](https://github.com/next-step/java-racingcar-kakao/pull/34#discussion_r552006749)과 다르게 Cars 클래스에 테스트를 위한 생성자를 추가하게 되었습니다😢
더 좋은 방법이 있을까요..?😂

2021-01-07 13:06 UTC, 32sylee commented on src/main/java/carRace/Cars.java
> +    public Cars(List<Car> carList) {
이 생성자는 사실 private이어야 하는데 getWinner 메서드의 테스트를 위해 public이 되었습니다😢

2021-01-07 13:28 UTC, limmmee-bonjour requested changes
안녕하세요 sierra :) 벨 입니다. 😄 
요청드린 부분 아주 잘 반영해주셨어요 👏  💯 
다만 패키지 구조 및 controller 경계가 모호합니다. 이 부분에 대해 피드백 드렸어요!
[ 도전! ] 이라고 코멘트 드린부분은 고민해보셔서 수정해주시기 바랍니다.
열심히 하시는 모습 보기 좋습니다! 화이팅 입니다!!

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/Car.java
> +    public void go(MovingStrategy strategy) {
전략 패턴을 사용하여 좀 더 유연하게! 좋아요 :100:

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/Cars.java
> +    public static Cars fromNames(String[] names) {
정적 팩토리 메서드를 적용해주셨네요 이름도 적절해요 👍

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/Console.java
>      public static void main(String[] args) {
적절한 위치를 찾다가 여기에 남기게 되었어요 :)

[ 도전! ]
MVC 구조를 잘 나누어주셨지만 패키지가 나뉘어져있지 않네요!
패키지의 구조는 다양한 방법론들이 있는데요 (계층기반, 기능기반, 컴포넌트기반)
현업에서도 패키지 룰이 있고 다양하게 사용하고 있습니다 :)
이번에는 계층기반으로 패키지를 (controller, domain, service 등등) 나누어 볼까요?

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/RacingGame.java
>  public class RacingGame {
RacingGame은 controller일까요? 아니면 도메인일까요? 
개발시에는 경계를 명확하게 나누는 것이 좋습니다. 제가 봤을 때는 RacingGame은 멤버 변수를 가지고 있는 도메인으로 보여지는데요!

[ 도전! ]
만약 RacingGame이 도메인이라면 입출력에 대한 내용을 외부(Controller)에서 주입받고 오히려 전략은 RacingGame에서 생성해도 좋을 듯 합니다! (더 나아가면 Cars or Car의 팩토리 클래스가 있어도 좋을 것 같아요
함께읽으면 좋은글 : [팩토리 클래스](https://woovictory.github.io/2019/02/07/Design-Pattern-Factory-Pattern/))
만약 RacingGame이 Controller 목적으로 만들어졌다면 RacingGame + Console 을 합쳐도 될 것 같습니다!

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/RacingGameUI.java
> -    public static Cars getCarsFromUser() {
Cars와 입출력이 관계가 느슨해졌네요 좋습니다 👍

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/RandomStrategy.java
> +        return MOVE_BOUND <= getRandomNumber();
보통은 작거나같다(<=) 보다는 크거나같다(>=) 를 사용하는 것 같아요! 😉

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/test/java/carRace/RandomStrategyTest.java
> +            assertThat(randomStrategy.getRandomNumber()).isBetween(0, 9);
isBetween으로 잘 테스트 해주셨네요 👍 👍 

[ 도전! ] 
RandomStrategy의 주요한 메서드인 movable() 메서드 테스트가 빠져있네요!
만약 MOVE_BOUND의 요구사항은 4였는데, 잘못해서 5로 셋팅했다면? 프로젝트는 잘못 돌아갈거예요 @.@
게다가 getRandomNumber() 메서드는 테스트케이스에서만 사용되어지고 있네요! (캡슐화 되어져도 될것 같은 코드죠?)

힌트를 드리자면 우리는 CheckMovableByRandomNumber 상속받는 CheckMovableByRandomNumberForTest를 만들어 보는건 어때요? 물론 이 클래스는 테스트 패키지에만 있어야 겠죠?
makeRandomValue() 는 public 보다는 protected로 변경하여 접근자를 제한하는거죠! (private가 제일 좋겠지만 이정도는 괜찮을 것 같아요)
makeRandomValue() 리턴 값이 우리가 원하는 값이라면?!
어짜피 Math.random()는 이미 유틸성 메소드이기 때문에 굳이 테스트 할 필요가 없어 보이거든요~
그럼 한번 도전해 보아요!! 🤞 🤞

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/test/java/carRace/CarTest.java
> -    @Test
테스트를 작성해주실땐 @DisplayName을 습관적으로 적어주세요!

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/test/java/carRace/CarTest.java
> +    @MethodSource("provideCar")
👍 👍   열심히 공부하셨군요!

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/test/java/carRace/CarsTest.java
>  public class CarsTest {
Q. 그래서 지난번에 답변 주셨던 내용과 다르게 Cars 클래스에 테스트를 위한 생성자를 추가하게 되었습니다😢
A. 테스트를 위한 생성자가 어떤걸까요~? 기본 생성자, 정적 팩토리 메서드 둘 다 코드내에 사용되어지고 있는것 같은데
제가 질문을 잘 이해하지 못했어요! 좀 더 자세하게 설명해주실수 있을까요~?

2021-01-07 13:28 UTC, limmmee-bonjour commented on src/main/java/carRace/MovingStrategy.java
> +public interface MovingStrategy {
👏  잘 반영해주셨습니다~ 👏

2021-01-08 03:00 UTC, limmmee-bonjour commented on src/main/java/carRace/Cars.java
> +    public Cars(List<Car> carList) {
아하! 그 말씀이셨군요~
중요 메서드들의 접근 제한자를 지정하는것은 중요한 부분이겠죠!
그러나 여기서는 캡슐화를 위한 메소드라기 보다는 생성자의 의미가 강하기 때문에 접근 제한자에 크게 고민할 필요는 없어보여요^^
현재는 물론 테스트케이스에서만 사용되어지겠지만 name을 받아서 Cars를 처리하는게 아닌 Car list를 통해 Cars를 만든 요구사항이 추가될 가능성이 커보입니다! 따라서 이렇게 처리해주셔도 크게 무리는 없어보입니다! 
추가로 하나 의견드리자면 (어제는 제가 저걸 못봤네요+_+)

도메인의 멤버변수는 웬만하면 private final 로 지정해주는 것이 좋습니다.
멤버변수는 생성자에서 기본으로 셋팅되는 것이 좋구요! 
아래와 같이 셋팅해주시면 외부에서 모두 접근이 가능해서 좋지 않아요! 누군가가 갑자기 객체를 바꿀수도 있겠구요! ㅎㅎ
```
List<Car> carList;
```
그럼 이 부분도 [ 도전! ]에 포함시켜주세요 :) - 멤버변수 private final 처리

2021-01-10 13:36 UTC, 32sylee commented on src/main/java/carRace/Cars.java
> +    public Cars(List<Car> carList) {
답변 감사합니다!!+_+

2021-01-10 13:38 UTC, 32sylee commented on src/main/java/carRace/Cars.java
> +    public Cars(List<Car> carList) {
답변 감사합니다!! :)
멤버변수 private final 처리하는거 반영해보겠습니다~!

2021-01-10 13:39 UTC, 32sylee commented on src/main/java/carRace/Console.java
>      public static void main(String[] args) {
네!! 말씀주신대로 패키지 나눠보겠습니다 ㅎㅎ

2021-01-10 13:48 UTC, 32sylee commented on src/main/java/carRace/RacingGame.java
>  public class RacingGame {
RacingGame을 컨트롤러라고 생각하고 개발을 하긴 했었는데 피드백 주신 내용 읽어보니 도메인에 가까운 것 같네요!
적어주신 내용 반영해서 역할 경계가 잘 드러나도록 수정해보겠습니다

2021-01-10 13:48 UTC, 32sylee commented on src/main/java/carRace/RandomStrategy.java
> +        return MOVE_BOUND <= getRandomNumber();
앗!! 네 수정하겠습니다😀

2021-01-10 13:55 UTC, 32sylee commented on src/test/java/carRace/RandomStrategyTest.java
> +            assertThat(randomStrategy.getRandomNumber()).isBetween(0, 9);
protected로 만들고 상속을 받는 방법도 있었네요😲 좋은 방법 감사합니다!
내용 반영해서 수정해볼게요!

2021-01-10 13:55 UTC, 32sylee commented on src/test/java/carRace/CarTest.java
> -    @Test
넵 수정하겠습니다!!

2021-01-11 06:45 UTC, 32sylee commented
@limmmee-bonjour
벨 안녕하세요! 2차 코드리뷰 감사합니다😊
코멘트주신 내용들 수정하였고, 추가로 차 이름을 Name 클래스로 만들어서 이름에 대한 validation을 Name 클래스에서 하도록 변경했습니다!

다만 https://github.com/next-step/java-racingcar-kakao/pull/64#discussion_r553315506 에서 말씀하신 Car, Car의 팩토리클래스 관련 내용을 어떻게 적용해야 할 지 감이 잘 오지 않아서 질문드립니다.

경기 참가자(Player)로 Car, Bike 등등 여러 종류의 객체가 올 수 있다고 생각을 하고,
Car 클래스가 Player를 상속받는 상황에서 팩토리클래스를 적용한다고 생각하면 될까요?

2021-01-12 01:32 UTC, limmmee-bonjour approved these changes
안녕하세요 sierra ! 벨입니다.
요청드린 피드백을 잘 반영해주셔서 코드가 많이 좋아졌습니다 👍 💯 
자동차 경주 프로젝트 진행하면서 고민을 많이 해주신 모습이 보기 좋습니다!
추가로 궁금하신 점 있으시면 언제든 DM 주셔요! 그럼 다음 미션도 화이팅 입니다!! 😄

2021-01-12 01:32 UTC, limmmee-bonjour commented on src/main/java/carRace/domain/Cars.java
> +    private final List<Car> carList;
final 좋습니다 :) 👍

2021-01-12 01:32 UTC, limmmee-bonjour commented on src/main/java/carRace/strategy/RandomStrategy.java
> +        return getRandomNumber() >= MOVE_BOUND;
가독성이 좋아졌어요 💯

2021-01-12 01:32 UTC, limmmee-bonjour commented on src/test/java/carRace/domain/CarTest.java
> +    @DisplayName("차가 한 칸 이동한다.")
displayName을 붙여주셔서 어떤 테스트인지 한눈에 알 수 있네요 👏 👏

2021-01-12 01:32 UTC, limmmee-bonjour commented on src/test/java/carRace/strategy/RandomStrategyTest.java
> +    }
경계 테스트를 잘 해주셨습니다 :) 👍 💯

2021-01-12 01:32 UTC, limmmee-bonjour commented on src/main/java/carRace/domain/RacingGame.java
> +public class RacingGame {
Q. 다만 #64 (comment) 에서 말씀하신 Car, Car의 팩토리클래스 관련 내용을 어떻게 적용해야 할 지 감이 잘 오지 않아서 질문드립니다.
경기 참가자(Player)로 Car, Bike 등등 여러 종류의 객체가 올 수 있다고 생각을 하고,
Car 클래스가 Player를 상속받는 상황에서 팩토리클래스를 적용한다고 생각하면 될까요?

A. 팩토리 클래스는 도메인보다는 서비스 느낌이 좀 더 있는 것 같습니다.
그래서 Car에 대한 전략이나 생성에 관련된 일을 하죠 (약간 생성자 서비스 느낌입니다!)
그런데 sierra는 RacingGame을 도메인화 시켜주셨네요 :) 이 방법도 좋습니다! 
무엇이든 경계가 명확한것이 좋은 것 같아요!
무조건 팩토리패턴을 쓰기보다 이렇게 객체화 할 수 있다면 이런 방법으로 사용하는 것도 좋습니다 👍

2021-01-12 01:33 UTC, merged

2021-01-12 06:45 UTC, 32sylee commented on src/main/java/carRace/domain/RacingGame.java
> +public class RacingGame {
아하! 만약 팩토리 클래스를 쓴다면 전략 생성을 RacingGame이 아니라 Car의 팩토리클래스에서 해주는 방식이 되겠군요!
디자인 패턴에 대해서도 꼭 더 공부해야겠어요!
알려주신 내용 잘 기억해두고 다음에 써먹어 보겠습니다 ㅎㅎ 좋은 피드백들 정말 감사합니다🙏