[dy.namic] 자동차 경주 2단계 코드리뷰 요청합니다.
NewKrew2021/java-racingcar-kakao pull request #69
Opened 2021-01-09 18:09 UTC by kdy2000

안녕하세요 dy입니다 :)

자동차 경주 2단계입니다. 저번에 피드백 주신 내용, 2단계 요구사항 을 반영하여 구현하였습니다.

2021-01-11 03:25 UTC, ljh131 requested changes
안녕하세요. 몇 가지 커멘트 드렸습니다. 생각해보시고 수정이 필요하겠다 싶은 부분들은 수정해주시면 좋겠습니다. 그리고 커멘트에 대해 궁금한 점이 있으시면 질문주세요.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/controller/GameController.java
> +            List<Integer> movingNumbers = randomGenerator.getIntegerList(candidates.size());
랜덤을 외부에서 주는 방법도 있겠지만, strategy pattern을 사용하는 방법도 있습니다.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Car.java
> +public class Car{
코딩스타일도 한번 신경써보세요.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Cars.java
> +    /* 이 생성자는 테스트 할때만 사용해야 합니다. */
테스트용 생성자를 따로 두는 것보다는 하나로 할 수 있는 방법은 없을까요?

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Car.java
> +    public Car(String name, int location){
이것도 테스트 전용으로 만든 것 같네요.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Cars.java
> +        for(Car car : carList){
스트림을 쓰면 더 간단하지 않을까요

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Car.java
> +    public boolean equals(Object o) {
오버라이드를 왜 하신건가요? 그리고 equals를 오버라이드하면 hashCode도 오버라이드 해야합니다.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Winners.java
> +    public boolean equals(Object o) {
여기도 마찬가지고요

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/view/Output.java
> +    public static void printAllCars(Cars cars) {
이왕 CarDTOs라는걸 만들었으니 그걸 넘기는게 좋지 않을까요?

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/view/Input.java
> +    private static Cars retryGetCarsFromUser(){
위 메서드와 합칠 수 있지 않을까요?

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/view/Input.java
> +            return new Cars(names);
여기서 직접 Cars를 생성해주는 것보다는 인풋에 필요한 내용만 콜러에게 전달해주면 어떨까요?
그리고 성공인데 중간에 리턴하면 가독성이 별로 좋지 않습니다.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/domain/Winners.java
> +    private final List<Car> cars;
외부에서 가져가기 위한 immutable한 CarDto를 만드셨는데, 그걸 쓰면 더 좋을 것 같습니다.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/dtos/CarDTOs.java
> +public class CarDTOs {
사실 CarDto가 immutable한 이상 크게 필요는 없을 것 같아요.

2021-01-11 03:25 UTC, friediceday commented on src/test/java/carRace/domain/CarsTest.java
> +                        new Car("test1", 6),
이렇게 초기 위치 지정하는 방식은 테스트 전용이고 실제 실행시엔 사용하지 않는데요, 실행하는 것과 유사하게 테스트하는 방법은 없을까요?

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/dtos/CarDTO.java
> +    public final String name;
private이 좋겠습니다.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/dtos/CarDTO.java
> +    public boolean equals(Object o) {
여기도 있었네요.

2021-01-11 03:25 UTC, friediceday commented on src/main/java/carRace/dtos/CarDTOs.java
> +    public boolean equals(Object o) {
여기도 있고요

2021-01-11 17:06 UTC, kdy2000 commented
피드백 사항 반영하여, 리팩토링및 기능추가 하였습니다.

2021-01-12 03:17 UTC, ljh131 reviewed
전체적으로 개선된 것 같습니다. 테스트도 상세하게 만드셨네요. 이번 미션은 머지하겠습니다. 
커멘트 몇 가지 남겼으니 참고해보시면 좋겠습니다.

2021-01-12 03:17 UTC, friediceday commented on src/main/java/carRace/domain/RandomMovingStrategy.java
> +    Random random = new Random();
이건 패키지 프라이빗인가요?

2021-01-12 03:17 UTC, friediceday commented on src/main/java/carRace/dtos/CarDTOs.java
> +        this.dtos = dtos;
이 클래스를 리스트까지 이뮤터블로 만드려는 의도가 있으셨군요.
그렇다면 여기서 레퍼런스만 할당하는게 아니라 딥카피 해야 완전히 안전하지 않을까요?
콜러 쪽에서 넘겨준 리스트를 가지고 수정할 수도 있으니까요.

2021-01-12 03:18 UTC, merged

2021-01-12 03:35 UTC, kdy2000 commented on src/main/java/carRace/domain/RandomMovingStrategy.java
> +    Random random = new Random();
아 Random 객체가 패키지-프라이빗으로 되어있군요. 이것을 private으로 바꾸겠습니다.

2021-01-12 03:35 UTC, kdy2000 commented on src/main/java/carRace/dtos/CarDTOs.java
> +        this.dtos = dtos;
아하! 그렇군요. 알겠습니다. 피드백 감사합니다.